--Add By Tany 2015-05-25 疾病的医院医保对应表
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[JC_DISEASE_YYYBDZ]') AND type in (N'U'))
CREATE TABLE [dbo].[JC_DISEASE_YYYBDZ](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[YYJBBM] [varchar](30) NOT NULL,
	[YBJKLX] [int] NOT NULL default 0,
	[YBJBBM] [varchar](100) NOT NULL,
	[YBJBMC] [varchar](100) NOT NULL,
 CONSTRAINT [PK_JC_DISEASE_YYYBDZ] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE NONCLUSTERED INDEX IX_JC_DISEASE_YYYBDZ_YBJBBM ON dbo.JC_DISEASE_YYYBDZ
	(
	YBJBBM
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX IX_JC_DISEASE_YYYBDZ_YYJBBM ON dbo.JC_DISEASE_YYYBDZ
	(
	YYJBBM
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO