//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5477
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.5477 版自动生成。
// 
#pragma warning disable 1591

namespace ts.WHZXYY.Portal.WebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="XMLStreamServiceSoap", Namespace="http://wuhan-central-hospital.org/platform")]
    public partial class XMLStreamService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ProcessInputOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public XMLStreamService() {
            this.Url = global::ts.WHZXYY.Portal.Properties.Settings.Default.ts_WHZXYY_Portal_WebReference_XMLStreamService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ProcessInputCompletedEventHandler ProcessInputCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wuhan-central-hospital.org/platform/Project.Proxy.WS.XMLStreamService.Proc" +
            "essInput", RequestNamespace="http://wuhan-central-hospital.org/platform", ResponseNamespace="http://wuhan-central-hospital.org/platform", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ProcessInput(string input, long timeout, [System.Xml.Serialization.XmlIgnoreAttribute()] bool timeoutSpecified, string target) {
            object[] results = this.Invoke("ProcessInput", new object[] {
                        input,
                        timeout,
                        timeoutSpecified,
                        target});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessInputAsync(string input, long timeout, bool timeoutSpecified, string target) {
            this.ProcessInputAsync(input, timeout, timeoutSpecified, target, null);
        }
        
        /// <remarks/>
        public void ProcessInputAsync(string input, long timeout, bool timeoutSpecified, string target, object userState) {
            if ((this.ProcessInputOperationCompleted == null)) {
                this.ProcessInputOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessInputOperationCompleted);
            }
            this.InvokeAsync("ProcessInput", new object[] {
                        input,
                        timeout,
                        timeoutSpecified,
                        target}, this.ProcessInputOperationCompleted, userState);
        }
        
        private void OnProcessInputOperationCompleted(object arg) {
            if ((this.ProcessInputCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessInputCompleted(this, new ProcessInputCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void ProcessInputCompletedEventHandler(object sender, ProcessInputCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessInputCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessInputCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591