IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[SP_ZY_TJ_BRSRTJ]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[SP_ZY_TJ_BRSRTJ]
GO
CREATE PROCEDURE [DBO].[SP_ZY_TJ_BRSRTJ]
 (  
	@RQ1 DATETIME,
	@RQ2 DATETIME,
	@DEPTID BIGINT, --科室
	@TJ_TYPE SMALLINT    --统计类型1=出院2=在院
 ) 
AS
/*
  住院病人收入统计
  TANY 2009-12-01
*/
BEGIN
	
	IF @TJ_TYPE=1
	BEGIN
		SELECT '0' AS 序号, INPATIENT_NO 住院号,NAME 病人姓名,SEX_NAME 性别,AGE 年龄,CONVERT(VARCHAR,A.BILLNO) AS 票据号,
			CASE A.CZ_FLAG WHEN 1 THEN '被冲帐' WHEN 2 THEN '冲帐' ELSE '' END AS 冲帐标志,
			DBO.FUN_ZY_SEEKDEPTNAME(A.DEPT_ID) AS 住院科室,ZYDOC_NAME 经治医生,DBO.FUN_GETDATE(A.DISCHARGE_DATE) AS 结算时间,
			DBO.FUN_GETDATE(B.IN_DATE) 入院日期,DBO.FUN_GETDATE(B.OUT_DATE) 出院日期,RYTS 住院天数,
			DEPTOSITS AS 预交款, A.NFEE-A.AGIO_FEE AS 总费用,
			PATCH_FEE AS 补款, RECEDE_FEE AS 退款, 
			YB_FEE 医保支付, SELF_FEE AS 自付, AGIO_FEE AS 折扣, 
			LACK_FEE AS 欠费, SAVE_FEE AS 暂存,
			ISNULL((SELECT SUM(NVALUES) FROM ZY_DEPOSITS WHERE DISCHARGE_ID=A.ID AND NTRANS IN(11,21) AND NMODE = 3),0) 收退POS,
			CASE DISCHARGETYPE WHEN 0 THEN '自费' WHEN 1 THEN /*'医保'*/B.YBLX_NAME WHEN 2 THEN '公费' WHEN 3 THEN '其他' ELSE '' END AS 结算类型, 
			BRLX_NAME 病人类型,
			DBO.FUN_ZY_SEEKEMPLOYEENAME(USERID) AS 操作员  
		INTO #JS_TMP1
		FROM ZY_DISCHARGE AS A 
		LEFT JOIN VI_ZY_VINPATIENT_ALL AS B ON A.INPATIENT_ID=B.INPATIENT_ID AND B.BABY_ID=0
		WHERE A.CANCEL_BIT=0 
			AND A.DISCHARGE_DATE >= @RQ1 AND A.DISCHARGE_DATE <= @RQ2
			AND (B.DEPT_ID=@DEPTID OR @DEPTID=-1)
		ORDER BY A.BILLNO,A.CZ_FLAG,A.DEPT_ID,INPATIENT_NO ASC  

		SELECT * FROM #JS_TMP1
		UNION ALL
		SELECT '99999999' AS 序号, '' 住院号,'' 病人姓名,'' 性别,NULL 年龄,'' 票据号,
			'' AS 冲帐标志,
			'' AS 住院科室,'' 经治医生,'' AS 结算时间,'' 入院日期,'' 出院日期,NULL 住院天数,
			SUM(预交款) AS 预交款, SUM(总费用) AS 总费用,
			SUM(补款) AS 补款, SUM(退款) AS 退款, 
			SUM(医保支付) 医保支付, SUM(自付) AS 自付, SUM(折扣) AS 折扣, 
			SUM(欠费) AS 欠费, SUM(暂存) AS 暂存,
			SUM(收退POS) 收退POS,
			'' AS 结算类型,'' 病人类型,
			'' AS 操作员 
		FROM #JS_TMP1

		DROP TABLE #JS_TMP1
	END

	IF @TJ_TYPE=2
	BEGIN
		SELECT A.INPATIENT_ID,SUM(JE) FEE
		INTO #TMP_FEE 
		FROM 
		(
			SELECT A.INPATIENT_ID,A.ACVALUE JE 
			FROM ZY_FEE_SPECI A INNER JOIN 
			ZY_DISCHARGE B ON A.DISCHARGE_ID=B.ID  
			WHERE CHARGE_BIT=1 AND DELETE_BIT=0 
			AND CHARGE_DATE<=@RQ2 
			AND DISCHARGE_DATE>@RQ2 AND B.CZ_FLAG=0
			UNION ALL
			SELECT A.INPATIENT_ID,A.ACVALUE JE 
			FROM ZY_FEE_SPECI A
			WHERE CHARGE_BIT=1 AND DELETE_BIT=0 
			AND CHARGE_DATE<=@RQ2 AND DISCHARGE_BIT=0   
			UNION ALL 
			SELECT A.INPATIENT_ID,ITEMVALUES JE 
			FROM ZY_DISCHARGE A INNER JOIN ZY_DISCHARGELIST B ON A.ID=B.DISCHARGE_ID
			WHERE A.CZ_FLAG=2 AND DISCHARGE_DATE>@RQ2 AND CZ_ID NOT IN
			(SELECT ID FROM ZY_DISCHARGE WHERE DISCHARGE_DATE>@RQ2 AND CZ_FLAG=1)
		) A
		GROUP BY A.INPATIENT_ID

		SELECT A.INPATIENT_ID,SUM(JE) YJJ,SUM(XJ) XJ,SUM(ZP) ZP,SUM(POS) POS
		INTO #TMP_YJJ
		FROM 
		(
			SELECT A.INPATIENT_ID,A.NVALUES JE,
			CASE NMODE WHEN 1 THEN A.NVALUES ELSE 0 END XJ,
			CASE NMODE WHEN 2 THEN A.NVALUES ELSE 0 END ZP,
			CASE NMODE WHEN 3 THEN A.NVALUES ELSE 0 END POS
			FROM ZY_DEPOSITS A INNER JOIN 
			ZY_DISCHARGE B ON A.DISCHARGE_ID=B.ID  
			WHERE ARRIVE_BIT=1 AND A.CANCEL_BIT=0 
			AND ARRIVE_DATE<=@RQ2 
			AND DISCHARGE_DATE>@RQ2 --AND B.CZ_FLAG=0
			AND NTRANS IN (10,20)
			UNION ALL
			SELECT A.INPATIENT_ID,A.NVALUES JE,
			CASE NMODE WHEN 1 THEN A.NVALUES ELSE 0 END XJ,
			CASE NMODE WHEN 2 THEN A.NVALUES ELSE 0 END ZP,
			CASE NMODE WHEN 3 THEN A.NVALUES ELSE 0 END POS
			FROM ZY_DEPOSITS A
			WHERE ARRIVE_BIT=1 AND A.CANCEL_BIT=0 
			AND ARRIVE_DATE<=@RQ2 AND DISCHARGE_BIT=0   
		) A
		GROUP BY A.INPATIENT_ID HAVING SUM(JE)<>0

		SELECT '0' AS 序号, INPATIENT_NO 住院号,NAME 病人姓名,SEX_NAME 性别,AGE 年龄,
			CUR_DEPT_NAME AS 住院科室,ZYDOC_NAME 经治医生,
			DBO.FUN_GETDATE(A.IN_DATE) 入院日期,
			ISNULL(FEE,0) AS 总费用,ISNULL(YJJ,0) AS 预交款,
			ISNULL(XJ,0) AS 现金, ISNULL(ZP,0) AS 支票, 
			ISNULL(POS,0) POS,ISNULL(YJJ,0)-ISNULL(FEE,0) 余额,
			CASE DISCHARGETYPE WHEN 0 THEN '自费' WHEN 1 THEN YBLX_NAME WHEN 2 THEN '公费' WHEN 3 THEN '其他' ELSE '' END AS 结算类型,
			BRLX_NAME 病人类型
		INTO #TMP
		FROM VI_ZY_VINPATIENT_ALL A 
		LEFT JOIN #TMP_FEE B ON A.INPATIENT_ID=B.INPATIENT_ID AND A.BABY_ID=0
		LEFT JOIN #TMP_YJJ C ON A.INPATIENT_ID=C.INPATIENT_ID AND A.BABY_ID=0
		WHERE (B.INPATIENT_ID IS NOT NULL OR C.INPATIENT_ID IS NOT NULL)
		AND (A.DEPT_ID=@DEPTID OR @DEPTID=-1)

		SELECT * FROM #TMP
		UNION ALL
		SELECT '99' AS 序号, '' 住院号,'' 病人姓名,'' 性别,NULL 年龄,
			NULL AS 住院科室,NULL 经治医生,
			NULL 入院日期,
			SUM(总费用) AS 总费用,SUM(预交款) AS 预交款,
			SUM(现金) AS 现金, SUM(支票) AS 支票, 
			SUM(POS) POS,SUM(余额) 余额,
			'' AS 结算类型,'' 病人类型
		FROM #TMP
		ORDER BY 序号,住院科室,住院号

		DROP TABLE #TMP_FEE
		DROP TABLE #TMP_YJJ
		DROP TABLE #TMP
	END

END