IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SP_ZYHS_ORDERS_SELECTZC_INPATIENT]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SP_ZYHS_ORDERS_SELECTZC_INPATIENT]
GO
create PROCEDURE [dbo].[SP_ZYHS_ORDERS_SELECTZC_INPATIENT]
 (
  @WARDID VARCHAR(4), 
  @SELKIND INT, 
  @SELTYPE INT, 
  @BEGINDATE DATETIME, 
  @ENDDATE DATETIME,
  @INPATIENT_ID UNIQUEIDENTIFIER, 
  @BABY_ID INT
 ) 
AS
/*--------------------------------------------------------------------------
作者：TANY
说明：住院护士站-医嘱转抄
日期：2006-12-09
参数：
  @WARDID VARCHAR(4), 
  @SELKIND INT, 
  @SELTYPE INT, 
  @BEGINDATE DATETIME, 
  @ENDDATE
修改：

--------------------------------------------------------------------------*/
SET NOCOUNT ON

--新医嘱
IF @SELKIND=0
BEGIN
   --所有
   IF @SELTYPE=0
   BEGIN 
	SELECT A.STATUS_FLAG,A.ORDER_ID,A.GROUP_ID,A.NUM,
	case when  ISNUMERIC (LEFT(A.UNIT,1))>0 then '['+A.UNIT +']' else  A.UNIT end UNIT,
	A.DWLX,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,A.DOSAGE,
		A.NTYPE,A.EXEC_DEPT,CONVERT(CHAR,DATEPART(DD,A.ORDER_BDATE)) DAY1,CONVERT(CHAR,DATEPART(MI,A.ORDER_BDATE)) SECOND1,
		B.INPATIENT_ID,B.BABY_ID,B.ISMY,CASE WHEN NTYPE<=3 AND NTYPE<>0 THEN A.ITEM_CODE ELSE CHAR(A.HOITEM_ID) END ITEM_CODE,A.XMLY,
		B.BED_NO 床号,B.INPATIENT_NO 住院号,B.NAME 姓名,
		CONVERT(CHAR,DATEPART(MM,A.ORDER_BDATE)) 日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_BDATE)) 时间,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 医生,
		CASE A.MNGTYPE WHEN 0 THEN '长嘱' ELSE '临嘱'END AS 类型,
		LTRIM(RTRIM(A.ORDER_CONTEXT))+CASE WHEN ISNULL(ORDER_SPEC,'')='' THEN '' ELSE '('+LTRIM(RTRIM(ORDER_SPEC))+')' END 医嘱内容,FIRST_TIMES 次,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER) 转抄护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER1) 核对护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER2) 查对护士,
		DBO.FUN_ZY_SEEKDEPTNAME(A.EXEC_DEPT) 执行科室,
		CASE WHEN C.TENDLEVEL IS NULL THEN 0 ELSE C.TENDLEVEL END 护理级别 ,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病重' or CHARINDEX('病重',ORDER_CONTEXT)>0  THEN 1 ELSE 0 END 病重,--防止补录的
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病危' or CHARINDEX('病危',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病危,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '%饮食'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '禁食%'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '普食%'
		THEN 1
		ELSE 0
		END 饮食,
		--Add By tany 2011-06-19
		CASE NTYPE WHEN 0 THEN '出院'
		WHEN 1 THEN '西药'
		WHEN 2 THEN '成药'
		WHEN 3 THEN '草药'
		WHEN 4 THEN '治疗'
		WHEN 5 THEN '医技'
		WHEN 6 THEN '手术'
		WHEN 7 THEN '说明'
		WHEN 8 THEN '护理'
		WHEN 9 THEN '其他'
		ELSE '' END	类别,
		B.ORDER_HL,B.ORDER_BZ,B.ORDER_BW,B.ORDER_YS,A.停 ,A.SERIAL_NO,A.MNGTYPE,
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,A.USAGE,PS_FLAG,PS_ORDERID,PS_USER,A.DEPT_ID,A.DEPT_BR,A.HOITEM_ID,A.ts,A.zsl,A.zsldw
	FROM (SELECT * FROM VI_ZY_VINPATIENT_BED WHERE WARD_ID=@WARDID AND INPATIENT_ID=@INPATIENT_ID AND BABY_ID=@BABY_ID) B,
	     (SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,DWLX,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,0 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,XMLY,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_BDATE,ORDER_DOC,FIRST_TIMES,		
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>0 AND STATUS_FLAG<=5 AND MNGTYPE IN (0,1,5)
	      UNION ALL
	      SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,DWLX,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,1 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,XMLY,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_EDATE AS ORDER_BDATE,ORDER_EDOC AS ORDER_DOC, TERMINAL_TIMES AS FIRST_TIMES,
		ORDER_EUSER AS AUDITING_USER,ORDER_EUSER1 AS AUDITING_USER1,ORDER_EUSER2 AS AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,
		PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM  ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>2 AND STATUS_FLAG<=5 AND MNGTYPE=0
	      ) A LEFT JOIN JC_HOI_HL C  ON A.HOITEM_ID=C.HOITEM_ID AND A.XMLY=2
--		LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1
	WHERE A.INPATIENT_ID=B.INPATIENT_ID AND A.BABY_ID=B.BABY_ID --AND B.WARD_ID=@WARDID
	ORDER BY B.BED_NO,B.BABY_ID,B.NAME,A.MNGTYPE,A.ORDER_BDATE,A.ORDER_DOC,A.GROUP_ID,A.SERIAL_NO
   END
   --按时间段
   ELSE
   BEGIN
	SELECT A.STATUS_FLAG,A.ORDER_ID,A.GROUP_ID,A.NUM,
	case when  ISNUMERIC (LEFT(A.UNIT,1))>0 then '['+A.UNIT +']' else  A.UNIT end UNIT,A.DWLX,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,A.DOSAGE,
		A.NTYPE,A.EXEC_DEPT,CONVERT(CHAR,DATEPART(DD,A.ORDER_BDATE)) DAY1,CONVERT(CHAR,DATEPART(MI,A.ORDER_BDATE)) SECOND1,
		B.INPATIENT_ID,B.BABY_ID,B.ISMY,CASE WHEN NTYPE<=3 AND NTYPE<>0 THEN A.ITEM_CODE ELSE CONVERT(CHAR,A.HOITEM_ID) END ITEM_CODE,A.XMLY,
		B.BED_NO 床号,B.INPATIENT_NO 住院号,B.NAME 姓名,
		CONVERT(CHAR,DATEPART(MM,A.ORDER_BDATE)) 日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_BDATE)) 时间,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 医生,
		CASE A.MNGTYPE WHEN 0 THEN '长嘱' ELSE '临嘱'END AS 类型,
		LTRIM(RTRIM(A.ORDER_CONTEXT))+CASE WHEN ISNULL(ORDER_SPEC,'')='' THEN '' ELSE '('+LTRIM(RTRIM(ORDER_SPEC))+')' END 医嘱内容,FIRST_TIMES 次,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER) 转抄护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER1) 核对护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER2) 查对护士,
		DBO.FUN_ZY_SEEKDEPTNAME(A.EXEC_DEPT) 执行科室,
		CASE WHEN C.TENDLEVEL IS NULL THEN 0 ELSE C.TENDLEVEL END 护理级别 ,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病重' or CHARINDEX('病重',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病重,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病危' or CHARINDEX('病危',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病危,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '%饮食'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '禁食%'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '普食%'
		THEN 1
		ELSE 0
		END 饮食,
		--Add By tany 2011-06-19
		CASE NTYPE WHEN 0 THEN '出院'
		WHEN 1 THEN '西药'
		WHEN 2 THEN '成药'
		WHEN 3 THEN '草药'
		WHEN 4 THEN '治疗'
		WHEN 5 THEN '医技'
		WHEN 6 THEN '手术'
		WHEN 7 THEN '说明'
		WHEN 8 THEN '护理'
		WHEN 9 THEN '其他'
		ELSE '' END	类别,
		B.ORDER_HL,B.ORDER_BZ,B.ORDER_BW,B.ORDER_YS,A.停 ,A.SERIAL_NO,A.MNGTYPE,
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,A.USAGE,PS_FLAG,PS_ORDERID,PS_USER,A.DEPT_ID,A.DEPT_BR,A.HOITEM_ID,A.ts,A.zsl,A.zsldw
	FROM (SELECT * FROM VI_ZY_VINPATIENT_BED WHERE WARD_ID=@WARDID AND INPATIENT_ID=@INPATIENT_ID AND BABY_ID=@BABY_ID) B,
	     (SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,DWLX,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,0 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,XMLY,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_BDATE,ORDER_DOC,FIRST_TIMES,		
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>0 AND STATUS_FLAG<=5 AND MNGTYPE IN (0,1,5)
	      UNION ALL
	      SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,DWLX,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,1 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,XMLY,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_EDATE AS ORDER_BDATE,ORDER_EDOC AS ORDER_DOC, TERMINAL_TIMES AS FIRST_TIMES,
		ORDER_EUSER AS AUDITING_USER,ORDER_EUSER1 AS AUDITING_USER1,ORDER_EUSER2 AS AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,
		PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM  ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>2 AND STATUS_FLAG<=5 AND MNGTYPE=0
	      ) A LEFT JOIN JC_HOI_HL C  ON A.HOITEM_ID=C.HOITEM_ID AND A.XMLY=2
--		LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1
	WHERE A.INPATIENT_ID=B.INPATIENT_ID AND A.BABY_ID=B.BABY_ID --AND B.WARD_ID=@WARDID
              AND A.ORDER_BDATE BETWEEN @BEGINDATE AND @ENDDATE
	ORDER BY B.BED_NO,B.BABY_ID,B.NAME,A.MNGTYPE,A.ORDER_BDATE,A.ORDER_DOC,A.GROUP_ID,A.SERIAL_NO
   END
END
--未转抄
IF @SELKIND=1
BEGIN
   --所有
   IF @SELTYPE=0
   BEGIN
	SELECT A.STATUS_FLAG,A.ORDER_ID,A.GROUP_ID,A.NUM,case when  ISNUMERIC (LEFT(A.UNIT,1))>0 then '['+A.UNIT +']' else  A.UNIT end UNIT
	,DWLX,CASE U.ISP WHEN 0 THEN A.ORDER_USAGE ELSE '' END ORDER_USAGE,A.FREQUENCY,A.DROPSPER,A.DOSAGE,
		A.NTYPE,A.EXEC_DEPT,CONVERT(CHAR,DATEPART(DD,A.ORDER_BDATE)) DAY1,CONVERT(CHAR,DATEPART(MI,A.ORDER_BDATE)) SECOND1,
		B.INPATIENT_ID,B.BABY_ID,B.ISMY,CASE WHEN NTYPE<=3 AND NTYPE<>0 THEN A.ITEM_CODE ELSE CHAR(A.HOITEM_ID) END ITEM_CODE,XMLY,
		B.BED_NO 床号,B.INPATIENT_NO 住院号,B.NAME 姓名,
		CONVERT(CHAR,DATEPART(MM,A.ORDER_BDATE)) 日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_BDATE)) 时间,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 医生,
		CASE A.MNGTYPE WHEN 0 THEN '长嘱' ELSE '临嘱'END AS 类型,
		LTRIM(RTRIM(A.ORDER_CONTEXT))+CASE WHEN ISNULL(ORDER_SPEC,'')='' THEN '' ELSE '('+LTRIM(RTRIM(ORDER_SPEC))+')' END 医嘱内容,FIRST_TIMES 次,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER) 转抄护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER1) 核对护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER2) 查对护士,
		DBO.FUN_ZY_SEEKDEPTNAME(A.EXEC_DEPT) 执行科室,
		CASE WHEN C.TENDLEVEL IS NULL THEN 0 ELSE C.TENDLEVEL END 护理级别 ,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病重' or CHARINDEX('病重',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病重,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病危' or CHARINDEX('病危',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病危,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '%饮食'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '禁食%'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '普食%'
		THEN 1
		ELSE 0
		END 饮食,
		--Add By tany 2011-06-19
		CASE NTYPE WHEN 0 THEN '出院'
		WHEN 1 THEN '西药'
		WHEN 2 THEN '成药'
		WHEN 3 THEN '草药'
		WHEN 4 THEN '治疗'
		WHEN 5 THEN '医技'
		WHEN 6 THEN '手术'
		WHEN 7 THEN '说明'
		WHEN 8 THEN '护理'
		WHEN 9 THEN '其他'
		ELSE '' END	类别,
		B.ORDER_HL,B.ORDER_BZ,B.ORDER_BW,B.ORDER_YS,A.停 ,A.SERIAL_NO,A.MNGTYPE,
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,A.USAGE,PS_FLAG,PS_ORDERID,PS_USER,A.DEPT_ID,A.DEPT_BR,A.HOITEM_ID,A.ts,A.zsl,A.zsldw
	FROM (SELECT * FROM VI_ZY_VINPATIENT_BED WHERE WARD_ID=@WARDID AND INPATIENT_ID=@INPATIENT_ID AND BABY_ID=@BABY_ID) B
	     INNER JOIN
	     (SELECT STATUS_FLAG, ORDER_ID, GROUP_ID, NUM, UNIT,DWLX, ORDER_USAGE, FREQUENCY,
		DROPSPER, DOSAGE, case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE, NTYPE, CASE STATUS_FLAG WHEN 3 THEN 1 ELSE 0 END AS 停, INPATIENT_ID, BABY_ID,
		ITEM_CODE,XMLY, HOITEM_ID, LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT, EXEC_DEPT,
		SERIAL_NO,
		CASE STATUS_FLAG WHEN 3 THEN ORDER_EDATE ELSE ORDER_BDATE END ORDER_BDATE,
		CASE STATUS_FLAG WHEN 3 THEN ORDER_EDOC ELSE ORDER_DOC END ORDER_DOC,
		CASE STATUS_FLAG WHEN 3 THEN TERMINAL_TIMES ELSE FIRST_TIMES END FIRST_TIMES,
		CASE STATUS_FLAG WHEN 3 THEN ORDER_EUSER ELSE AUDITING_USER END AUDITING_USER,
		CASE STATUS_FLAG WHEN 3 THEN ORDER_EUSER1 ELSE AUDITING_USER1 END AUDITING_USER1,
		CASE STATUS_FLAG WHEN 3 THEN ORDER_EUSER2 ELSE AUDITING_USER2 END AUDITING_USER2,
		DEPT_ID, DEPT_BR,ORDER_USAGE USAGE,PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM ZY_ORDERRECORD A
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT = 0 AND STATUS_FLAG IN (1,3) AND MNGTYPE IN (0, 1, 5)
	     ) A
	     ON A.INPATIENT_ID=B.INPATIENT_ID AND A.BABY_ID=B.BABY_ID
	     LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') U ON A.ORDER_USAGE=U.USG
	     LEFT JOIN JC_HOI_HL C  ON A.HOITEM_ID=C.HOITEM_ID AND A.XMLY=2
--		LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1
	     ORDER BY B.BED_NO,B.BABY_ID,B.NAME,A.MNGTYPE,A.ORDER_BDATE,A.ORDER_DOC,A.GROUP_ID,A.SERIAL_NO 
   END
   --按时间段
   ELSE
   BEGIN
	SELECT A.STATUS_FLAG,A.ORDER_ID,A.GROUP_ID,A.NUM,
	case when  ISNUMERIC (LEFT(A.UNIT,1))>0 then '['+A.UNIT +']' else  A.UNIT end UNIT
	,DWLX,CASE U.ISP WHEN 0 THEN A.ORDER_USAGE ELSE '' END ORDER_USAGE,A.FREQUENCY,A.DROPSPER,A.DOSAGE,
		A.NTYPE,A.EXEC_DEPT,CONVERT(CHAR,DATEPART(DD,A.ORDER_BDATE)) DAY1,CONVERT(CHAR,DATEPART(MI,A.ORDER_BDATE)) SECOND1,
		B.INPATIENT_ID,B.BABY_ID,B.ISMY,CASE WHEN NTYPE<=3 AND NTYPE<>0 THEN A.ITEM_CODE ELSE CONVERT(CHAR,A.HOITEM_ID) END ITEM_CODE,XMLY,
		B.BED_NO 床号,B.INPATIENT_NO 住院号,B.NAME 姓名,
		CONVERT(CHAR,DATEPART(MM,A.ORDER_BDATE)) 日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_BDATE)) 时间,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 医生,
		CASE A.MNGTYPE WHEN 0 THEN '长嘱' ELSE '临嘱'END AS 类型,
		LTRIM(RTRIM(A.ORDER_CONTEXT))+CASE WHEN ISNULL(ORDER_SPEC,'')='' THEN '' ELSE '('+LTRIM(RTRIM(ORDER_SPEC))+')' END 医嘱内容,FIRST_TIMES 次,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER) 转抄护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER1) 核对护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER2) 查对护士,
		DBO.FUN_ZY_SEEKDEPTNAME(A.EXEC_DEPT) 执行科室,
		CASE WHEN C.TENDLEVEL IS NULL THEN 0 ELSE C.TENDLEVEL END 护理级别 ,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病重' or CHARINDEX('病重',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病重,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病危' or CHARINDEX('病危',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病危,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '%饮食'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '禁食%'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '普食%'
		THEN 1
		ELSE 0
		END 饮食,
		--Add By tany 2011-06-19
		CASE NTYPE WHEN 0 THEN '出院'
		WHEN 1 THEN '西药'
		WHEN 2 THEN '成药'
		WHEN 3 THEN '草药'
		WHEN 4 THEN '治疗'
		WHEN 5 THEN '医技'
		WHEN 6 THEN '手术'
		WHEN 7 THEN '说明'
		WHEN 8 THEN '护理'
		WHEN 9 THEN '其他'
		ELSE '' END	类别,
		B.ORDER_HL,B.ORDER_BZ,B.ORDER_BW,B.ORDER_YS,A.停 ,A.SERIAL_NO,A.MNGTYPE,
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,A.USAGE,PS_FLAG,PS_ORDERID,PS_USER,A.DEPT_ID,A.DEPT_BR,A.HOITEM_ID,A.ts,A.zsl,A.zsldw
	FROM (SELECT * FROM VI_ZY_VINPATIENT_BED WHERE WARD_ID=@WARDID AND INPATIENT_ID=@INPATIENT_ID AND BABY_ID=@BABY_ID) B
	     INNER JOIN
	     (SELECT STATUS_FLAG, ORDER_ID, GROUP_ID, NUM, UNIT,DWLX, ORDER_USAGE, FREQUENCY,
		DROPSPER, DOSAGE, case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE, NTYPE, CASE STATUS_FLAG WHEN 3 THEN 1 ELSE 0 END AS 停, INPATIENT_ID, BABY_ID,
		ITEM_CODE,XMLY, HOITEM_ID, LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT, EXEC_DEPT,
		SERIAL_NO,
		CASE STATUS_FLAG WHEN 3 THEN ORDER_EDATE ELSE ORDER_BDATE END ORDER_BDATE,
		CASE STATUS_FLAG WHEN 3 THEN ORDER_EDOC ELSE ORDER_DOC END ORDER_DOC,
		CASE STATUS_FLAG WHEN 3 THEN TERMINAL_TIMES ELSE FIRST_TIMES END FIRST_TIMES,
		CASE STATUS_FLAG WHEN 3 THEN ORDER_EUSER ELSE AUDITING_USER END AUDITING_USER,
		CASE STATUS_FLAG WHEN 3 THEN ORDER_EUSER1 ELSE AUDITING_USER1 END AUDITING_USER1,
		CASE STATUS_FLAG WHEN 3 THEN ORDER_EUSER2 ELSE AUDITING_USER2 END AUDITING_USER2,
		DEPT_ID, DEPT_BR,ORDER_USAGE USAGE,PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM ZY_ORDERRECORD A
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT = 0 AND STATUS_FLAG IN (1,3) AND MNGTYPE IN (0, 1, 5)
                    AND A.ORDER_BDATE BETWEEN @BEGINDATE AND @ENDDATE
	     ) A
	     ON A.INPATIENT_ID=B.INPATIENT_ID AND A.BABY_ID=B.BABY_ID
	     LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') U ON A.ORDER_USAGE=U.USG
	     LEFT JOIN JC_HOI_HL C  ON A.HOITEM_ID=C.HOITEM_ID AND A.XMLY=2
--		LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1
	     ORDER BY B.BED_NO,B.BABY_ID,B.NAME,A.MNGTYPE,A.ORDER_BDATE,A.ORDER_DOC,A.GROUP_ID,A.SERIAL_NO 
   END
END
--已转抄
IF @SELKIND=2
BEGIN
   --所有
   IF @SELTYPE=0
   BEGIN
	SELECT A.STATUS_FLAG,A.ORDER_ID,A.GROUP_ID,A.NUM,
	case when  ISNUMERIC (LEFT(A.UNIT,1))>0 then '['+A.UNIT +']' else  A.UNIT end UNIT
	,A.DWLX,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,A.DOSAGE,
		A.NTYPE,A.EXEC_DEPT,CONVERT(CHAR,DATEPART(DD,A.ORDER_BDATE)) DAY1,CONVERT(CHAR,DATEPART(MI,A.ORDER_BDATE)) SECOND1,
		B.INPATIENT_ID,B.BABY_ID,B.ISMY,CASE WHEN NTYPE<=3 AND NTYPE<>0 THEN A.ITEM_CODE ELSE CHAR(A.HOITEM_ID) END ITEM_CODE,A.XMLY,
		B.BED_NO 床号,B.INPATIENT_NO 住院号,B.NAME 姓名,
		CONVERT(CHAR,DATEPART(MM,A.ORDER_BDATE)) 日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_BDATE)) 时间,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 医生,
		CASE A.MNGTYPE WHEN 0 THEN '长嘱' ELSE '临嘱'END AS 类型,
		A.ORDER_CONTEXT+CASE WHEN ISNULL(ORDER_SPEC,'')='' THEN '' ELSE '('+LTRIM(RTRIM(ORDER_SPEC))+')' END 医嘱内容,FIRST_TIMES 次,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER) 转抄护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER1) 核对护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER2) 查对护士,
		DBO.FUN_ZY_SEEKDEPTNAME(A.EXEC_DEPT) 执行科室,
		CASE WHEN C.TENDLEVEL IS NULL THEN 0 ELSE C.TENDLEVEL END 护理级别 ,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病重' or CHARINDEX('病重',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病重,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病危' or CHARINDEX('病危',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病危,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '%饮食'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '禁食%'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '普食%'
		THEN 1
		ELSE 0
		END 饮食,
		--Add By tany 2011-06-19
		CASE NTYPE WHEN 0 THEN '出院'
		WHEN 1 THEN '西药'
		WHEN 2 THEN '成药'
		WHEN 3 THEN '草药'
		WHEN 4 THEN '治疗'
		WHEN 5 THEN '医技'
		WHEN 6 THEN '手术'
		WHEN 7 THEN '说明'
		WHEN 8 THEN '护理'
		WHEN 9 THEN '其他'
		ELSE '' END	类别,
		B.ORDER_HL,B.ORDER_BZ,B.ORDER_BW,B.ORDER_YS,A.停 ,A.SERIAL_NO ,A.MNGTYPE,
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,A.USAGE,PS_FLAG,PS_ORDERID,PS_USER,A.DEPT_ID,A.DEPT_BR,A.HOITEM_ID,A.ts,A.zsl,A.zsldw
	FROM (SELECT * FROM VI_ZY_VINPATIENT_BED WHERE WARD_ID=@WARDID AND INPATIENT_ID=@INPATIENT_ID AND BABY_ID=@BABY_ID) B,
	     (SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,DWLX,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,0 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,XMLY,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_BDATE,ORDER_DOC,FIRST_TIMES,		
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>1  AND MNGTYPE IN (0,1,5)
	      UNION ALL
	      SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,DWLX,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,1 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,XMLY,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_EDATE AS ORDER_BDATE,ORDER_EDOC AS ORDER_DOC, TERMINAL_TIMES AS FIRST_TIMES,
		ORDER_EUSER AS AUDITING_USER,ORDER_EUSER1 AS AUDITING_USER1,ORDER_EUSER2 AS AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,
		PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>3 AND STATUS_FLAG<=5 AND  MNGTYPE=0
	     ) A LEFT JOIN JC_HOI_HL C  ON A.HOITEM_ID=C.HOITEM_ID AND A.XMLY=2
--		LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1
	WHERE A.INPATIENT_ID=B.INPATIENT_ID AND A.BABY_ID=B.BABY_ID --AND B.WARD_ID=@WARDID
	      AND A.AUDITING_USER IS NOT NULL
	ORDER BY B.BED_NO,B.BABY_ID,B.NAME,A.MNGTYPE,A.ORDER_BDATE,A.ORDER_DOC,A.GROUP_ID,A.SERIAL_NO 
   END
   --按时间段
   ELSE
   BEGIN
	SELECT A.STATUS_FLAG,A.ORDER_ID,A.GROUP_ID,A.NUM,
	case when  ISNUMERIC (LEFT(A.UNIT,1))>0 then '['+A.UNIT +']' else  A.UNIT end UNIT,A.DWLX,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,A.DOSAGE,
		A.NTYPE,A.EXEC_DEPT,CONVERT(CHAR,DATEPART(DD,A.ORDER_BDATE)) DAY1,CONVERT(CHAR,DATEPART(MI,A.ORDER_BDATE)) SECOND1,
		B.INPATIENT_ID,B.BABY_ID,B.ISMY,CASE WHEN NTYPE<=3 AND NTYPE<>0 THEN A.ITEM_CODE ELSE CHAR(A.HOITEM_ID) END ITEM_CODE,A.XMLY,
		B.BED_NO 床号,B.INPATIENT_NO 住院号,B.NAME 姓名,
		CONVERT(CHAR,DATEPART(MM,A.ORDER_BDATE)) 日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_BDATE)) 时间,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 医生,
		CASE A.MNGTYPE WHEN 0 THEN '长嘱' ELSE '临嘱'END AS 类型,
		A.ORDER_CONTEXT+CASE WHEN ISNULL(ORDER_SPEC,'')='' THEN '' ELSE '('+LTRIM(RTRIM(ORDER_SPEC))+')' END 医嘱内容,FIRST_TIMES 次,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER) 转抄护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER1) 核对护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER2) 查对护士,
		DBO.FUN_ZY_SEEKDEPTNAME(A.EXEC_DEPT) 执行科室,
		CASE WHEN C.TENDLEVEL IS NULL THEN 0 ELSE C.TENDLEVEL END 护理级别 ,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病重' or CHARINDEX('病重',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病重,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病危' or CHARINDEX('病危',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病危,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '%饮食'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '禁食%'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '普食%'
		THEN 1
		ELSE 0
		END 饮食,
		--Add By tany 2011-06-19
		CASE NTYPE WHEN 0 THEN '出院'
		WHEN 1 THEN '西药'
		WHEN 2 THEN '成药'
		WHEN 3 THEN '草药'
		WHEN 4 THEN '治疗'
		WHEN 5 THEN '医技'
		WHEN 6 THEN '手术'
		WHEN 7 THEN '说明'
		WHEN 8 THEN '护理'
		WHEN 9 THEN '其他'
		ELSE '' END	类别,
		B.ORDER_HL,B.ORDER_BZ,B.ORDER_BW,B.ORDER_YS,A.停 ,A.SERIAL_NO ,A.MNGTYPE,
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,A.USAGE,PS_FLAG,PS_ORDERID,PS_USER,A.DEPT_ID,A.DEPT_BR,A.HOITEM_ID,A.ts,A.zsl,A.zsldw
	FROM (SELECT * FROM VI_ZY_VINPATIENT_BED WHERE WARD_ID=@WARDID AND INPATIENT_ID=@INPATIENT_ID AND BABY_ID=@BABY_ID) B,
	     (SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,DWLX,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,0 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,XMLY,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_BDATE,ORDER_DOC,FIRST_TIMES,		
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw,
		AUDITING_DATE,ORDER_EUDATE
	      FROM ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>1  AND MNGTYPE IN (0,1,5)
	      UNION ALL
	      SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,DWLX,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,1 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,XMLY,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_EDATE AS ORDER_BDATE,ORDER_EDOC AS ORDER_DOC, TERMINAL_TIMES AS FIRST_TIMES,
		ORDER_EUSER AS AUDITING_USER,ORDER_EUSER1 AS AUDITING_USER1,ORDER_EUSER2 AS AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,
		PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw,
		AUDITING_DATE,ORDER_EUDATE
	      FROM ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>3 AND STATUS_FLAG<=5 AND  MNGTYPE=0
	     ) A LEFT JOIN JC_HOI_HL C  ON A.HOITEM_ID=C.HOITEM_ID AND A.XMLY=2
--		LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1
	WHERE A.INPATIENT_ID=B.INPATIENT_ID AND A.BABY_ID=B.BABY_ID --AND B.WARD_ID=@WARDID
	      AND A.AUDITING_USER IS NOT NULL
              AND ((A.ORDER_EUDATE BETWEEN @BEGINDATE AND @ENDDATE) 
					OR (A.AUDITING_DATE BETWEEN @BEGINDATE AND @ENDDATE)) --Modify By Tany 2015-02-02 已转抄的按转抄时间查 Modify By Tany 2015-04-23 还要包括停医嘱转抄时间
	ORDER BY B.BED_NO,B.BABY_ID,B.NAME,A.MNGTYPE,A.ORDER_BDATE,A.ORDER_DOC,A.GROUP_ID,A.SERIAL_NO 
   END
END
--未核对
IF @SELKIND=3
BEGIN
   --所有
   IF @SELTYPE=0
   BEGIN 
	SELECT A.STATUS_FLAG,A.ORDER_ID,A.GROUP_ID,A.NUM,
	case when  ISNUMERIC (LEFT(A.UNIT,1))>0 then '['+A.UNIT +']' else  A.UNIT end UNIT
	,A.DWLX,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,A.DOSAGE,
		A.NTYPE,A.EXEC_DEPT,CONVERT(CHAR,DATEPART(DD,A.ORDER_BDATE)) DAY1,CONVERT(CHAR,DATEPART(MI,A.ORDER_BDATE)) SECOND1,
		B.INPATIENT_ID,B.BABY_ID,B.ISMY,CASE WHEN NTYPE<=3 AND NTYPE<>0 THEN A.ITEM_CODE ELSE CONVERT(CHAR,A.HOITEM_ID) END ITEM_CODE,A.XMLY,
		B.BED_NO 床号,B.INPATIENT_NO 住院号,B.NAME 姓名,
		CONVERT(CHAR,DATEPART(MM,A.ORDER_BDATE)) 日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_BDATE)) 时间,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 医生,
		CASE A.MNGTYPE WHEN 0 THEN '长嘱' ELSE '临嘱'END AS 类型,
		LTRIM(RTRIM(A.ORDER_CONTEXT))+CASE WHEN ISNULL(ORDER_SPEC,'')='' THEN '' ELSE '('+LTRIM(RTRIM(ORDER_SPEC))+')' END 医嘱内容,FIRST_TIMES 次,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER) 转抄护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER1) 核对护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER2) 查对护士,
		DBO.FUN_ZY_SEEKDEPTNAME(A.EXEC_DEPT) 执行科室,
		CASE WHEN C.TENDLEVEL IS NULL THEN 0 ELSE C.TENDLEVEL END 护理级别 ,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病重' or CHARINDEX('病重',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病重,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病危' or CHARINDEX('病危',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病危,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '%饮食'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '禁食%'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '普食%'
		THEN 1
		ELSE 0
		END 饮食,
		--Add By tany 2011-06-19
		CASE NTYPE WHEN 0 THEN '出院'
		WHEN 1 THEN '西药'
		WHEN 2 THEN '成药'
		WHEN 3 THEN '草药'
		WHEN 4 THEN '治疗'
		WHEN 5 THEN '医技'
		WHEN 6 THEN '手术'
		WHEN 7 THEN '说明'
		WHEN 8 THEN '护理'
		WHEN 9 THEN '其他'
		ELSE '' END	类别,
		B.ORDER_HL,B.ORDER_BZ,B.ORDER_BW,B.ORDER_YS,A.停 ,A.SERIAL_NO,A.MNGTYPE,
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,A.USAGE,PS_FLAG,PS_ORDERID,PS_USER,A.DEPT_ID,A.DEPT_BR,A.HOITEM_ID,A.ts,A.zsl,A.zsldw
	FROM (SELECT * FROM VI_ZY_VINPATIENT_BED WHERE WARD_ID=@WARDID AND INPATIENT_ID=@INPATIENT_ID AND BABY_ID=@BABY_ID) B,
	     (SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,DWLX,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,0 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,XMLY,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_BDATE,ORDER_DOC,FIRST_TIMES,		
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>1 AND STATUS_FLAG<=5 AND MNGTYPE IN (0,1,5)
	      UNION ALL
	      SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,DWLX,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,1 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,XMLY,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_EDATE AS ORDER_BDATE,ORDER_EDOC AS ORDER_DOC, TERMINAL_TIMES AS FIRST_TIMES,
		ORDER_EUSER AS AUDITING_USER,ORDER_EUSER1 AS AUDITING_USER1,ORDER_EUSER2 AS AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,
		PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>3 AND  MNGTYPE=0
	     ) A LEFT JOIN JC_HOI_HL C  ON A.HOITEM_ID=C.HOITEM_ID AND A.XMLY=2
--		LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1
	WHERE A.INPATIENT_ID=B.INPATIENT_ID AND A.BABY_ID=B.BABY_ID --AND B.WARD_ID=@WARDID
	      AND A.AUDITING_USER1 IS NULL
	ORDER BY B.BED_NO,B.BABY_ID,B.NAME,A.MNGTYPE,A.ORDER_BDATE,A.ORDER_DOC,A.GROUP_ID,A.SERIAL_NO
   END
   --按时间段
   ELSE
   BEGIN
	SELECT A.STATUS_FLAG,A.ORDER_ID,A.GROUP_ID,A.NUM,
	case when  ISNUMERIC (LEFT(A.UNIT,1))>0 then '['+A.UNIT +']' else  A.UNIT end UNIT,
	A.DWLX,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,A.DOSAGE,
		A.NTYPE,A.EXEC_DEPT,CONVERT(CHAR,DATEPART(DD,A.ORDER_BDATE)) DAY1,CONVERT(CHAR,DATEPART(MI,A.ORDER_BDATE)) SECOND1,
		B.INPATIENT_ID,B.BABY_ID,B.ISMY,CASE WHEN NTYPE<=3 AND NTYPE<>0 THEN A.ITEM_CODE ELSE CHAR(A.HOITEM_ID) END ITEM_CODE,A.XMLY,
		B.BED_NO 床号,B.INPATIENT_NO 住院号,B.NAME 姓名,
		CONVERT(CHAR,DATEPART(MM,A.ORDER_BDATE)) 日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_BDATE)) 时间,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 医生,
		CASE A.MNGTYPE WHEN 0 THEN '长嘱' ELSE '临嘱'END AS 类型,
		LTRIM(RTRIM(A.ORDER_CONTEXT))+CASE WHEN ISNULL(ORDER_SPEC,'')='' THEN '' ELSE '('+LTRIM(RTRIM(ORDER_SPEC))+')' END 医嘱内容,FIRST_TIMES 次,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER) 转抄护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER1) 核对护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER2) 查对护士,
		DBO.FUN_ZY_SEEKDEPTNAME(A.EXEC_DEPT) 执行科室,
		CASE WHEN C.TENDLEVEL IS NULL THEN 0 ELSE C.TENDLEVEL END 护理级别 ,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病重' or CHARINDEX('病重',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病重,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病危' or CHARINDEX('病危',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病危,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '%饮食'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '禁食%'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '普食%'
		THEN 1
		ELSE 0
		END 饮食,
		--Add By tany 2011-06-19
		CASE NTYPE WHEN 0 THEN '出院'
		WHEN 1 THEN '西药'
		WHEN 2 THEN '成药'
		WHEN 3 THEN '草药'
		WHEN 4 THEN '治疗'
		WHEN 5 THEN '医技'
		WHEN 6 THEN '手术'
		WHEN 7 THEN '说明'
		WHEN 8 THEN '护理'
		WHEN 9 THEN '其他'
		ELSE '' END	类别,
		B.ORDER_HL,B.ORDER_BZ,B.ORDER_BW,B.ORDER_YS,A.停 ,A.SERIAL_NO,A.MNGTYPE,
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,A.USAGE,PS_FLAG,PS_ORDERID,PS_USER,A.DEPT_ID,A.DEPT_BR,A.HOITEM_ID,A.ts,A.zsl,A.zsldw
	FROM (SELECT * FROM VI_ZY_VINPATIENT_BED WHERE WARD_ID=@WARDID AND INPATIENT_ID=@INPATIENT_ID AND BABY_ID=@BABY_ID) B,
	     (SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,DWLX,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,0 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,XMLY,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_BDATE,ORDER_DOC,FIRST_TIMES,		
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>1 AND STATUS_FLAG<=5 AND MNGTYPE IN (0,1,5)
	      UNION ALL
	      SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,DWLX,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,1 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,XMLY,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_EDATE AS ORDER_BDATE,ORDER_EDOC AS ORDER_DOC, TERMINAL_TIMES AS FIRST_TIMES,
		ORDER_EUSER AS AUDITING_USER,ORDER_EUSER1 AS AUDITING_USER1,ORDER_EUSER2 AS AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,
		PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>3 AND  MNGTYPE=0
	     ) A LEFT JOIN JC_HOI_HL C  ON A.HOITEM_ID=C.HOITEM_ID AND A.XMLY=2
--		LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1
	WHERE A.INPATIENT_ID=B.INPATIENT_ID AND A.BABY_ID=B.BABY_ID --AND B.WARD_ID=@WARDID
	      AND A.AUDITING_USER1 IS NULL
              AND A.ORDER_BDATE BETWEEN @BEGINDATE AND @ENDDATE
	ORDER BY B.BED_NO,B.BABY_ID,B.NAME,A.MNGTYPE,A.ORDER_BDATE,A.ORDER_DOC,A.GROUP_ID,A.SERIAL_NO
   END
END
--已核对
IF @SELKIND=4
BEGIN
   --所有
   IF @SELTYPE=0
   BEGIN 
	SELECT A.STATUS_FLAG,A.ORDER_ID,A.GROUP_ID,A.NUM,
	case when  ISNUMERIC (LEFT(A.UNIT,1))>0 then '['+A.UNIT +']' else  A.UNIT end UNIT,A.DWLX,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,A.DOSAGE,
		A.NTYPE,A.EXEC_DEPT,CONVERT(CHAR,DATEPART(DD,A.ORDER_BDATE)) DAY1,CONVERT(CHAR,DATEPART(MI,A.ORDER_BDATE)) SECOND1,
		B.INPATIENT_ID,B.BABY_ID,B.ISMY,CASE WHEN NTYPE<=3 AND NTYPE<>0 THEN A.ITEM_CODE ELSE CONVERT(CHAR,A.HOITEM_ID) END ITEM_CODE,A.XMLY,
		B.BED_NO 床号,B.INPATIENT_NO 住院号,B.NAME 姓名,
		CONVERT(CHAR,DATEPART(MM,A.ORDER_BDATE)) 日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_BDATE)) 时间,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 医生,
		CASE A.MNGTYPE WHEN 0 THEN '长嘱' ELSE '临嘱'END AS 类型,
		LTRIM(RTRIM(A.ORDER_CONTEXT))+CASE WHEN ISNULL(ORDER_SPEC,'')='' THEN '' ELSE '('+LTRIM(RTRIM(ORDER_SPEC))+')' END 医嘱内容,FIRST_TIMES 次,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER) 转抄护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER1) 核对护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER2) 查对护士,
		DBO.FUN_ZY_SEEKDEPTNAME(A.EXEC_DEPT) 执行科室,
		CASE WHEN C.TENDLEVEL IS NULL THEN 0 ELSE C.TENDLEVEL END 护理级别 ,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病重' or CHARINDEX('病重',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病重,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病危' or CHARINDEX('病危',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病危,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '%饮食'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '禁食%'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '普食%'
		THEN 1
		ELSE 0
		END 饮食,
		--Add By tany 2011-06-19
		CASE NTYPE WHEN 0 THEN '出院'
		WHEN 1 THEN '西药'
		WHEN 2 THEN '成药'
		WHEN 3 THEN '草药'
		WHEN 4 THEN '治疗'
		WHEN 5 THEN '医技'
		WHEN 6 THEN '手术'
		WHEN 7 THEN '说明'
		WHEN 8 THEN '护理'
		WHEN 9 THEN '其他'
		ELSE '' END	类别,
		B.ORDER_HL,B.ORDER_BZ,B.ORDER_BW,B.ORDER_YS,A.停 ,A.SERIAL_NO,A.MNGTYPE,
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,A.USAGE,PS_FLAG,PS_ORDERID,PS_USER,A.DEPT_ID,A.DEPT_BR,A.HOITEM_ID,A.ts,A.zsl,A.zsldw
	FROM (SELECT * FROM VI_ZY_VINPATIENT_BED WHERE WARD_ID=@WARDID AND INPATIENT_ID=@INPATIENT_ID AND BABY_ID=@BABY_ID) B,
	     (SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,0 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_BDATE,ORDER_DOC,FIRST_TIMES,		
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,
		DWLX,XMLY,PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>1 AND STATUS_FLAG<=5 AND MNGTYPE IN (0,1,5)
	      UNION ALL
	      SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,1 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_EDATE AS ORDER_BDATE,ORDER_EDOC AS ORDER_DOC, TERMINAL_TIMES AS FIRST_TIMES,
		ORDER_EUSER AS AUDITING_USER,ORDER_EUSER1 AS AUDITING_USER1,ORDER_EUSER2 AS AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,
		DWLX,XMLY,PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>3 AND STATUS_FLAG<=5 AND  MNGTYPE=0
	     ) A LEFT JOIN JC_HOI_HL C  ON A.HOITEM_ID=C.HOITEM_ID AND A.XMLY=2
--		LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1
	WHERE A.INPATIENT_ID=B.INPATIENT_ID AND A.BABY_ID=B.BABY_ID --AND B.WARD_ID=@WARDID
	      AND A.AUDITING_USER1 IS NOT NULL
	ORDER BY B.BED_NO,B.BABY_ID,B.NAME,A.MNGTYPE,A.ORDER_BDATE,A.ORDER_DOC,A.GROUP_ID,A.SERIAL_NO
   END
   --按时间段
   ELSE
   BEGIN
	SELECT A.STATUS_FLAG,A.ORDER_ID,A.GROUP_ID,A.NUM,case when  ISNUMERIC (LEFT(A.UNIT,1))>0 then '['+A.UNIT +']' else  A.UNIT end UNIT
	,A.DWLX,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,A.DOSAGE,
		A.NTYPE,A.EXEC_DEPT,CONVERT(CHAR,DATEPART(DD,A.ORDER_BDATE)) DAY1,CONVERT(CHAR,DATEPART(MI,A.ORDER_BDATE)) SECOND1,
		B.INPATIENT_ID,B.BABY_ID,B.ISMY,CASE WHEN NTYPE<=3 AND NTYPE<>0 THEN A.ITEM_CODE ELSE CONVERT(CHAR,A.HOITEM_ID) END ITEM_CODE,A.XMLY,
		B.BED_NO 床号,B.INPATIENT_NO 住院号,B.NAME 姓名,
		CONVERT(CHAR,DATEPART(MM,A.ORDER_BDATE)) 日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_BDATE)) 时间,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 医生,
		CASE A.MNGTYPE WHEN 0 THEN '长嘱' ELSE '临嘱'END AS 类型,
		LTRIM(RTRIM(A.ORDER_CONTEXT))+CASE WHEN ISNULL(ORDER_SPEC,'')='' THEN '' ELSE '('+LTRIM(RTRIM(ORDER_SPEC))+')' END 医嘱内容,FIRST_TIMES 次,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER) 转抄护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER1) 核对护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER2) 查对护士,
		DBO.FUN_ZY_SEEKDEPTNAME(A.EXEC_DEPT) 执行科室,
		CASE WHEN C.TENDLEVEL IS NULL THEN 0 ELSE C.TENDLEVEL END 护理级别 ,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病重' or CHARINDEX('病重',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病重,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病危' or CHARINDEX('病危',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病危,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '%饮食'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '禁食%'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '普食%'
		THEN 1
		ELSE 0
		END 饮食,
		--Add By tany 2011-06-19
		CASE NTYPE WHEN 0 THEN '出院'
		WHEN 1 THEN '西药'
		WHEN 2 THEN '成药'
		WHEN 3 THEN '草药'
		WHEN 4 THEN '治疗'
		WHEN 5 THEN '医技'
		WHEN 6 THEN '手术'
		WHEN 7 THEN '说明'
		WHEN 8 THEN '护理'
		WHEN 9 THEN '其他'
		ELSE '' END	类别,
		B.ORDER_HL,B.ORDER_BZ,B.ORDER_BW,B.ORDER_YS,A.停 ,A.SERIAL_NO,A.MNGTYPE,
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,A.USAGE,PS_FLAG,PS_ORDERID,PS_USER,A.DEPT_ID,A.DEPT_BR,A.HOITEM_ID,A.ts,A.zsl,A.zsldw
	FROM (SELECT * FROM VI_ZY_VINPATIENT_BED WHERE WARD_ID=@WARDID AND INPATIENT_ID=@INPATIENT_ID AND BABY_ID=@BABY_ID) B,
	     (SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,0 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_BDATE,ORDER_DOC,FIRST_TIMES,		
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,
		DWLX,XMLY,PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>1 AND STATUS_FLAG<=5 AND MNGTYPE IN (0,1,5)
	      UNION ALL
	      SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,1 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_EDATE AS ORDER_BDATE,ORDER_EDOC AS ORDER_DOC, TERMINAL_TIMES AS FIRST_TIMES,
		ORDER_EUSER AS AUDITING_USER,ORDER_EUSER1 AS AUDITING_USER1,ORDER_EUSER2 AS AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,
		DWLX,XMLY,PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>3 AND STATUS_FLAG<=5 AND  MNGTYPE=0
	     ) A LEFT JOIN JC_HOI_HL C  ON A.HOITEM_ID=C.HOITEM_ID AND A.XMLY=2
--		LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1
	WHERE A.INPATIENT_ID=B.INPATIENT_ID AND A.BABY_ID=B.BABY_ID --AND B.WARD_ID=@WARDID
	      AND A.AUDITING_USER1 IS NOT NULL
              AND A.ORDER_BDATE BETWEEN @BEGINDATE AND @ENDDATE
	ORDER BY B.BED_NO,B.BABY_ID,B.NAME,A.MNGTYPE,A.ORDER_BDATE,A.ORDER_DOC,A.GROUP_ID,A.SERIAL_NO
   END
END
--未查对
IF @SELKIND=5
BEGIN
   --所有
   IF @SELTYPE=0
   BEGIN 
	SELECT A.STATUS_FLAG,A.ORDER_ID,A.GROUP_ID,A.NUM,
	case when  ISNUMERIC (LEFT(A.UNIT,1))>0 then '['+A.UNIT +']' else  A.UNIT end UNIT,A.DWLX,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,A.DOSAGE,
		A.NTYPE,A.EXEC_DEPT,CONVERT(CHAR,DATEPART(DD,A.ORDER_BDATE)) DAY1,CONVERT(CHAR,DATEPART(MI,A.ORDER_BDATE)) SECOND1,
		B.INPATIENT_ID,B.BABY_ID,B.ISMY,CASE WHEN NTYPE<=3 AND NTYPE<>0 THEN A.ITEM_CODE ELSE CONVERT(CHAR,A.HOITEM_ID) END ITEM_CODE,A.XMLY,
		B.BED_NO 床号,B.INPATIENT_NO 住院号,B.NAME 姓名,
		CONVERT(CHAR,DATEPART(MM,A.ORDER_BDATE)) 日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_BDATE)) 时间,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 医生,
		CASE A.MNGTYPE WHEN 0 THEN '长嘱' ELSE '临嘱'END AS 类型,
		LTRIM(RTRIM(A.ORDER_CONTEXT))+CASE WHEN ISNULL(ORDER_SPEC,'')='' THEN '' ELSE '('+LTRIM(RTRIM(ORDER_SPEC))+')' END 医嘱内容,FIRST_TIMES 次,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER) 转抄护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER1) 核对护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER2) 查对护士,
		DBO.FUN_ZY_SEEKDEPTNAME(A.EXEC_DEPT) 执行科室,
		CASE WHEN C.TENDLEVEL IS NULL THEN 0 ELSE C.TENDLEVEL END 护理级别 ,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病重' or CHARINDEX('病重',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病重,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病危' or CHARINDEX('病危',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病危,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '%饮食'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '禁食%'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '普食%'
		THEN 1
		ELSE 0
		END 饮食,
		--Add By tany 2011-06-19
		CASE NTYPE WHEN 0 THEN '出院'
		WHEN 1 THEN '西药'
		WHEN 2 THEN '成药'
		WHEN 3 THEN '草药'
		WHEN 4 THEN '治疗'
		WHEN 5 THEN '医技'
		WHEN 6 THEN '手术'
		WHEN 7 THEN '说明'
		WHEN 8 THEN '护理'
		WHEN 9 THEN '其他'
		ELSE '' END	类别,
		B.ORDER_HL,B.ORDER_BZ,B.ORDER_BW,B.ORDER_YS,A.停 ,A.SERIAL_NO,A.MNGTYPE,
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,A.USAGE,PS_FLAG,PS_ORDERID,PS_USER,A.DEPT_ID,A.DEPT_BR,A.HOITEM_ID,A.ts,A.zsl,A.zsldw
	FROM (SELECT * FROM VI_ZY_VINPATIENT_BED WHERE WARD_ID=@WARDID AND INPATIENT_ID=@INPATIENT_ID AND BABY_ID=@BABY_ID) B,
	     (SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,0 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_BDATE,ORDER_DOC,FIRST_TIMES,		
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,
		DWLX,XMLY,PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>1 AND STATUS_FLAG<=5 AND MNGTYPE IN (0,1,5)
	      UNION ALL
	      SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,1 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_EDATE AS ORDER_BDATE,ORDER_EDOC AS ORDER_DOC, TERMINAL_TIMES AS FIRST_TIMES,
		ORDER_EUSER AS AUDITING_USER,ORDER_EUSER1 AS AUDITING_USER1,ORDER_EUSER2 AS AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,
		DWLX,XMLY,PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>3 AND STATUS_FLAG<=5 AND MNGTYPE=0
	     ) A LEFT JOIN JC_HOI_HL C  ON A.HOITEM_ID=C.HOITEM_ID AND A.XMLY=2
--		LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1
	WHERE A.INPATIENT_ID=B.INPATIENT_ID AND A.BABY_ID=B.BABY_ID --AND B.WARD_ID=@WARDID
	      AND A.AUDITING_USER2 IS NULL
	ORDER BY B.BED_NO,B.BABY_ID,B.NAME,A.MNGTYPE,A.ORDER_BDATE,A.ORDER_DOC,A.GROUP_ID,A.SERIAL_NO
   END
   --按时间段
   ELSE
   BEGIN
	SELECT A.STATUS_FLAG,A.ORDER_ID,A.GROUP_ID,A.NUM,
	case when  ISNUMERIC (LEFT(A.UNIT,1))>0 then '['+A.UNIT +']' else  A.UNIT end UNIT
	,A.DWLX,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,A.DOSAGE,
		A.NTYPE,A.EXEC_DEPT,CONVERT(CHAR,DATEPART(DD,A.ORDER_BDATE)) DAY1,CONVERT(CHAR,DATEPART(MI,A.ORDER_BDATE)) SECOND1,
		B.INPATIENT_ID,B.BABY_ID,B.ISMY,CASE WHEN NTYPE<=3 AND NTYPE<>0 THEN A.ITEM_CODE ELSE CONVERT(CHAR,A.HOITEM_ID) END ITEM_CODE,A.XMLY,
		B.BED_NO 床号,B.INPATIENT_NO 住院号,B.NAME 姓名,
		CONVERT(CHAR,DATEPART(MM,A.ORDER_BDATE)) 日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_BDATE)) 时间,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 医生,
		CASE A.MNGTYPE WHEN 0 THEN '长嘱' ELSE '临嘱'END AS 类型,
		LTRIM(RTRIM(A.ORDER_CONTEXT))+CASE WHEN ISNULL(ORDER_SPEC,'')='' THEN '' ELSE '('+LTRIM(RTRIM(ORDER_SPEC))+')' END 医嘱内容,FIRST_TIMES 次,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER) 转抄护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER1) 核对护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER2) 查对护士,
		DBO.FUN_ZY_SEEKDEPTNAME(A.EXEC_DEPT) 执行科室,
		CASE WHEN C.TENDLEVEL IS NULL THEN 0 ELSE C.TENDLEVEL END 护理级别 ,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病重' or CHARINDEX('病重',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病重,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病危' or CHARINDEX('病危',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病危,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '%饮食'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '禁食%'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '普食%'
		THEN 1
		ELSE 0
		END 饮食,
		--Add By tany 2011-06-19
		CASE NTYPE WHEN 0 THEN '出院'
		WHEN 1 THEN '西药'
		WHEN 2 THEN '成药'
		WHEN 3 THEN '草药'
		WHEN 4 THEN '治疗'
		WHEN 5 THEN '医技'
		WHEN 6 THEN '手术'
		WHEN 7 THEN '说明'
		WHEN 8 THEN '护理'
		WHEN 9 THEN '其他'
		ELSE '' END	类别,
		B.ORDER_HL,B.ORDER_BZ,B.ORDER_BW,B.ORDER_YS,A.停 ,A.SERIAL_NO,A.MNGTYPE,
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,A.USAGE,PS_FLAG,PS_ORDERID,PS_USER,A.DEPT_ID,A.DEPT_BR,A.HOITEM_ID,A.ts,A.zsl,A.zsldw
	FROM (SELECT * FROM VI_ZY_VINPATIENT_BED WHERE WARD_ID=@WARDID AND INPATIENT_ID=@INPATIENT_ID AND BABY_ID=@BABY_ID) B,
	     (SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,0 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_BDATE,ORDER_DOC,FIRST_TIMES,		
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,
		DWLX,XMLY,PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>1 AND STATUS_FLAG<=5 AND MNGTYPE IN (0,1,5)
	      UNION ALL
	      SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,1 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_EDATE AS ORDER_BDATE,ORDER_EDOC AS ORDER_DOC, TERMINAL_TIMES AS FIRST_TIMES,
		ORDER_EUSER AS AUDITING_USER,ORDER_EUSER1 AS AUDITING_USER1,ORDER_EUSER2 AS AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,
		DWLX,XMLY,PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>3 AND STATUS_FLAG<=5 AND MNGTYPE=0
	     ) A LEFT JOIN JC_HOI_HL C  ON A.HOITEM_ID=C.HOITEM_ID AND A.XMLY=2
--		LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1
	WHERE A.INPATIENT_ID=B.INPATIENT_ID AND A.BABY_ID=B.BABY_ID --AND B.WARD_ID=@WARDID
	      AND A.AUDITING_USER2 IS NULL
              AND A.ORDER_BDATE BETWEEN @BEGINDATE AND @ENDDATE
	ORDER BY B.BED_NO,B.BABY_ID,B.NAME,A.MNGTYPE,A.ORDER_BDATE,A.ORDER_DOC,A.GROUP_ID,A.SERIAL_NO
   END
END
--已查对
IF @SELKIND=6
BEGIN
   --所有
   IF @SELTYPE=0
   BEGIN 
	SELECT A.STATUS_FLAG,A.ORDER_ID,A.GROUP_ID,A.NUM,
	case when  ISNUMERIC (LEFT(A.UNIT,1))>0 then '['+A.UNIT +']' else  A.UNIT end UNIT
	,A.DWLX,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,A.DOSAGE,
		A.NTYPE,A.EXEC_DEPT,CONVERT(CHAR,DATEPART(DD,A.ORDER_BDATE)) DAY1,CONVERT(CHAR,DATEPART(MI,A.ORDER_BDATE)) SECOND1,
		B.INPATIENT_ID,B.BABY_ID,B.ISMY,CASE WHEN NTYPE<=3 AND NTYPE<>0 THEN A.ITEM_CODE ELSE CONVERT(CHAR,A.HOITEM_ID) END ITEM_CODE,A.XMLY,
		B.BED_NO 床号,B.INPATIENT_NO 住院号,B.NAME 姓名,
		CONVERT(CHAR,DATEPART(MM,A.ORDER_BDATE)) 日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_BDATE)) 时间,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 医生,
		CASE A.MNGTYPE WHEN 0 THEN '长嘱' ELSE '临嘱'END AS 类型,
		LTRIM(RTRIM(A.ORDER_CONTEXT))+CASE WHEN ISNULL(ORDER_SPEC,'')='' THEN '' ELSE '('+LTRIM(RTRIM(ORDER_SPEC))+')' END 医嘱内容,FIRST_TIMES 次,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER) 转抄护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER1) 核对护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER2) 查对护士,
		DBO.FUN_ZY_SEEKDEPTNAME(A.EXEC_DEPT) 执行科室,
		CASE WHEN C.TENDLEVEL IS NULL THEN 0 ELSE C.TENDLEVEL END 护理级别 ,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病重' or CHARINDEX('病重',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病重,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病危' or CHARINDEX('病危',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病危,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '%饮食'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '禁食%'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '普食%'
		THEN 1
		ELSE 0
		END 饮食,
		--Add By tany 2011-06-19
		CASE NTYPE WHEN 0 THEN '出院'
		WHEN 1 THEN '西药'
		WHEN 2 THEN '成药'
		WHEN 3 THEN '草药'
		WHEN 4 THEN '治疗'
		WHEN 5 THEN '医技'
		WHEN 6 THEN '手术'
		WHEN 7 THEN '说明'
		WHEN 8 THEN '护理'
		WHEN 9 THEN '其他'
		ELSE '' END	类别,
		B.ORDER_HL,B.ORDER_BZ,B.ORDER_BW,B.ORDER_YS,A.停 ,A.SERIAL_NO ,A.MNGTYPE,
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,A.USAGE,PS_FLAG,PS_ORDERID,PS_USER,A.DEPT_ID,A.DEPT_BR,A.HOITEM_ID,A.ts,A.zsl,A.zsldw
	FROM (SELECT * FROM VI_ZY_VINPATIENT_BED WHERE WARD_ID=@WARDID AND INPATIENT_ID=@INPATIENT_ID AND BABY_ID=@BABY_ID) B,
	     (SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,0 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_BDATE,ORDER_DOC,FIRST_TIMES,		
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,
		DWLX,XMLY,PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>1 AND STATUS_FLAG<=5 AND MNGTYPE IN (0,1,5)
	      UNION ALL
	      SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,1 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_EDATE AS ORDER_BDATE,ORDER_EDOC AS ORDER_DOC, TERMINAL_TIMES AS FIRST_TIMES,
		ORDER_EUSER AS AUDITING_USER,ORDER_EUSER1 AS AUDITING_USER1,ORDER_EUSER2 AS AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,
		DWLX,XMLY,PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>3 AND STATUS_FLAG<=5 AND  MNGTYPE=0
	     ) A LEFT JOIN JC_HOI_HL C  ON A.HOITEM_ID=C.HOITEM_ID AND A.XMLY=2
--		LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1
	WHERE A.INPATIENT_ID=B.INPATIENT_ID AND A.BABY_ID=B.BABY_ID --AND B.WARD_ID=@WARDID
	      AND A.AUDITING_USER2 IS NOT NULL
	ORDER BY B.BED_NO,B.BABY_ID,B.NAME,A.MNGTYPE,A.ORDER_BDATE,A.ORDER_DOC,A.GROUP_ID,A.SERIAL_NO
   END
   --按时间段
   ELSE
   BEGIN
	SELECT A.STATUS_FLAG,A.ORDER_ID,A.GROUP_ID,A.NUM,
	case when  ISNUMERIC (LEFT(A.UNIT,1))>0 then '['+A.UNIT +']' else  A.UNIT end UNIT
	,A.DWLX,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,A.DOSAGE,
		A.NTYPE,A.EXEC_DEPT,CONVERT(CHAR,DATEPART(DD,A.ORDER_BDATE)) DAY1,CONVERT(CHAR,DATEPART(MI,A.ORDER_BDATE)) SECOND1,
		B.INPATIENT_ID,B.BABY_ID,B.ISMY,CASE WHEN NTYPE<=3 AND NTYPE<>0 THEN A.ITEM_CODE ELSE CONVERT(CHAR,A.HOITEM_ID) END ITEM_CODE,A.XMLY,
		B.BED_NO 床号,B.INPATIENT_NO 住院号,B.NAME 姓名,
		CONVERT(CHAR,DATEPART(MM,A.ORDER_BDATE)) 日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_BDATE)) 时间,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 医生,
		CASE A.MNGTYPE WHEN 0 THEN '长嘱' ELSE '临嘱'END AS 类型,
		LTRIM(RTRIM(A.ORDER_CONTEXT))+CASE WHEN ISNULL(ORDER_SPEC,'')='' THEN '' ELSE '('+LTRIM(RTRIM(ORDER_SPEC))+')' END 医嘱内容,FIRST_TIMES 次,
		DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER) 转抄护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER1) 核对护士,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER2) 查对护士,
		DBO.FUN_ZY_SEEKDEPTNAME(A.EXEC_DEPT) 执行科室,
		CASE WHEN C.TENDLEVEL IS NULL THEN 0 ELSE C.TENDLEVEL END 护理级别 ,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病重' OR   CHARINDEX('病重',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病重,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT))='病危' OR   CHARINDEX('病危',ORDER_CONTEXT)>0 THEN 1 ELSE 0 END 病危,
		CASE WHEN LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '%饮食'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '禁食%'
		OR LTRIM(RTRIM(ORDER_CONTEXT)) LIKE '普食%'
		THEN 1
		ELSE 0
		END 饮食,
		--Add By tany 2011-06-19
		CASE NTYPE WHEN 0 THEN '出院'
		WHEN 1 THEN '西药'
		WHEN 2 THEN '成药'
		WHEN 3 THEN '草药'
		WHEN 4 THEN '治疗'
		WHEN 5 THEN '医技'
		WHEN 6 THEN '手术'
		WHEN 7 THEN '说明'
		WHEN 8 THEN '护理'
		WHEN 9 THEN '其他'
		ELSE '' END	类别,
		B.ORDER_HL,B.ORDER_BZ,B.ORDER_BW,B.ORDER_YS,A.停 ,A.SERIAL_NO ,A.MNGTYPE,
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,A.USAGE,PS_FLAG,PS_ORDERID,PS_USER,A.DEPT_ID,A.DEPT_BR,A.HOITEM_ID,A.ts,A.zsl,A.zsldw
	FROM (SELECT * FROM VI_ZY_VINPATIENT_BED WHERE WARD_ID=@WARDID AND INPATIENT_ID=@INPATIENT_ID AND BABY_ID=@BABY_ID) B,
	     (SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,0 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_BDATE,ORDER_DOC,FIRST_TIMES,		
		AUDITING_USER,AUDITING_USER1,AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,
		DWLX,XMLY,PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>1 AND STATUS_FLAG<=5 AND MNGTYPE IN (0,1,5)
	      UNION ALL
	      SELECT STATUS_FLAG,ORDER_ID,GROUP_ID,NUM,UNIT,CASE B.ISP WHEN 0 THEN ORDER_USAGE ELSE '' END ORDER_USAGE,FREQUENCY,DROPSPER,DOSAGE,
		case when A.MNGTYPE in(1,5) then 1 else A.MNGTYPE end  as MNGTYPE,NTYPE,1 AS 停,INPATIENT_ID,BABY_ID,
		ITEM_CODE,HOITEM_ID,LTRIM(RTRIM(ORDER_CONTEXT)) ORDER_CONTEXT,EXEC_DEPT,SERIAL_NO,
		ORDER_EDATE AS ORDER_BDATE,ORDER_EDOC AS ORDER_DOC, TERMINAL_TIMES AS FIRST_TIMES,
		ORDER_EUSER AS AUDITING_USER,ORDER_EUSER1 AS AUDITING_USER1,ORDER_EUSER2 AS AUDITING_USER2,DEPT_ID,DEPT_BR,ORDER_USAGE USAGE,
		DWLX,XMLY,PS_FLAG,PS_ORDERID,PS_USER,ORDER_SPEC,A.ts,A.zsl,A.zsldw
	      FROM ZY_ORDERRECORD A LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') B ON A.ORDER_USAGE=B.USG
	      WHERE A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT) AND DELETE_BIT=0 AND STATUS_FLAG>3 AND STATUS_FLAG<=5 AND  MNGTYPE=0
	     ) A LEFT JOIN JC_HOI_HL C  ON A.HOITEM_ID=C.HOITEM_ID AND A.XMLY=2
--		LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1
	WHERE A.INPATIENT_ID=B.INPATIENT_ID AND A.BABY_ID=B.BABY_ID --AND B.WARD_ID=@WARDID
	      AND A.AUDITING_USER2 IS NOT NULL
              AND A.ORDER_BDATE BETWEEN @BEGINDATE AND @ENDDATE
	ORDER BY B.BED_NO,B.BABY_ID,B.NAME,A.MNGTYPE,A.ORDER_BDATE,A.ORDER_DOC,A.GROUP_ID,A.SERIAL_NO
   END
END



GO


