if exists (select 1 from dbo.sysobjects where name='SP_ZYYS_ORDERS_SELECT' and type ='P')
	drop PROCEDURE SP_ZYYS_ORDERS_SELECT
go
create PROCEDURE [dbo].[SP_ZYYS_ORDERS_SELECT]  
(  
 @SELTYPE INTEGER,   
 @BABYID INTEGER,   
 @BINID UNIQUEIDENTIFIER,  
 @DEPTID BIGINT  
)   
AS  
  
declare @ISSHowSS int --add by zouchihua 是否显示手术室病人医嘱  
set @ISSHowSS =CAST( ISNULL(( select top 1 CONFIG  from jc_config where id=7148),0) as int)  
declare @zcyxsmc varchar  
set @zcyxsmc=(select top 1 isnull(config,0) from JC_CONFIG where ID=6070)  
  
BEGIN  
 --|长嘱  
 IF @SELTYPE = 1  
 BEGIN  
     SELECT A.STATUS_FLAG,A.ORDER_ID ID,A.GROUP_ID 嘱号,'长' 类,A.NUM 剂量,A.UNIT 单位,A.DWLX,A.ORDER_SPEC 规格,A.ORDER_USAGE 用法,A.FREQUENCY 频率,A.DROPSPER 滴量,A.DOSAGE 剂数,  
     (SELECT NAME FROM JC_ORDERTYPE WHERE CODE=NTYPE) 类型,NTYPE,A.EXEC_DEPT ,A.AUDITING_USER 校对护士,  
     AUDITING_USER1,ORDER_EUSER,ORDER_EUSER1,convert(varchar(30),A.ORDER_BDATE,20)  开始时间,A.ORDER_CONTEXT 医嘱内容,DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 下嘱医生,DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_EDOC) 停嘱医生,  
     A.AUDITING_USER 开嘱转抄,AUDITING_USER1 "开嘱核对",A.ORDER_EDATE 停嘱时间,FIRST_TIMES 首日执行次数,TERMINAL_TIMES 末日次数,  
     A.ORDER_DOC,ORDER_EUSER 停嘱转抄,CAST(HOITEM_ID  AS CHARACTER(18)) HOITEM_ID,ITEM_CODE,XMLY,  
     ORDER_EUSER1 停嘱核对,A.LASTEXECDATE 执行时间,DBO.FUN_ZY_SEEKEMPLOYEENAME(A.LASTEXECUSER) 执行护士,A.EXEC_DEPT 执行科室 ,SERIAL_NO,MNGTYPE,A.PS_FLAG,A.PS_ORDERID,A.JZ_FLAG,A.WZX_FLAG,A.JGBM  
     ,A.MEMO,jsd 警示灯,DEL_PRINT ,IsprintYPGG --add by zouchihua 2012-1-31  
     ,( select top 1 name from JC_KJYP_PURPOSE where id=A.KJYWZY) Yymd,zfbl  
     FROM ZY_ORDERRECORD A  
--  LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1  
--     LEFT JOIN  
--  (SELECT X.ORDER_ID,X.EXEUSER,X.EXECDATE  
--   FROM (SELECT * FROM ZY_ORDEREXEC WHERE (INPATIENT_ID = @BINID) AND (BABY_ID = @BABYID) )X,  
--     (SELECT ORDER_ID,MAX(EXECDATE) AS EXECDATE FROM ZY_ORDEREXEC WHERE (INPATIENT_ID = @BINID) AND (BABY_ID = @BABYID) GROUP BY ORDER_ID) AS Y  
--   WHERE X.ORDER_ID=Y.ORDER_ID AND X.EXECDATE=Y.EXECDATE  
--         ) AS B  
--     ON A.ORDER_ID=B.ORDER_ID  
     WHERE A.MNGTYPE=0  
  AND (A.INPATIENT_ID = @BINID) AND (A.BABY_ID = @BABYID)  
  AND (A.DELETE_BIT = 0)  
  AND ( (A.STATUS_FLAG >= 0 AND A.STATUS_FLAG <= 5) OR A.STATUS_FLAG = 9 ) --OR (A.STATUS_FLAG = 5 AND DATE(A.ORDER_EDATE)=CURRENT DATE) )  
     ORDER BY A.ORDER_BDATE,A.GROUP_ID,SERIAL_NO  
 END  
  
 --|临嘱  
 IF @SELTYPE = 2     
 BEGIN          
  SELECT A.STATUS_FLAG,A.ORDER_ID ID,A.GROUP_ID 嘱号,A.NUM 剂量,A.UNIT 单位,A.DWLX,A.ORDER_SPEC 规格,A.ORDER_USAGE 用法,A.FREQUENCY 频率,A.DROPSPER 滴量,A.DOSAGE 剂数,  
         (SELECT NAME FROM JC_ORDERTYPE WHERE CODE=A.NTYPE) 类型,NTYPE,A.EXEC_DEPT,AUDITING_USER 校对护士,FIRST_TIMES 首日执行次数,  
         AUDITING_USER1,ORDER_EUSER,ORDER_EUSER1,convert(varchar(30),A.ORDER_BDATE,20) 开始时间,CAST(HOITEM_ID  AS CHARACTER(18))  HOITEM_ID,ITEM_CODE,XMLY,  
         A.ORDER_CONTEXT 医嘱内容,DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 下嘱医生,A.AUDITING_USER 开嘱转抄,AUDITING_USER1 开嘱核对,  
         A.ORDER_EDATE 停嘱时间,A.ORDER_DOC,ORDER_EUSER 停嘱转抄,ORDER_EUSER1 停嘱核对,ts 天数, zsl 总量, zsldw 总单位, --add by zouchihua 2012-5-22  
         A.LASTEXECDATE 执行时间,DBO.FUN_ZY_SEEKEMPLOYEENAME(A.LASTEXECUSER) 执行护士,A.EXEC_DEPT 执行科室 ,SERIAL_NO ,MNGTYPE,A.PS_FLAG,A.PS_ORDERID,A.JZ_FLAG ,A.WZX_FLAG,A.JGBM  
         ,A.MEMO,jsd 警示灯,DEL_PRINT ,IsprintYPGG,jldwlx --add by zouchihua 2012-1-31  
         , (select top 1 REALEXECDATE from ZY_ORDEREXEC where ORDER_ID=A.ORDER_ID) REALEXECDATE --add by zouchihua 2013-5-22  
         ,( select top 1 name from JC_KJYP_PURPOSE where id=A.KJYWZY) Yymd,zfbl  
  FROM ZY_ORDERRECORD A  
--  LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1  
--  LEFT JOIN  
--  ( SELECT ORDER_ID,EXEUSER,EXECDATE  
--   FROM ZY_ORDEREXEC WHERE (INPATIENT_ID = @BINID) AND (BABY_ID = @BABYID)) B  
--  ON A.ORDER_ID=B.ORDER_ID  
  WHERE (A.MNGTYPE =1 OR A.MNGTYPE=5)  
   AND (A.INPATIENT_ID = @BINID) AND (A.BABY_ID = @BABYID)  
   AND (A.DELETE_BIT = 0) AND ( (@ISSHowSS=0 and  A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT)) or  @ISSHowSS=1 )  
   AND ( (A.STATUS_FLAG >= 0 AND A.STATUS_FLAG <=5) OR A.STATUS_FLAG=9 ) --OR (A.STATUS_FLAG = 5 AND DATE(A.ORDER_EDATE)=CURRENT DATE) )  
   AND A.NTYPE<>3  
        UNION ALL  
  SELECT A.STATUS_FLAG,A.ORDER_ID ID,A.GROUP_ID 嘱号,A.NUM 剂量,A.UNIT 单位,A.DWLX,A.ORDER_SPEC 规格,A.ORDER_USAGE 用法,A.FREQUENCY 频率,A.DROPSPER 滴量,A.DOSAGE 剂数,  
   (SELECT NAME FROM JC_ORDERTYPE WHERE CODE=A.NTYPE) 类型,A.NTYPE,A.EXEC_DEPT,AUDITING_USER 校对护士,FIRST_TIMES 首日执行次数,  
   AUDITING_USER1,ORDER_EUSER,ORDER_EUSER1,convert(varchar(30),A.ORDER_BDATE,20) "开始时间",CAST(HOITEM_ID  AS CHARACTER(18)) HOITEM_ID,ITEM_CODE,XMLY,  
   A.ORDER_CONTEXT 医嘱内容,DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 下嘱医生,A.AUDITING_USER 开嘱转抄,AUDITING_USER1 开嘱核对,  
   A.ORDER_EDATE 停嘱时间,A.ORDER_DOC,ORDER_EUSER 停嘱转抄,ORDER_EUSER1 停嘱核对,ts 天数, zsl 总量, zsldw 总单位, --add by zouchihua 2012-5-22  
   A.LASTEXECDATE 执行时间,DBO.FUN_ZY_SEEKEMPLOYEENAME(A.LASTEXECUSER) 执行护士,A.EXEC_DEPT 执行科室,SERIAL_NO,MNGTYPE,-1 PS_FLAG, PS_ORDERID,A.JZ_FLAG ,A.WZX_FLAG,A.JGBM  
   ,A.MEMO,jsd 警示灯,DEL_PRINT ,IsprintYPGG,jldwlx --add by zouchihua 2012-1-31  
   , (select top 1 REALEXECDATE from ZY_ORDEREXEC where ORDER_ID=A.ORDER_ID) REALEXECDATE --add by zouchihua 2013-5-22  
   ,( select top 1 name from JC_KJYP_PURPOSE where id=A.KJYWZY) Yymd,zfbl  
  FROM ZY_ORDERRECORD A  
--  LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1  
--  LEFT JOIN     
--  ( SELECT ORDER_ID,EXEUSER,EXECDATE  
--   FROM ZY_ORDEREXEC WHERE (INPATIENT_ID = @BINID) AND (BABY_ID = @BABYID)) B  
--  ON A.ORDER_ID=B.ORDER_ID  
  WHERE (A.MNGTYPE =1 OR A.MNGTYPE=5)  
  AND (A.INPATIENT_ID = @BINID) AND (A.BABY_ID = @BABYID)  
  AND (A.DELETE_BIT = 0) AND ( ( @ISSHowSS=0 and  A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT)) or @ISSHowSS=1)  
  AND ( (A.STATUS_FLAG = 0 OR A.STATUS_FLAG =1 ) OR A.STATUS_FLAG=9) --OR (A.STATUS_FLAG = 5 AND DATE(A.ORDER_EDATE)=CURRENT DATE) )  
  AND A.NTYPE=3  
        UNION ALL  
  SELECT  A.STATUS_FLAG,CONVERT(UNIQUEIDENTIFIER,'99999999-9999-9999-9999-999999999999') ID,A.GROUP_ID 嘱号,A.DOSAGE 剂量,'付' 单位,1 DWLX,CONVERT(VARCHAR,A.DOSAGE) + '付' 规格,A.ORDER_USAGE 用法,A.FREQUENCY 频率,A.DROPSPER 滴量,A.DOSAGE 剂数,  
   (SELECT NAME FROM JC_ORDERTYPE WHERE CODE=A.NTYPE) 类型,A.NTYPE,A.EXEC_DEPT,AUDITING_USER 校对护士,1 首日执行次数,  
    AUDITING_USER1,ORDER_EUSER,ORDER_EUSER1,convert(varchar(30),A.ORDER_BDATE,20) 开始时间,'-1'  HOITEM_ID, '' ITEM_CODE,-1 XMLY,  
   '中草药处方'+  
   case when @zcyxsmc='0' then '' else  (case when rtrim(isnull(A.MEMO,''))!=''   then '【'+isnull(A.MEMO,'')+'】' else isnull((select top 1 '【'+MBMC+'】' from  jc_cfmb where MBXH=A.PS_ORDERID),'') end  )   end  
    医嘱内容,  
   --'中草药处方' 医嘱内容,  
   DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 下嘱医生,A.AUDITING_USER 开嘱转抄,AUDITING_USER1 开嘱核对,  
   A.ORDER_EDATE 停嘱时间,A.ORDER_DOC,ORDER_EUSER 停嘱转抄,ORDER_EUSER1 停嘱核对,ts 天数, null 总量, null 总单位, --add by zouchihua 2012-5-22  
   A.LASTEXECDATE 执行时间,DBO.FUN_ZY_SEEKEMPLOYEENAME(A.LASTEXECUSER) 执行护士,A.EXEC_DEPT 执行科室 ,0 SERIAL_NO,1 MNGTYPE,-1 PS_FLAG,DBO.FUN_GETEMPTYGUID() PS_ORDERID,0 JZ_FLAG, WZX_FLAG,A.JGBM  
   ,A.MEMO,jsd as 警示灯,DEL_PRINT ,IsprintYPGG,1 jldwlx --add by zouchihua 2012-1-31  
   , (select top 1 REALEXECDATE from ZY_ORDEREXEC where GROUP_ID=A.GROUP_ID) REALEXECDATE --add by zouchihua 2013-5-22  
   ,'' Yymd,null zfbl  
  FROM ZY_ORDERRECORD A  
--  LEFT JOIN  
--        --(SELECT X.ORDER_ID,X.EXEUSER,X.EXECDATE  
--        --   FROM (SELECT * FROM ZY_ORDEREXEC WHERE (INPATIENT_ID = BINID) AND (BABY_ID = BABYID) )X,  
--        --        (SELECT ORDER_ID,EXECDATE FROM ZY_ORDEREXEC WHERE (INPATIENT_ID = BINID) AND (BABY_ID = BABYID)) AS Y  
--        --  WHERE X.ORDER_ID=Y.ORDER_ID AND X.EXECDATE=Y.EXECDATE) AS B  
--  ( SELECT ORDER_ID,EXEUSER,EXECDATE  
--   FROM ZY_ORDEREXEC WHERE (INPATIENT_ID = @BINID) AND (BABY_ID = @BABYID)) B  
--  ON A.ORDER_ID=B.ORDER_ID  
  WHERE (A.MNGTYPE =1 OR A.MNGTYPE=5)  
   AND (A.INPATIENT_ID = @BINID) AND (A.BABY_ID = @BABYID)  
   AND (A.DELETE_BIT = 0) AND ( (@ISSHowSS=0 and  A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT )) or @ISSHowSS=1)  
   AND ( (A.STATUS_FLAG >=2 AND A.STATUS_FLAG <6))  
   AND A.NTYPE=3  
  GROUP BY A.STATUS_FLAG,A.GROUP_ID,A.DOSAGE,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,  
   A.NTYPE,A.EXEC_DEPT,A.ORDER_BDATE,A.ORDER_EDATE,  
   AUDITING_USER,AUDITING_USER1,ORDER_EUSER,ORDER_EUSER1,  
   A.ORDER_DOC, ORDER_EDOC,LASTEXECDATE,LASTEXECUSER,A.PRICE,A.JGBM,A.MEMO,DEL_PRINT ,IsprintYPGG,jsd,ts,WZX_FLAG--,zsl,zsldw,jldwlx  
   ,a.PS_ORDERID  
  ORDER BY 开始时间,嘱号,SERIAL_NO  
 END  
  
        --有效长嘱  
 IF @SELTYPE = 3  
 BEGIN  
  SELECT A.STATUS_FLAG,A.ORDER_ID ID,A.GROUP_ID 嘱号,'长' 类,DBO.FUN_ZY_CHGDECIMALTOCHAR(A.NUM) 剂量,A.UNIT 单位,A.DWLX,A.ORDER_SPEC 规格,A.ORDER_USAGE 用法,A.FREQUENCY 频率,A.DROPSPER 滴量,A.DOSAGE 剂数,  
         (SELECT NAME FROM JC_ORDERTYPE WHERE CODE=NTYPE) 类型,NTYPE,A.EXEC_DEPT ,A.AUDITING_USER 校对护士,  
         AUDITING_USER1,ORDER_EUSER,ORDER_EUSER1,convert(varchar(30),A.ORDER_BDATE,20) 开始时间,A.ORDER_CONTEXT 医嘱内容,DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 下嘱医生,DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_EDOC) 停嘱医生,  
         A.AUDITING_USER 开嘱转抄,AUDITING_USER1 开嘱核对,A.ORDER_EDATE 停嘱时间,FIRST_TIMES 首日执行次数,TERMINAL_TIMES 末日次数,  
         A.ORDER_DOC,ORDER_EUSER 停嘱转抄,CAST(HOITEM_ID  AS CHARACTER(18))  HOITEM_ID,ITEM_CODE,XMLY,  
         ORDER_EUSER1 停嘱核对,A.LASTEXECDATE 执行时间,DBO.FUN_ZY_SEEKEMPLOYEENAME(A.LASTEXECUSER) 执行护士,A.EXEC_DEPT 执行科室 ,SERIAL_NO,MNGTYPE,A.PS_FLAG,A.PS_ORDERID,A.JZ_FLAG,A.JGBM  
         ,A.MEMO,jsd 警示灯,DEL_PRINT ,IsprintYPGG --add by zouchihua 2012-1-31  
         , (select top 1 REALEXECDATE from ZY_ORDEREXEC where ORDER_ID=A.ORDER_ID) REALEXECDATE --add by zouchihua 2013-5-22  
         ,( select top 1 name from JC_KJYP_PURPOSE where id=A.KJYWZY) Yymd,zfbl  
  FROM ZY_ORDERRECORD A  
--  LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1  
--  LEFT JOIN  
--  (SELECT X.ORDER_ID,X.EXEUSER,X.EXECDATE  
--   FROM (SELECT * FROM ZY_ORDEREXEC WHERE (INPATIENT_ID = @BINID) AND (BABY_ID = @BABYID)) X,  
--   (SELECT ORDER_ID,MAX(EXECDATE) AS EXECDATE FROM ZY_ORDEREXEC WHERE (INPATIENT_ID = @BINID) AND (BABY_ID = @BABYID) GROUP BY ORDER_ID) AS Y  
--   WHERE X.ORDER_ID=Y.ORDER_ID AND X.EXECDATE=Y.EXECDATE) AS B  
--  ON A.ORDER_ID=B.ORDER_ID  
  WHERE A.MNGTYPE=0  
   AND (A.INPATIENT_ID = @BINID) AND (A.BABY_ID = @BABYID)  
   AND (A.DELETE_BIT = 0)  
   AND (A.STATUS_FLAG =2) --OR (A.STATUS_FLAG = 5 AND DATE(A.ORDER_EDATE)=CURRENT DATE) )  
  ORDER BY A.ORDER_BDATE,A.GROUP_ID,SERIAL_NO  
 END  
     
    --| 麻醉站临嘱     
 IF @SELTYPE = 4         
 BEGIN    
  SELECT A.STATUS_FLAG,A.ORDER_ID ID,A.GROUP_ID 嘱号,A.NUM 剂量,A.UNIT 单位,A.DWLX,A.ORDER_SPEC 规格,A.ORDER_USAGE 用法,A.FREQUENCY 频率,A.DROPSPER 滴量,A.DOSAGE 剂数,  
   (SELECT NAME FROM JC_ORDERTYPE WHERE CODE=A.NTYPE) 类型,NTYPE,A.EXEC_DEPT,AUDITING_USER 校对护士,FIRST_TIMES 首日执行次数,  
   AUDITING_USER1,ORDER_EUSER,ORDER_EUSER1,convert(varchar(30),A.ORDER_BDATE,20) 开始时间,CAST(HOITEM_ID  AS CHARACTER(18))  HOITEM_ID,ITEM_CODE,XMLY,  
   A.ORDER_CONTEXT 医嘱内容,DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 下嘱医生,A.AUDITING_USER 开嘱转抄,AUDITING_USER1 开嘱核对,  
   A.ORDER_EDATE 停嘱时间,A.ORDER_DOC,ORDER_EUSER 停嘱转抄,ORDER_EUSER1 停嘱核对,ts 天数, zsl 总量, zsldw 总单位, --add by zouchihua 2012-5-22  
   A.LASTEXECDATE 执行时间,DBO.FUN_ZY_SEEKEMPLOYEENAME(A.LASTEXECUSER) 执行护士,A.EXEC_DEPT 执行科室 ,SERIAL_NO ,MNGTYPE,A.PS_FLAG,A.PS_ORDERID,A.JZ_FLAG ,A.WZX_FLAG,A.JGBM  
   ,A.MEMO,jsd 警示灯,DEL_PRINT ,IsprintYPGG,jldwlx --add by zouchihua 2012-1-31  
   , (select top 1 REALEXECDATE from ZY_ORDEREXEC where ORDER_ID=A.ORDER_ID) REALEXECDATE --add by zouchihua 2013-5-22  
   ,( select top 1 name from JC_KJYP_PURPOSE where id=A.KJYWZY) Yymd,zfbl  
     FROM ZY_ORDERRECORD A  
--  LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1  
--     LEFT JOIN  
--  (SELECT ORDER_ID,EXEUSER,EXECDATE  
--   FROM ZY_ORDEREXEC WHERE (INPATIENT_ID = @BINID) AND (BABY_ID = @BABYID)) B  
--  ON A.ORDER_ID=B.ORDER_ID  
  WHERE (A.MNGTYPE =1 OR A.MNGTYPE=5)  
   AND (A.INPATIENT_ID = @BINID) AND (A.BABY_ID = @BABYID)  
   AND (A.DELETE_BIT = 0)  
   AND ( (A.STATUS_FLAG >= 0 AND A.STATUS_FLAG <=5) OR A.STATUS_FLAG=9 ) --OR (A.STATUS_FLAG = 5 AND DATE(A.ORDER_EDATE)=CURRENT DATE) )  
   AND A.NTYPE<>3  
   AND  ( (A.DEPT_ID IN (SELECT DEPTID FROM SS_DEPT where DEPTID=@DEPTID)) )  --Modify By Tany 2015-03-25 手术和麻醉的医嘱分开显示
        UNION ALL  
  SELECT A.STATUS_FLAG,A.ORDER_ID ID,A.GROUP_ID 嘱号,A.NUM 剂量,A.UNIT 单位,A.DWLX,A.ORDER_SPEC 规格,A.ORDER_USAGE 用法,A.FREQUENCY 频率,A.DROPSPER 滴量,A.DOSAGE 剂数,  
   (SELECT NAME FROM JC_ORDERTYPE WHERE CODE=A.NTYPE) 类型,A.NTYPE,A.EXEC_DEPT,AUDITING_USER 校对护士,FIRST_TIMES 首日执行次数,  
   AUDITING_USER1,ORDER_EUSER,ORDER_EUSER1,convert(varchar(30),A.ORDER_BDATE,20) 开始时间,CAST(HOITEM_ID  AS CHARACTER(18)) HOITEM_ID,ITEM_CODE,XMLY,  
   A.ORDER_CONTEXT 医嘱内容,DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 下嘱医生,A.AUDITING_USER 开嘱转抄,AUDITING_USER1 开嘱核对,  
   A.ORDER_EDATE 停嘱时间,A.ORDER_DOC,ORDER_EUSER 停嘱转抄,ORDER_EUSER1 停嘱核对,ts 天数, zsl 总量, zsldw 总单位, --add by zouchihua 2012-5-22  
   A.LASTEXECDATE 执行时间,DBO.FUN_ZY_SEEKEMPLOYEENAME(A.LASTEXECUSER) 执行护士,A.EXEC_DEPT 执行科室 ,SERIAL_NO,MNGTYPE,-1 PS_FLAG,  PS_ORDERID,A.JZ_FLAG ,A.WZX_FLAG,A.JGBM  
   ,A.MEMO,jsd 警示灯,DEL_PRINT ,IsprintYPGG, jldwlx --add by zouchihua 2012-1-31  
   , (select top 1 REALEXECDATE from ZY_ORDEREXEC where ORDER_ID=A.ORDER_ID) REALEXECDATE --add by zouchihua 2013-5-22  
   ,( select top 1 name from JC_KJYP_PURPOSE where id=A.KJYWZY) Yymd,zfbl  
  FROM ZY_ORDERRECORD A  
--  LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1  
--  LEFT JOIN     
--   (SELECT ORDER_ID,EXEUSER,EXECDATE  
--   FROM ZY_ORDEREXEC WHERE (INPATIENT_ID = @BINID) AND (BABY_ID = @BABYID)) B  
--   ON A.ORDER_ID=B.ORDER_ID  
  WHERE (A.MNGTYPE =1 OR A.MNGTYPE=5)  
   AND (A.INPATIENT_ID = @BINID) AND (A.BABY_ID = @BABYID)  
   AND (A.DELETE_BIT = 0)  
   AND ( (A.STATUS_FLAG = 0 OR A.STATUS_FLAG =1 ) OR A.STATUS_FLAG=9) --OR (A.STATUS_FLAG = 5 AND DATE(A.ORDER_EDATE)=CURRENT DATE) )  
   AND A.NTYPE=3  
   AND  ( ( A.DEPT_ID IN (SELECT DEPTID FROM SS_DEPT where DEPTID=@DEPTID)) )  --Modify By Tany 2015-03-25 手术和麻醉的医嘱分开显示
     
  UNION ALL  
  SELECT  A.STATUS_FLAG,CONVERT(UNIQUEIDENTIFIER,'99999999-9999-9999-9999-999999999999') ID,A.GROUP_ID 嘱号,A.DOSAGE 剂量,'付' 单位,1 DWLX,CONVERT(VARCHAR,A.DOSAGE) + '付' 规格,A.ORDER_USAGE 用法,A.FREQUENCY 频率,A.DROPSPER 滴量,A.DOSAGE 剂数,  
   (SELECT NAME FROM JC_ORDERTYPE WHERE CODE=A.NTYPE) 类型,A.NTYPE,A.EXEC_DEPT,AUDITING_USER 校对护士,1 首日执行次数,  
    AUDITING_USER1,ORDER_EUSER,ORDER_EUSER1,convert(varchar(30),A.ORDER_BDATE,20) 开始时间,''  HOITEM_ID, '' ITEM_CODE,-1 XMLY,  
   '中草药处方'+  
   case when @zcyxsmc='0' then '' else  (case when rtrim(isnull(A.MEMO,''))!=''   then '【'+isnull(A.MEMO,'')+'】' else isnull((select top 1 '【'+MBMC+'】' from  jc_cfmb where MBXH=A.PS_ORDERID),'') end  )   end  
    医嘱内容,  
   DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 下嘱医生,  
   A.AUDITING_USER 开嘱转抄,AUDITING_USER1 开嘱核对,  
   A.ORDER_EDATE 停嘱时间,A.ORDER_DOC,ORDER_EUSER 停嘱转抄,ORDER_EUSER1 停嘱核对,ts 天数, null 总量, null 总单位, --add by zouchihua 2012-5-22  
   A.LASTEXECDATE 执行时间,DBO.FUN_ZY_SEEKEMPLOYEENAME(A.LASTEXECUSER) 执行护士,A.EXEC_DEPT 执行科室 ,0 SERIAL_NO,1 MNGTYPE,-1 PS_FLAG,DBO.FUN_GETEMPTYGUID() PS_ORDERID,0 JZ_FLAG , WZX_FLAG,A.JGBM  
   ,A.MEMO,jsd as 警示灯,DEL_PRINT ,IsprintYPGG,1 jldwlx --add by zouchihua 2012-1-31  
   , (select top 1 REALEXECDATE from ZY_ORDEREXEC where GROUP_ID=A.GROUP_ID) REALEXECDATE --add by zouchihua 2013-5-22  
   ,'' Yymd,null zfbl  
  FROM ZY_ORDERRECORD A  
--  LEFT JOIN  
--  --(SELECT X.ORDER_ID,X.EXEUSER,X.EXECDATE  
--  --   FROM (SELECT * FROM ZY_ORDEREXEC WHERE (INPATIENT_ID = BINID) AND (BABY_ID = BABYID) )X,  
--  --        (SELECT ORDER_ID,EXECDATE FROM ZY_ORDEREXEC WHERE (INPATIENT_ID = BINID) AND (BABY_ID = BABYID)) AS Y  
--  --  WHERE X.ORDER_ID=Y.ORDER_ID AND X.EXECDATE=Y.EXECDATE) AS B  
--  ( SELECT ORDER_ID,EXEUSER,EXECDATE  
--   FROM ZY_ORDEREXEC WHERE (INPATIENT_ID = @BINID) AND (BABY_ID = @BABYID)) B  
--  ON A.ORDER_ID=B.ORDER_ID  
  WHERE (A.MNGTYPE =1 OR A.MNGTYPE=5)  
   AND (A.INPATIENT_ID = @BINID) AND (A.BABY_ID = @BABYID)  
   AND (A.DELETE_BIT = 0)  
   AND ( (A.STATUS_FLAG >=2 AND A.STATUS_FLAG <6))  
   AND A.NTYPE=3  
   AND ( ( A.DEPT_ID IN (SELECT DEPTID FROM SS_DEPT where DEPTID=@DEPTID)) )  --Modify By Tany 2015-03-25 手术和麻醉的医嘱分开显示
  GROUP BY A.STATUS_FLAG,A.GROUP_ID,A.DOSAGE,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,  
   A.NTYPE,A.EXEC_DEPT,A.ORDER_BDATE,A.ORDER_EDATE,  
   AUDITING_USER,AUDITING_USER1,ORDER_EUSER,ORDER_EUSER1,  
   A.ORDER_DOC, ORDER_EDOC,LASTEXECDATE,LASTEXECUSER,A.PRICE,A.JGBM,A.MEMO,DEL_PRINT ,IsprintYPGG,jsd,ts,WZX_FLAG--,zsl,zsldw,jldwlx  
   ,A.PS_ORDERID  
  ORDER BY 开始时间,嘱号,SERIAL_NO   
 END   
  
 --| 特殊治疗临嘱    
 IF @SELTYPE = 5         
 BEGIN    
  SELECT A.STATUS_FLAG,A.ORDER_ID ID,A.GROUP_ID 嘱号,A.NUM 剂量,A.UNIT 单位,A.DWLX,A.ORDER_SPEC 规格,A.ORDER_USAGE 用法,A.FREQUENCY 频率,A.DROPSPER 滴量,A.DOSAGE 剂数,  
   (SELECT NAME FROM JC_ORDERTYPE WHERE CODE=A.NTYPE) 类型,NTYPE,A.EXEC_DEPT,AUDITING_USER 校对护士,FIRST_TIMES 首日执行次数,  
   AUDITING_USER1,ORDER_EUSER,ORDER_EUSER1,convert(varchar(30),A.ORDER_BDATE,20) 开始时间,CAST(HOITEM_ID  AS CHARACTER(18))  HOITEM_ID,ITEM_CODE,XMLY,  
   A.ORDER_CONTEXT 医嘱内容,DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 下嘱医生,A.AUDITING_USER 开嘱转抄,AUDITING_USER1 开嘱核对,  
   A.ORDER_EDATE 停嘱时间,A.ORDER_DOC,ORDER_EUSER 停嘱转抄,ORDER_EUSER1 停嘱核对,ts 天数, zsl 总量, zsldw 总单位, --add by zouchihua 2012-5-22  
   A.LASTEXECDATE 执行时间,DBO.FUN_ZY_SEEKEMPLOYEENAME(A.LASTEXECUSER) 执行护士,A.EXEC_DEPT 执行科室 ,SERIAL_NO ,MNGTYPE,A.PS_FLAG,A.PS_ORDERID,A.JZ_FLAG ,A.WZX_FLAG,A.JGBM  
   ,A.MEMO,jsd 警示灯,DEL_PRINT ,IsprintYPGG,jldwlx --add by zouchihua 2012-1-31  
   , (select top 1 REALEXECDATE from ZY_ORDEREXEC where ORDER_ID=A.ORDER_ID) REALEXECDATE --add by zouchihua 2013-5-22  
   ,( select top 1 name from JC_KJYP_PURPOSE where id=A.KJYWZY) Yymd,zfbl  
     FROM ZY_ORDERRECORD A  
--  LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1  
--     LEFT JOIN  
--  (SELECT ORDER_ID,EXEUSER,EXECDATE  
--   FROM ZY_ORDEREXEC WHERE (INPATIENT_ID = @BINID) AND (BABY_ID = @BABYID)) B  
--  ON A.ORDER_ID=B.ORDER_ID  
  WHERE (A.MNGTYPE =1 OR A.MNGTYPE=5)  
   AND (A.INPATIENT_ID = @BINID) AND (A.BABY_ID = @BABYID)  
   AND (A.DELETE_BIT = 0)  
   AND ( (A.STATUS_FLAG >= 0 AND A.STATUS_FLAG <=5) OR A.STATUS_FLAG=9 ) --OR (A.STATUS_FLAG = 5 AND DATE(A.ORDER_EDATE)=CURRENT DATE) )  
   AND A.NTYPE<>3  
   AND A.DEPT_ID = @DEPTID  
        UNION ALL  
  SELECT A.STATUS_FLAG,A.ORDER_ID ID,A.GROUP_ID 嘱号,A.NUM 剂量,A.UNIT 单位,A.DWLX,A.ORDER_SPEC 规格,A.ORDER_USAGE 用法,A.FREQUENCY 频率,A.DROPSPER 滴量,A.DOSAGE 剂数,  
   (SELECT NAME FROM JC_ORDERTYPE WHERE CODE=A.NTYPE) 类型,A.NTYPE,A.EXEC_DEPT,AUDITING_USER 校对护士,FIRST_TIMES 首日执行次数,  
   AUDITING_USER1,ORDER_EUSER,ORDER_EUSER1,convert(varchar(30),A.ORDER_BDATE,20) 开始时间,CAST(HOITEM_ID  AS CHARACTER(18)) HOITEM_ID,ITEM_CODE,XMLY,  
   A.ORDER_CONTEXT 医嘱内容,DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 下嘱医生,A.AUDITING_USER 开嘱转抄,AUDITING_USER1 开嘱核对,  
   A.ORDER_EDATE 停嘱时间,A.ORDER_DOC,ORDER_EUSER 停嘱转抄,ORDER_EUSER1 停嘱核对,ts 天数, zsl 总量, zsldw 总单位, --add by zouchihua 2012-5-22  
   A.LASTEXECDATE 执行时间,DBO.FUN_ZY_SEEKEMPLOYEENAME(A.LASTEXECUSER) 执行护士,A.EXEC_DEPT 执行科室 ,SERIAL_NO,MNGTYPE,-1 PS_FLAG, PS_ORDERID,A.JZ_FLAG ,A.WZX_FLAG,A.JGBM  
   ,A.MEMO,jsd 警示灯,DEL_PRINT ,IsprintYPGG ,jldwlx--add by zouchihua 2012-1-31  
   , (select top 1 REALEXECDATE from ZY_ORDEREXEC where ORDER_ID=A.ORDER_ID) REALEXECDATE --add by zouchihua 2013-5-22  
   ,( select top 1 name from JC_KJYP_PURPOSE where id=A.KJYWZY) Yymd,zfbl  
  FROM ZY_ORDERRECORD A  
--  LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1  
--  LEFT JOIN     
--   (SELECT ORDER_ID,EXEUSER,EXECDATE  
--   FROM ZY_ORDEREXEC WHERE (INPATIENT_ID = @BINID) AND (BABY_ID = @BABYID)) B  
--   ON A.ORDER_ID=B.ORDER_ID  
  WHERE (A.MNGTYPE =1 OR A.MNGTYPE=5)  
   AND (A.INPATIENT_ID = @BINID) AND (A.BABY_ID = @BABYID)  
   AND (A.DELETE_BIT = 0)  
   AND ( (A.STATUS_FLAG = 0 OR A.STATUS_FLAG =1 ) OR A.STATUS_FLAG=9) --OR (A.STATUS_FLAG = 5 AND DATE(A.ORDER_EDATE)=CURRENT DATE) )  
   AND A.NTYPE=3  
   AND A.DEPT_ID = @DEPTID  
  UNION ALL  
  SELECT  A.STATUS_FLAG,CONVERT(UNIQUEIDENTIFIER,'99999999-9999-9999-9999-999999999999') ID,A.GROUP_ID 嘱号,A.DOSAGE 剂量,'付' 单位,1 DWLX,CONVERT(VARCHAR,A.DOSAGE) + '付' 规格,A.ORDER_USAGE 用法,A.FREQUENCY 频率,A.DROPSPER 滴量,A.DOSAGE 剂数,  
   (SELECT NAME FROM JC_ORDERTYPE WHERE CODE=A.NTYPE) 类型,A.NTYPE,A.EXEC_DEPT,AUDITING_USER 校对护士,1 首日执行次数,  
    AUDITING_USER1,ORDER_EUSER,ORDER_EUSER1,convert(varchar(30),A.ORDER_BDATE,20) 开始时间,''  HOITEM_ID, '' ITEM_CODE,-1 XMLY,  
   '中草药处方'+  
   case when @zcyxsmc='0' then '' else  (case when rtrim(isnull(A.MEMO,''))!=''   then '【'+isnull(A.MEMO,'')+'】' else isnull((select top 1 '【'+MBMC+'】' from  jc_cfmb where MBXH=A.PS_ORDERID),'') end  )   end  
    医嘱内容,  
   DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 下嘱医生,A.AUDITING_USER 开嘱转抄,AUDITING_USER1 开嘱核对,  
   A.ORDER_EDATE 停嘱时间,A.ORDER_DOC,ORDER_EUSER 停嘱转抄,ORDER_EUSER1 停嘱核对,ts 天数, null 总量, null 总单位, --add by zouchihua 2012-5-22  
   A.LASTEXECDATE 执行时间,DBO.FUN_ZY_SEEKEMPLOYEENAME(A.LASTEXECUSER) 执行护士,A.EXEC_DEPT 执行科室 ,0 SERIAL_NO,1 MNGTYPE,-1 PS_FLAG,DBO.FUN_GETEMPTYGUID() PS_ORDERID,0 JZ_FLAG , WZX_FLAG,A.JGBM  
   ,A.MEMO,jsd as 警示灯,DEL_PRINT ,IsprintYPGG,1 jldwlx --add by zouchihua 2012-1-31  
   , (select top 1 REALEXECDATE from ZY_ORDEREXEC where GROUP_ID=A.GROUP_ID) REALEXECDATE --add by zouchihua 2013-5-22  
   ,'' Yymd,null zfbl  
  FROM ZY_ORDERRECORD A  
--  LEFT JOIN  
--  --(SELECT X.ORDER_ID,X.EXEUSER,X.EXECDATE  
--  --   FROM (SELECT * FROM ZY_ORDEREXEC WHERE (INPATIENT_ID = BINID) AND (BABY_ID = BABYID) )X,  
--  --        (SELECT ORDER_ID,EXECDATE FROM ZY_ORDEREXEC WHERE (INPATIENT_ID = BINID) AND (BABY_ID = BABYID)) AS Y  
--  --  WHERE X.ORDER_ID=Y.ORDER_ID AND X.EXECDATE=Y.EXECDATE) AS B  
--  ( SELECT ORDER_ID,EXEUSER,EXECDATE  
--   FROM ZY_ORDEREXEC WHERE (INPATIENT_ID = @BINID) AND (BABY_ID = @BABYID)) B  
--  ON A.ORDER_ID=B.ORDER_ID  
  WHERE (A.MNGTYPE =1 OR A.MNGTYPE=5)  
   AND (A.INPATIENT_ID = @BINID) AND (A.BABY_ID = @BABYID)  
   AND (A.DELETE_BIT = 0)  
   AND ( (A.STATUS_FLAG >=2 AND A.STATUS_FLAG <6))  
   AND A.NTYPE=3  
   AND A.DEPT_ID = @DEPTID  
  GROUP BY A.STATUS_FLAG,A.GROUP_ID,A.DOSAGE,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,  
   A.NTYPE,A.EXEC_DEPT,A.ORDER_BDATE,A.ORDER_EDATE,  
   AUDITING_USER,AUDITING_USER1,ORDER_EUSER,ORDER_EUSER1,  
   A.ORDER_DOC, ORDER_EDOC,LASTEXECDATE,LASTEXECUSER,A.PRICE,A.JGBM,A.MEMO,DEL_PRINT ,IsprintYPGG,jsd,ts,WZX_FLAG--,zsl,zsldw,jldwlx  
   ,A.PS_ORDERID  
  ORDER BY 开始时间,嘱号,SERIAL_NO   
 END   
END  
  
/*  
modify by zouchihua 中草药医嘱ps_orderid 取数据库本身id ,中草药的ps_orderid是为了保存模版的id！  
*/  
