IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SP_SS_SSMZCX]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SP_SS_SSMZCX]
GO
CREATE PROCEDURE [dbo].[SP_SS_SSMZCX]    
(    
 @KSSJ DATETIME,     
 @JSSJ DATETIME,     
 @SSKS BIGINT,      
 @SIGE INT    
)     
AS    
BEGIN    
 DECLARE @DATE1 VARCHAR(19)    
 DECLARE @DATE2 VARCHAR(19)    
 SET @DATE1= CAST(CAST(@KSSJ AS DATETIME)AS VARCHAR(19))+' 00:00:00'    
 SET @DATE2= CAST(DATEADD(DAY, 1, CAST(@JSSJ AS DATETIME))AS VARCHAR(19))+' 00:00:00'    
    
 -- 未安排手术----------------------------------------------------------------------------------------------------------------------------------------------------    
 IF @SIGE=0    
  SELECT DISTINCT A.*,DBO.FUN_JC_EMPNAME(SQDJCZY) SQDJCZY_NAME,B.NAME YSMZ_NAME,C.NAME PAT_NAME,C.BED_NO,C.SEX_NAME,DBO.FUN_ZY_AGE(C.BIRTHDAY,0,GETDATE()) AGE,C.CUR_DEPT_NAME DEPT_NAME,DBO.FUN_JC_EMPNAME(A.ZDYS) ZDYS_NAME,'' MZYS_NAME,DBO.FUN_GETDEPTNAME(
  
A.DEPTID) SQKS_NAME,dbo.fun_getEmpName(shys) shysxm,SHRQ , (   
       CASE WHEN    
       (SELECT COUNT(*) AS num FROM dbo.ZY_FEE_SPECI WHERE DEPT_ID=@SSKS AND INPATIENT_ID = a.INPATIENT_ID)  >0 THEN 0 ELSE 1 END ) isjz    
  FROM SS_APPRECORD A        
  LEFT JOIN SS_ANESTHESIACODE B ON CAST(A.YSMZ AS INT)=B.ID           
  INNER JOIN VI_ZY_VINPATIENT_BED C ON A.INPATIENT_ID=C.INPATIENT_ID AND C.BABY_ID=0          
  WHERE (SHBJ=1 OR JZSS=1) AND APBJ=0 AND BDELETE=0 AND A.SSDEPT=@SSKS AND YSSSRQ>=@DATE1 AND YSSSRQ<=@DATE2    
     
 -- 未安排手术 （手术主窗体）    
 IF @SIGE=10    
  SELECT DISTINCT A.*,A.YSSSRQ YXSSRQ,DBO.FUN_GETEMPTYGUID() SSTC,DBO.FUN_JC_EMPNAME(SQDJCZY) SQDJCZY_NAME,B.NAME YSMZ_NAME,C.NAME PAT_NAME,C.BED_NO,C.SEX_NAME,DBO.FUN_ZY_AGE(C.BIRTHDAY,0,GETDATE()) AGE,C.CUR_DEPT_NAME DEPT_NAME,DBO.FUN_JC_EMPNAME(A.ZDYS)
  
 ZDYS_NAME,'' MZYS_NAME,DBO.FUN_GETDEPTNAME(A.DEPTID) SQKS_NAME ,dbo.fun_getEmpName(shys) shysxm,SHRQ  , (   
       CASE WHEN    
       (SELECT COUNT(*) AS num FROM dbo.ZY_FEE_SPECI WHERE DEPT_ID=@SSKS AND INPATIENT_ID = a.INPATIENT_ID)  >0 THEN 0 ELSE 1 END ) isjz    
  FROM SS_APPRECORD A        
  LEFT JOIN SS_ANESTHESIACODE B ON CAST(A.YSMZ AS INT)=B.ID           
  INNER JOIN VI_ZY_VINPATIENT_BED C ON A.INPATIENT_ID=C.INPATIENT_ID AND C.BABY_ID=0          
  WHERE (SHBJ=1  OR JZSS=1) AND APBJ=0 AND BDELETE=0 AND A.SSDEPT=@SSKS --add by zouchihua 2013-8-30是shbj=2表示是特殊手术科主任已经审核的，还需要上级审核    
  ORDER BY A.YSSSRQ --ADD BY TANY 2011-04-14    
     
 -- 未安排手术 （麻醉主窗体）    
 IF @SIGE=15    
  SELECT DISTINCT A.*,A.YSSSRQ YXSSRQ,DBO.FUN_GETEMPTYGUID() SSTC,DBO.FUN_JC_EMPNAME(SQDJCZY) SQDJCZY_NAME,B.NAME YSMZ_NAME,C.NAME PAT_NAME,C.BED_NO,C.SEX_NAME,DBO.FUN_ZY_AGE(C.BIRTHDAY,0,GETDATE()) AGE,C.CUR_DEPT_NAME DEPT_NAME,DBO.FUN_JC_EMPNAME(A.ZDYS)
  
 ZDYS_NAME,'' MZYS_NAME,DBO.FUN_GETDEPTNAME(A.DEPTID) SQKS_NAME ,dbo.fun_getEmpName(shys) shysxm,SHRQ  , (   
       CASE WHEN    
       (SELECT COUNT(*) AS num FROM dbo.ZY_FEE_SPECI WHERE DEPT_ID=@SSKS AND INPATIENT_ID = a.INPATIENT_ID)  >0 THEN 0 ELSE 1 END ) isjz    
  FROM SS_APPRECORD A        
  LEFT JOIN SS_ANESTHESIACODE B ON CAST(A.YSMZ AS INT)=B.ID           
  INNER JOIN VI_ZY_VINPATIENT_BED C ON A.INPATIENT_ID=C.INPATIENT_ID AND C.BABY_ID=0 AND C.FLAG<4          
  WHERE (SHBJ=1 OR JZSS=1) AND APBJ=0 AND BDELETE=0     
  ORDER BY A.YSSSRQ --ADD BY TANY 2011-04-14    
    
 -- 已安排手术------------------------------------------------------------------------------------------------------------------------------------------------------    
 IF @SIGE=1    
  SELECT  DISTINCT D.NAME PAT_NAME,D.BED_NO,D.SEX_NAME,DBO.FUN_ZY_AGE(D.BIRTHDAY,0,GETDATE()) AGE,D.CUR_DEPT_NAME DEPT_NAME,A.*,DBO.FUN_JC_EMPNAME(SQDJCZY) SQDJCZY_NAME,            
   B.SSTC,B.XSHS,B.XHHS,B.XSHS_NAME,B.XHHS_NAME,C.ROOMID,DBO.FUN_JC_EMPNAME(A.ZDYS) ZDYS_NAME,            
   (ISNULL(dbo.fun_getEmpName(SSYZ),''))+(ISNULL(dbo.fun_getEmpName(SSEZ),''))+(isnull(dbo.fun_getEmpName(SSSZ),'')) ZS,             
   DBO.FUN_JC_EMPNAME(A.MZYS) MZYS_NAME,DBO.FUN_JC_EMPNAME(A.MZYS1) FMYS_NAME,E.NAME YSMZ_NAME,             
   (CASE WHEN CGZ1_NAME <>'' THEN CGZ1_NAME ELSE '' END)+(CASE WHEN CGZ2_NAME <>''THEN ','+CGZ2_NAME ELSE '' END)+(CASE WHEN CGZ3_NAME <>'' THEN ','+CGZ3_NAME ELSE '' END)+(CASE WHEN CGZ4_NAME <>'' THEN ','+CGZ4_NAME ELSE '' END) CGZ,DBO.FUN_GETDEPTNAME(A
  
.DEPTID) SQKS_NAME,dbo.fun_getEmpName(shys) shysxm,SHRQ     
   , dbo.fun_getEmpName(SSYZ) SSYZ_NAME,dbo.fun_getEmpName(SSEZ) SSEZ_NAME,  f.NAME ,ssbz  , (   
       CASE WHEN    
       (SELECT COUNT(*) AS num FROM dbo.ZY_FEE_SPECI WHERE DEPT_ID=@SSKS AND INPATIENT_ID = a.INPATIENT_ID)  >0 THEN 0 ELSE 1 END ) isjz    
  FROM SS_APPRECORD A     
  INNER JOIN (SELECT * FROM SS_ARRRECORD WHERE WCBJ=0 AND BDELETE=0) B ON A.SNO=B.SNO      
  LEFT JOIN  SS_ROOMTC C ON B.SSTC=C.ID     
  left join SS_ROOM f on C.ROOMID=f.ID    
  LEFT JOIN  VI_ZY_VINPATIENT_BED D ON A.INPATIENT_ID=D.INPATIENT_ID AND D.BABY_ID=0          
  LEFT JOIN SS_ANESTHESIACODE E ON CAST(A.YSMZ AS INT)=E.ID     
  WHERE A.APBJ=1 AND A.BDELETE=0 AND A.SSDEPT=@SSKS  AND A.YSSSRQ>=@DATE1 AND A.YSSSRQ<=@DATE2     
  ORDER BY A.YSSSRQ --ADD BY TANY 2011-05-03    
  --ORDER BY C.ROOMID    
     
 -- 已安排手术 （手术主窗体）    
 IF @SIGE=11    
  SELECT  DISTINCT D.NAME PAT_NAME,D.BED_NO,D.SEX_NAME,DBO.FUN_ZY_AGE(D.BIRTHDAY,0,GETDATE()) AGE,D.CUR_DEPT_NAME DEPT_NAME,A.*,DBO.FUN_JC_EMPNAME(SQDJCZY) SQDJCZY_NAME,            
   B.YXSSRQ,B.SSTC,B.XSHS,B.XHHS,B.XSHS_NAME,B.XHHS_NAME,C.ROOMID,DBO.FUN_JC_EMPNAME(A.ZDYS) ZDYS_NAME,            
   (CASE WHEN SSYZ_NAME <>'' THEN SSYZ_NAME ELSE '' END)+(CASE WHEN SSEZ_NAME <>'' THEN ','+SSEZ_NAME ELSE '' END)+(CASE WHEN SSSZ_NAME <>'' THEN ','+SSSZ_NAME ELSE '' END) ZS,             
   DBO.FUN_JC_EMPNAME(A.MZYS) MZYS_NAME,DBO.FUN_JC_EMPNAME(A.MZYS1) FMYS_NAME,E.NAME YSMZ_NAME,             
   (CASE WHEN CGZ1_NAME <>'' THEN CGZ1_NAME ELSE '' END)+(CASE WHEN CGZ2_NAME <>''THEN ','+CGZ2_NAME ELSE '' END)+(CASE WHEN CGZ3_NAME <>'' THEN ','+CGZ3_NAME ELSE '' END)+(CASE WHEN CGZ4_NAME <>'' THEN ','+CGZ4_NAME ELSE '' END) CGZ,DBO.FUN_GETDEPTNAME(A
  
.DEPTID) SQKS_NAME ,dbo.fun_getEmpName(shys) shysxm,SHRQ   , (   
       CASE WHEN    
       (SELECT COUNT(*) AS num FROM dbo.ZY_FEE_SPECI WHERE DEPT_ID=@SSKS AND INPATIENT_ID = a.INPATIENT_ID)  >0 THEN 0 ELSE 1 END ) isjz    
  FROM SS_APPRECORD A     
  INNER JOIN (SELECT * FROM SS_ARRRECORD WHERE WCBJ=0 AND BDELETE=0) B ON A.SNO=B.SNO      
  LEFT JOIN  SS_ROOMTC C ON B.SSTC=C.ID     
  INNER JOIN  VI_ZY_VINPATIENT_BED D ON A.INPATIENT_ID=D.INPATIENT_ID AND D.BABY_ID=0 AND D.FLAG=3          
  LEFT JOIN SS_ANESTHESIACODE E ON CAST(A.YSMZ AS INT)=E.ID     
  WHERE A.APBJ=1 AND A.BDELETE=0 AND A.SSDEPT=@SSKS     
  ORDER BY A.YSSSRQ --ADD BY TANY 2011-04-14    
     
 -- 已安排手术 （麻醉主窗体）    
 IF @SIGE=13    
  SELECT  DISTINCT D.NAME PAT_NAME,D.BED_NO,D.SEX_NAME,DBO.FUN_ZY_AGE(D.BIRTHDAY,0,GETDATE()) AGE,D.CUR_DEPT_NAME DEPT_NAME,A.*,DBO.FUN_JC_EMPNAME(SQDJCZY) SQDJCZY_NAME,            
   B.YXSSRQ,B.SSTC,B.XSHS,B.XHHS,B.XSHS_NAME,B.XHHS_NAME,C.ROOMID,DBO.FUN_JC_EMPNAME(A.ZDYS) ZDYS_NAME,            
   (CASE WHEN SSYZ_NAME <>'' THEN SSYZ_NAME ELSE '' END)+(CASE WHEN SSEZ_NAME <>'' THEN ','+SSEZ_NAME ELSE '' END)+(CASE WHEN SSSZ_NAME <>'' THEN ','+SSSZ_NAME ELSE '' END) ZS,             
   DBO.FUN_JC_EMPNAME(A.MZYS) MZYS_NAME,DBO.FUN_JC_EMPNAME(A.MZYS1) FMYS_NAME,E.NAME YSMZ_NAME,             
   (CASE WHEN CGZ1_NAME <>'' THEN CGZ1_NAME ELSE '' END)+(CASE WHEN CGZ2_NAME <>''THEN ','+CGZ2_NAME ELSE '' END)+(CASE WHEN CGZ3_NAME <>'' THEN ','+CGZ3_NAME ELSE '' END)+(CASE WHEN CGZ4_NAME <>'' THEN ','+CGZ4_NAME ELSE '' END) CGZ,DBO.FUN_GETDEPTNAME(A.DEPTID) SQKS_NAME ,dbo.fun_getEmpName(shys) shysxm,SHRQ  , (   
       CASE WHEN    
       (SELECT COUNT(*) AS num FROM dbo.ZY_FEE_SPECI WHERE DEPT_ID=@SSKS AND INPATIENT_ID = a.INPATIENT_ID)  >0 THEN 0 ELSE 1 END ) isjz    
  FROM SS_APPRECORD A     
  INNER JOIN (SELECT * FROM SS_ARRRECORD WHERE WCBJ=0 AND BDELETE=0) B ON A.SNO=B.SNO      
  LEFT JOIN  SS_ROOMTC C ON B.SSTC=C.ID     
  INNER JOIN  VI_ZY_VINPATIENT_BED D ON A.INPATIENT_ID=D.INPATIENT_ID AND D.BABY_ID=0  AND D.FLAG=3       
  LEFT JOIN SS_ANESTHESIACODE E ON CAST(A.YSMZ AS INT)=E.ID     
  WHERE A.APBJ=1 AND A.BDELETE=0  AND (B.YSMZ IS NULL OR B.YSMZ='0') AND A.YSSSRQ>DATEADD(DAY,-15,GETDATE())    
  ORDER BY A.YSSSRQ --ADD BY TANY 2011-04-14    
    
 -- 已安排麻醉（麻醉主窗体）------------------------------------------------------------------------------------------------------------------------------------------------------------------------    
 IF @SIGE=16    
--  SELECT DISTINCT A.SNO,A.INPATIENT_NO,CASE WHEN A.SHZD IS NOT NULL THEN A.SHZD ELSE A.SSFZ END ZD,B.YSSS,A.ZDYS,DBO.FUN_JC_EMPNAME(A.ZDYS) ZDYS_NAME,    
--   B.YSMZ,D.NAME APMZ,B.YXMZ,A.MZYS,DBO.FUN_JC_EMPNAME(A.MZYS) MZYS_NAME,A.FMYS_NAME,COALESCE(B.YXSSRQ,A.YSSSRQ) YXSSRQ,A.SSTYS,A.MZTYS,    
--   A.SQDJCZY,DBO.FUN_JC_EMPNAME(A.SQDJCZY) SQDJCZY_NAME,B.WCBJ,DBO.FUN_JC_DEPTNAME(A.SSDEPT) SSDEPT,A.INPATIENT_ID,C.NAME ,    
--   DBO.FUN_ZY_SEEKSEXNAME(CHAR(C.SEXCODE)) SEXNAME,DBO.FUN_ZY_AGE(C.BIRTHDAY,0,GETDATE()) AGE,DBO.FUN_JC_DEPTNAME(A.DEPTID) DEPTNAME,B.WCBJ,    
--   B.SSTC,F.NAME SSROOM,F.NAME+E.NAME ROOMNAME     
--  FROM SS_APPRECORD A     
  SELECT  DISTINCT C.NAME PAT_NAME,C.BED_NO,C.SEX_NAME,DBO.FUN_ZY_AGE(C.BIRTHDAY,0,GETDATE()) AGE,C.CUR_DEPT_NAME DEPT_NAME,A.*,DBO.FUN_JC_EMPNAME(SQDJCZY) SQDJCZY_NAME,            
   B.YXSSRQ,B.SSTC,B.XSHS,B.XHHS,B.XSHS_NAME,B.XHHS_NAME,E.ROOMID,DBO.FUN_JC_EMPNAME(A.ZDYS) ZDYS_NAME,            
   (CASE WHEN SSYZ_NAME <>'' THEN SSYZ_NAME ELSE '' END)+(CASE WHEN SSEZ_NAME <>'' THEN ','+SSEZ_NAME ELSE '' END)+(CASE WHEN SSSZ_NAME <>'' THEN ','+SSSZ_NAME ELSE '' END) ZS,             
   DBO.FUN_JC_EMPNAME(A.MZYS) MZYS_NAME,DBO.FUN_JC_EMPNAME(A.MZYS1) FMYS_NAME,D.NAME YSMZ_NAME,             
   (CASE WHEN CGZ1_NAME <>'' THEN CGZ1_NAME ELSE '' END)+(CASE WHEN CGZ2_NAME <>''THEN ','+CGZ2_NAME ELSE '' END)+(CASE WHEN CGZ3_NAME <>'' THEN ','+CGZ3_NAME ELSE '' END)+(CASE WHEN CGZ4_NAME <>'' THEN ','+CGZ4_NAME ELSE '' END) CGZ,DBO.FUN_GETDEPTNAME(A.DEPTID) SQKS_NAME,dbo.fun_getEmpName(shys) shysxm,SHRQ   , (   
       CASE WHEN    
       (SELECT COUNT(*) AS num FROM dbo.ZY_FEE_SPECI WHERE DEPT_ID=@SSKS AND INPATIENT_ID = a.INPATIENT_ID)  >0 THEN 0 ELSE 1 END ) isjz    
   ,f.NAME shfjmc    
  ,a.YSSSRQFW FROM SS_APPRECORD A     
  INNER JOIN SS_ARRRECORD B ON A.SNO=B.SNO AND A.INPATIENT_ID=B.INPATIENT_ID AND A.APBJ=1 AND B.BDELETE=0          
  INNER JOIN VI_ZY_VINPATIENT_BED C ON A.INPATIENT_ID=C.INPATIENT_ID AND C.FLAG=3          
  LEFT JOIN SS_ANESTHESIACODE D ON CAST(CASE WHEN B.YSMZ IS NULL OR B.YSMZ='' THEN '-1' ELSE B.YSMZ END AS INT)=D.ID          
  LEFT JOIN SS_ROOMTC E ON B.SSTC=E.ID          
  LEFT JOIN SS_ROOM F ON E.ROOMID=F.ID     
  --WHERE NOT(B.YSMZ IS NULL OR B.YSMZ='0') and B.WCBJ=0
  WHERE NOT(B.YSMZ IS NULL OR B.YSMZ='0') and B.MZWCBJ=0 --Modify By Tany 2015-04-08 麻醉判断麻醉完成标记-- 2012-01-03 Modify by zouchihua --AND A.YSSSRQ>DATEADD(DAY,-15,GETDATE())    
  ORDER BY A.YSSSRQ --ADD BY TANY 2011-05-03    
  --ORDER BY F.ID,B.SSTC    
     
 -- 取消安排的手术-----------------------------------------------------------------------------------------------------------------------------------------------------------------------    
 IF @SIGE=2    
  SELECT DISTINCT A.*,DBO.FUN_JC_EMPNAME(SQDJCZY) SQDJCZY_NAME,B.NAME YSMZ_NAME,C.NAME PAT_NAME,C.BED_NO,C.SEX_NAME,DBO.FUN_ZY_AGE(C.BIRTHDAY,0,GETDATE()) AGE,C.CUR_DEPT_NAME DEPT_NAME,DBO.FUN_JC_EMPNAME(A.ZDYS) ZDYS_NAME,DBO.FUN_JC_EMPNAME(A.MZYS) MZYS_NAME,DBO.FUN_GETDEPTNAME(A.DEPTID) SQKS_NAME,dbo.fun_getEmpName(shys) shysxm,SHRQ   , (   
       CASE WHEN    
       (SELECT COUNT(*) AS num FROM dbo.ZY_FEE_SPECI WHERE DEPT_ID=@SSKS AND INPATIENT_ID = a.INPATIENT_ID)  >0 THEN 0 ELSE 1 END ) isjz    
  FROM SS_APPRECORD A     
  INNER JOIN (SELECT SNO FROM SS_ARRRECORD WHERE  BDELETE=1) D ON A.SNO=D.SNO         
  LEFT JOIN SS_ANESTHESIACODE B ON CAST(A.YSMZ AS INT)=B.ID           
  INNER JOIN VI_ZY_VINPATIENT_BED C ON A.INPATIENT_ID=C.INPATIENT_ID AND C.BABY_ID=0     
  WHERE A.SSDEPT=@SSKS AND A.YSSSRQ>=@DATE1 AND A.YSSSRQ<=@DATE2     
    
 -- 已完成的手术------------------------------------------------------------------------------------------------------------------------------------------------------------------------    
 IF @SIGE=3    
  SELECT DISTINCT A.*,B.YXSS,B.YXMZ,B.SSBEGINRQ,B.SSENDRQ,B.XSHS_NAME,B.XHHS_NAME,DBO.FUN_JC_EMPNAME(A.SQDJCZY) SQDJCZY_NAME, C.NAME PAT_NAME,C.BED_NO,           
  C.SEX_NAME,DBO.FUN_ZY_AGE(C.BIRTHDAY,0,GETDATE()) AGE,C.CUR_DEPT_NAME DEPT_NAME,DBO.FUN_JC_EMPNAME(A.ZDYS) ZDYS_NAME,DBO.FUN_JC_EMPNAME(A.MZYS) MZYS_NAME      
  ,B.QKLX,B.QKYHDJ,DBO.FUN_GETDEPTNAME(A.DEPTID) SQKS_NAME,dbo.fun_getEmpName(shys) shysxm,SHRQ   , (   
       CASE WHEN    
       (SELECT COUNT(*) AS num FROM dbo.ZY_FEE_SPECI WHERE DEPT_ID=@SSKS AND INPATIENT_ID = a.INPATIENT_ID)  >0 THEN 0 ELSE 1 END ) isjz,WCSJ    
  FROM SS_APPRECORD A           
  INNER JOIN SS_ARRRECORD B ON A.SNO=B.SNO AND B.WCBJ=1          
  INNER JOIN VI_ZY_VINPATIENT_BED C ON A.INPATIENT_ID=C.INPATIENT_ID AND C.BABY_ID=0     
  WHERE  A.BDELETE=0 AND A.SSDEPT=@SSKS AND A.YSSSRQ>=@DATE1 AND A.YSSSRQ<=@DATE2    
    
 -- 未麻醉安排的手术------------------------------------------------------------------------------------------------------------------------------------------------------------------------    
 IF @SIGE=4    
  SELECT DISTINCT A.ID,B.SSTC,F.NAME+E.NAME ROOMNAME,A.SNO,A.INPATIENT_NO,CASE WHEN A.SHZD IS NOT NULL THEN A.SHZD ELSE A.SSFZ END ZD,B.YSSS,A.ZDYS,    
   DBO.FUN_JC_EMPNAME(A.ZDYS) ZDYS_NAME,A.YSMZ,D.NAME YSMZ_NAME,B.YSMZ APMZ,B.YXMZ,A.MZYS,DBO.FUN_JC_EMPNAME(A.MZYS) MZYS_NAME,    
   COALESCE(B.YXSSRQ,A.YSSSRQ) YXSSRQ ,A.SSTYS,A.MZTYS,A.SQDJCZY,DBO.FUN_JC_EMPNAME(A.SQDJCZY) SQDJCZY_NAME,B.WCBJ,    
   DBO.FUN_JC_DEPTNAME(A.SSDEPT) SSDEPT,A.INPATIENT_ID,C.NAME PAT_NAME,DBO.FUN_ZY_SEEKSEXNAME(CHAR(C.SEXCODE)) SEX_NAME,DBO.FUN_ZY_AGE(C.BIRTHDAY,0,GETDATE()) AGE,    
   DBO.FUN_JC_DEPTNAME(A.DEPTID) DEPT_NAME,B.WCBJ,A.APBJ,A.JZSS,A.BDELETE,A.SSFZ,A.SSBZ,DBO.FUN_GETDEPTNAME(A.DEPTID) SQKS_NAME,dbo.fun_getEmpName(shys) shysxm,SHRQ  , (   
       CASE WHEN    
       (SELECT COUNT(*) AS num FROM dbo.ZY_FEE_SPECI WHERE DEPT_ID=@SSKS AND INPATIENT_ID = a.INPATIENT_ID)  >0 THEN 0 ELSE 1 END ) isjz    
 ,a.YSSSRQFW FROM SS_APPRECORD A    
  INNER JOIN SS_ARRRECORD B ON A.SNO=B.SNO AND A.INPATIENT_ID=B.INPATIENT_ID AND A.APBJ=1 AND B.BDELETE=0          
  INNER JOIN VI_ZY_VINPATIENT C ON A.INPATIENT_ID=C.INPATIENT_ID AND C.FLAG=3          
  LEFT JOIN SS_ANESTHESIACODE D ON CAST(A.YSMZ AS INT)=D.ID          
  LEFT JOIN SS_ROOMTC E ON B.SSTC=E.ID          
  LEFT JOIN SS_ROOM F ON E.ROOMID=F.ID     
  WHERE (B.YSMZ IS NULL OR B.YSMZ='0') AND A.YSSSRQ>=@DATE1 AND A.YSSSRQ<=@DATE2     
  --ORDER BY F.ID,B.SSTC     
     
 -- 未安排麻醉    
 IF @SIGE=14    
  SELECT DISTINCT A.ID, B.SSTC,F.NAME+E.NAME ROOMNAME,A.SNO,A.INPATIENT_NO,CASE WHEN A.SHZD IS NOT NULL THEN A.SHZD ELSE A.SSFZ END ZD,B.YSSS,A.ZDYS,    
   DBO.FUN_JC_EMPNAME(A.ZDYS) ZDYS_NAME,A.YSMZ,D.NAME YSMZ_NAME,B.YSMZ APMZ,B.YXMZ,A.MZYS,DBO.FUN_JC_EMPNAME(A.MZYS) MZYS_NAME,    
   COALESCE(B.YXSSRQ,A.YSSSRQ) YXSSRQ ,A.SSTYS,A.MZTYS,A.SQDJCZY,DBO.FUN_JC_EMPNAME(A.SQDJCZY) SQDJCZY_NAME,B.WCBJ,    
   DBO.FUN_JC_DEPTNAME(A.SSDEPT) SSDEPT,A.INPATIENT_ID,C.NAME PAT_NAME,DBO.FUN_ZY_SEEKSEXNAME(CHAR(C.SEXCODE)) SEX_NAME,DBO.FUN_ZY_AGE(C.BIRTHDAY,0,GETDATE()) AGE,    
   DBO.FUN_JC_DEPTNAME(A.DEPTID) DEPT_NAME,B.WCBJ,A.APBJ,A.JZSS,A.BDELETE,A.SSFZ,A.SSBZ,A.YSSSRQ,A.SQDJRQ,DBO.FUN_GETDEPTNAME(A.DEPTID) SQKS_NAME ,dbo.fun_getEmpName(shys) shysxm,SHRQ    
  , (   
       CASE WHEN    
       (SELECT COUNT(*) AS num FROM dbo.ZY_FEE_SPECI WHERE DEPT_ID=@SSKS AND INPATIENT_ID = a.INPATIENT_ID)  >0 THEN 0 ELSE 1 END ) isjz     
  ,a.YSSSRQFW FROM SS_APPRECORD A    
  INNER JOIN SS_ARRRECORD B ON A.SNO=B.SNO AND A.INPATIENT_ID=B.INPATIENT_ID AND A.APBJ=1 AND B.BDELETE=0          
  INNER JOIN VI_ZY_VINPATIENT C ON A.INPATIENT_ID=C.INPATIENT_ID AND C.FLAG=3          
  LEFT JOIN SS_ANESTHESIACODE D ON CAST(A.YSMZ AS INT)=D.ID          
  LEFT JOIN SS_ROOMTC E ON B.SSTC=E.ID          
  LEFT JOIN SS_ROOM F ON E.ROOMID=F.ID     
  --WHERE WCBJ=0 AND A.APBJ=1 AND A.BDELETE=0 AND (B.YSMZ IS NULL OR B.YSMZ='0') --AND A.YSSSRQ>DATEADD(DAY,-20,GETDATE())   
  --Modify By Tany 2015-04-08 麻醉判断麻醉完成标记
  WHERE MZWCBJ=0 AND A.APBJ=1 AND A.BDELETE=0 AND (B.YSMZ IS NULL OR B.YSMZ='0') 
  ORDER BY A.YSSSRQ --ADD BY TANY 2011-05-03    
  --ORDER BY F.ID,B.SSTC     
    
 -- 已安排麻醉的手术------------------------------------------------------------------------------------------------------------------------------------------------------------------------    
 IF @SIGE=5    
  SELECT DISTINCT A.ID, A.SNO,A.INPATIENT_NO,CASE WHEN A.SHZD IS NOT NULL THEN A.SHZD ELSE A.SSFZ END ZD,B.YSSS,A.ZDYS,DBO.FUN_JC_EMPNAME(A.ZDYS) ZDYS_NAME,    
   B.YSMZ,D.NAME APMZ,B.YXMZ,A.MZYS,DBO.FUN_JC_EMPNAME(A.MZYS) MZYS_NAME,A.FMYS_NAME,COALESCE(B.YXSSRQ,A.YSSSRQ) YXSSRQ,A.SSTYS,A.MZTYS,    
   A.SQDJCZY,DBO.FUN_JC_EMPNAME(A.SQDJCZY) SQDJCZY_NAME,B.WCBJ,DBO.FUN_JC_DEPTNAME(A.SSDEPT) SSDEPT,A.INPATIENT_ID,C.NAME PAT_NAME,    
   DBO.FUN_ZY_SEEKSEXNAME(CHAR(C.SEXCODE)) SEX_NAME,DBO.FUN_ZY_AGE(C.BIRTHDAY,0,GETDATE()) AGE,DBO.FUN_JC_DEPTNAME(A.DEPTID) DEPT_NAME,B.WCBJ,    
   B.SSTC,F.NAME SSROOM,F.NAME+E.NAME ROOMNAME,A.APBJ,A.JZSS,A.BDELETE,A.SSFZ,A.SSBZ,DBO.FUN_GETDEPTNAME(A.DEPTID) SQKS_NAME ,dbo.fun_getEmpName(shys) shysxm,SHRQ    
   ,dbo.fun_getEmpName(A.mzzds) mzzds  , (   
       CASE WHEN    
       (SELECT COUNT(*) AS num FROM dbo.ZY_FEE_SPECI WHERE DEPT_ID=@SSKS AND INPATIENT_ID = a.INPATIENT_ID)  >0 THEN 0 ELSE 1 END ) isjz    
  ,a.YSSSRQFW FROM SS_APPRECORD A     
  INNER JOIN SS_ARRRECORD B ON A.SNO=B.SNO AND A.INPATIENT_ID=B.INPATIENT_ID AND A.APBJ=1 AND B.BDELETE=0          
  INNER JOIN VI_ZY_VINPATIENT C ON A.INPATIENT_ID=C.INPATIENT_ID AND C.FLAG=3          
  LEFT JOIN SS_ANESTHESIACODE D ON CAST(CASE WHEN B.YSMZ IS NULL OR B.YSMZ='' THEN '-1' ELSE B.YSMZ END AS INT)=D.ID          
  LEFT JOIN SS_ROOMTC E ON B.SSTC=E.ID          
  LEFT JOIN SS_ROOM F ON E.ROOMID=F.ID     
  WHERE NOT(B.YSMZ IS NULL OR B.YSMZ='0') AND A.YSSSRQ>=@DATE1 AND A.YSSSRQ<=@DATE2     
  --ORDER BY F.ID,B.SSTC    
    
    
   --------------------------------------------------------急诊----------------------------------------------------------------------
   IF @SIGE=100   --未安排
  SELECT DISTINCT A.*,DBO.FUN_JC_EMPNAME(SQDJCZY) SQDJCZY_NAME,B.NAME YSMZ_NAME,C.NAME PAT_NAME,C.BED_NO,C.SEX_NAME,DBO.FUN_ZY_AGE(C.BIRTHDAY,0,GETDATE()) AGE,C.CUR_DEPT_NAME DEPT_NAME,DBO.FUN_JC_EMPNAME(A.ZDYS) ZDYS_NAME,'' MZYS_NAME,DBO.FUN_GETDEPTNAME(
  
A.DEPTID) SQKS_NAME,dbo.fun_getEmpName(shys) shysxm,SHRQ , (   
       CASE WHEN    
       (SELECT COUNT(*) AS num FROM dbo.ZY_FEE_SPECI WHERE DEPT_ID=@SSKS AND INPATIENT_ID = a.INPATIENT_ID)  >0 THEN 0 ELSE 1 END ) isjz    
  FROM SS_APPRECORD A        
  LEFT JOIN SS_ANESTHESIACODE B ON CAST(A.YSMZ AS INT)=B.ID           
  INNER JOIN VI_ZY_VINPATIENT_BED C ON A.INPATIENT_ID=C.INPATIENT_ID AND C.BABY_ID=0          
  WHERE (JZSS=1) AND APBJ=0 AND BDELETE=0 AND A.SSDEPT=@SSKS AND YSSSRQ>=@DATE1 AND YSSSRQ<=@DATE2    
     
  
 
   IF @SIGE=111 --已安排 
  SELECT  DISTINCT D.NAME PAT_NAME,D.BED_NO,D.SEX_NAME,DBO.FUN_ZY_AGE(D.BIRTHDAY,0,GETDATE()) AGE,D.CUR_DEPT_NAME DEPT_NAME,A.*,DBO.FUN_JC_EMPNAME(SQDJCZY) SQDJCZY_NAME,            
   B.SSTC,B.XSHS,B.XHHS,B.XSHS_NAME,B.XHHS_NAME,C.ROOMID,DBO.FUN_JC_EMPNAME(A.ZDYS) ZDYS_NAME,            
   (ISNULL(dbo.fun_getEmpName(SSYZ),''))+(ISNULL(dbo.fun_getEmpName(SSEZ),''))+(isnull(dbo.fun_getEmpName(SSSZ),'')) ZS,             
   DBO.FUN_JC_EMPNAME(A.MZYS) MZYS_NAME,DBO.FUN_JC_EMPNAME(A.MZYS1) FMYS_NAME,E.NAME YSMZ_NAME,             
   (CASE WHEN CGZ1_NAME <>'' THEN CGZ1_NAME ELSE '' END)+(CASE WHEN CGZ2_NAME <>''THEN ','+CGZ2_NAME ELSE '' END)+(CASE WHEN CGZ3_NAME <>'' THEN ','+CGZ3_NAME ELSE '' END)+(CASE WHEN CGZ4_NAME <>'' THEN ','+CGZ4_NAME ELSE '' END) CGZ,DBO.FUN_GETDEPTNAME(A.DEPTID) SQKS_NAME,dbo.fun_getEmpName(shys) shysxm,SHRQ     
   , dbo.fun_getEmpName(SSYZ) SSYZ_NAME,dbo.fun_getEmpName(SSEZ) SSEZ_NAME,  f.NAME ,ssbz  , (   
       CASE WHEN    
       (SELECT COUNT(*) AS num FROM dbo.ZY_FEE_SPECI WHERE DEPT_ID=@SSKS AND INPATIENT_ID = a.INPATIENT_ID)  >0 THEN 0 ELSE 1 END ) isjz    
  FROM SS_APPRECORD A     
  INNER JOIN (SELECT * FROM SS_ARRRECORD WHERE WCBJ=0 AND BDELETE=0) B ON A.SNO=B.SNO      
  LEFT JOIN  SS_ROOMTC C ON B.SSTC=C.ID     
  left join SS_ROOM f on C.ROOMID=f.ID    
  LEFT JOIN  VI_ZY_VINPATIENT_BED D ON A.INPATIENT_ID=D.INPATIENT_ID AND D.BABY_ID=0          
  LEFT JOIN SS_ANESTHESIACODE E ON CAST(A.YSMZ AS INT)=E.ID     
  WHERE A.APBJ=1 AND A.BDELETE=0 AND A.SSDEPT=@SSKS  AND A.YSSSRQ>=@DATE1 AND A.YSSSRQ<=@DATE2 and JZSS=1    
  ORDER BY A.YSSSRQ --ADD BY TANY 2011-05-03    
  --ORDER BY C.ROOMID  
  
   IF @SIGE=222  --已取消
  SELECT DISTINCT A.*,DBO.FUN_JC_EMPNAME(SQDJCZY) SQDJCZY_NAME,B.NAME YSMZ_NAME,C.NAME PAT_NAME,C.BED_NO,C.SEX_NAME,DBO.FUN_ZY_AGE(C.BIRTHDAY,0,GETDATE()) AGE,C.CUR_DEPT_NAME DEPT_NAME,DBO.FUN_JC_EMPNAME(A.ZDYS) ZDYS_NAME,DBO.FUN_JC_EMPNAME(A.MZYS) MZYS_NAME,DBO.FUN_GETDEPTNAME(A.DEPTID) SQKS_NAME,dbo.fun_getEmpName(shys) shysxm,SHRQ   , (   
       CASE WHEN    
       (SELECT COUNT(*) AS num FROM dbo.ZY_FEE_SPECI WHERE DEPT_ID=@SSKS AND INPATIENT_ID = a.INPATIENT_ID)  >0 THEN 0 ELSE 1 END ) isjz    
  FROM SS_APPRECORD A     
  INNER JOIN (SELECT SNO FROM SS_ARRRECORD WHERE  BDELETE=1) D ON A.SNO=D.SNO         
  LEFT JOIN SS_ANESTHESIACODE B ON CAST(A.YSMZ AS INT)=B.ID           
  INNER JOIN VI_ZY_VINPATIENT_BED C ON A.INPATIENT_ID=C.INPATIENT_ID AND C.BABY_ID=0     
  WHERE A.SSDEPT=@SSKS AND A.YSSSRQ>=@DATE1 AND A.YSSSRQ<=@DATE2 and JZSS=1     
       
   IF @SIGE=333    
  SELECT DISTINCT A.*,B.YXSS,B.YXMZ,B.SSBEGINRQ,B.SSENDRQ,B.XSHS_NAME,B.XHHS_NAME,DBO.FUN_JC_EMPNAME(A.SQDJCZY) SQDJCZY_NAME, C.NAME PAT_NAME,C.BED_NO,           
  C.SEX_NAME,DBO.FUN_ZY_AGE(C.BIRTHDAY,0,GETDATE()) AGE,C.CUR_DEPT_NAME DEPT_NAME,DBO.FUN_JC_EMPNAME(A.ZDYS) ZDYS_NAME,DBO.FUN_JC_EMPNAME(A.MZYS) MZYS_NAME      
  ,B.QKLX,B.QKYHDJ,DBO.FUN_GETDEPTNAME(A.DEPTID) SQKS_NAME,dbo.fun_getEmpName(shys) shysxm,SHRQ   , (   
       CASE WHEN    
       (SELECT COUNT(*) AS num FROM dbo.ZY_FEE_SPECI WHERE DEPT_ID=@SSKS AND INPATIENT_ID = a.INPATIENT_ID)  >0 THEN 0 ELSE 1 END ) isjz,WCSJ    
  FROM SS_APPRECORD A           
  INNER JOIN SS_ARRRECORD B ON A.SNO=B.SNO AND B.WCBJ=1          
  INNER JOIN VI_ZY_VINPATIENT_BED C ON A.INPATIENT_ID=C.INPATIENT_ID AND C.BABY_ID=0     
  WHERE  A.BDELETE=0 AND A.SSDEPT=@SSKS AND A.YSSSRQ>=@DATE1 AND A.YSSSRQ<=@DATE2 and JZSS=1 
    
END    
    
    
    
    
GO


