IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SP_ZYHS_GETBININFO]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SP_ZYHS_GETBININFO]
GO
create PROCEDURE [dbo].[SP_ZYHS_GETBININFO]    
 (    
  @BINID UNIQUEIDENTIFIER,     
  @BABYID INT,     
  @ISMY SMALLINT=0    
 )     
AS    
/*--------------------------------------------------------------------------    
作者：TANY    
说明：住院护士站-查询病人信息    
日期：2006-12-05    
参数：    
      @BINID 病人ID,     
      @BABYID 婴儿ID,     
      @ISMY   是否母婴    
修改：    
    
--------------------------------------------------------------------------*/    
SET NOCOUNT ON    
    
--查询费用(不是母婴)    
IF @ISMY=0    
BEGIN    
    
	CREATE TABLE #FEE0    
	(    
	 INPATIENT_ID UNIQUEIDENTIFIER,    
	 ZFY          DECIMAL(18,2),    
	 YPZFY        DECIMAL(18,2),    
	 WJSZFY       DECIMAL(18,2),    
	 YJK          DECIMAL(18,2),    
	 WDZYJK       DECIMAL(18,2)    
	)    
	    
	INSERT INTO #FEE0    
	SELECT INPATIENT_ID,ACVALUE,    
		   CASE  WHEN STATITEM_CODE IN ('01','02','03') THEN ACVALUE ELSE 0 END,    
		   CASE DISCHARGE_BIT WHEN 0 THEN ACVALUE ELSE 0 END,0,0    
	FROM ZY_FEE_SPECI    
	WHERE CHARGE_BIT=1 AND DELETE_BIT=0    
		  AND INPATIENT_ID=@BINID AND BABY_ID=@BABYID    
	UNION ALL    
	SELECT INPATIENT_ID,0,0,0,    
		   CASE ARRIVE_BIT WHEN 1 THEN NVALUES ELSE 0 END,    
		   CASE ARRIVE_BIT WHEN 0 THEN NVALUES ELSE 0 END    
	FROM ZY_DEPOSITS    
	WHERE CANCEL_BIT<>1 AND DISCHARGE_BIT<>1    
		  AND INPATIENT_ID=@BINID    
	    
	SELECT  A.DEPT_ID,A.BED_ID,A.ROOM_NO,A.BED_NO,A.INPATIENT_ID,A.BABY_ID,    
	 A.INPATIENT_NO,A.NAME,A.TIMES,A.BIRTHDAY,A.RYZD IN_DIAGNOSIS,--modify by zouchihua 
	 --DBO.FUN_GETDATE(A.IN_DATE) IN_DATE,DBO.FUN_GETDATE(A.OUT_DATE) OUT_DATE,A.DISCHARGETYPE,A.FLAG,
	 --Modify By Tany 2010-09-29 入院和出院时间还是给长时间格式   
	 A.IN_DATE,A.OUT_DATE,A.DISCHARGETYPE,A.FLAG, 
	 A.SEX_NAME,A.JSFS_NAME,A.TENDLEVEL,A.HLJB_NAME,A.ORDER_BW,A.ORDER_BZ,A.ORDER_YS,A.ORDER_YS_SPEC,    
	 A.ZZDOC_NAME,A.ZYDOC_NAME,A.NURS_NAME,    
	 A.IN_DEPT_NAME,A.CUR_DEPT_NAME,    
	 A.AGE,A.RYTS,    
	 CASE WHEN B.ZFY IS NULL THEN 0 ELSE B.ZFY END ZFY,    
	 CASE WHEN B.YPZFY IS NULL THEN 0 ELSE B.YPZFY END YPZFY,    
	 CASE WHEN B.WJSZFY IS NULL THEN 0 ELSE B.WJSZFY END WJSZFY,    
	 CASE WHEN B.YJK IS NULL THEN 0 ELSE B.YJK END YJK,    
	 CASE WHEN B.WDZYJK IS NULL THEN 0 ELSE B.WDZYJK END WDZYJK,    
	 CASE WHEN B.YE IS NULL THEN 0 ELSE B.YE END YE,    
	 0 AS GRZFY,0 AS GRWJSZFY,    
	 @ISMY AS ISMY,A.YBYE,CASE A.BABY_ID WHEN 0 THEN A.SICKDESCRIPTION ELSE '' END SICKDESCRIPTION,    
	 A.YBLX,A.YBLX_NAME,A.BRLX,A.BRLX_NAME,A.DBJE,INSUREACCOUNT,A.XZLX_NAME,A.DYLX_NAME,
	 ISNULL(D.FYXZ,0) FYXZ,E.YBJS_DATE,E.ZFY YBZFY,E.TCZF,E.ZHZF,E.XJZF,E.QTZF,D.RYSH_BZ,D.CYSH_BZ,A.YJJ_LIMIT
	 , case when  (select COUNT(1) from ZY_ORDERRECORD where INPATIENT_ID=A.INPATIENT_ID and BABY_ID=A.BABY_ID and (ORDER_CONTEXT like '%陪护%' OR ORDER_CONTEXT like '%陪人%' )
	      AND  MNGTYPE=0 AND STATUS_FLAG=2    AND DELETE_BIT=0)=0 then '' else '陪护' end as order_ph,   --add by zouchihua 2013-8-1 增加陪人陪护
	 A.INPATIENT_BANO --Add By Tany 2015-04-23 增加病案号
	FROM VI_ZY_VINPATIENT_ALL A    
	LEFT JOIN    
	(SELECT INPATIENT_ID,CASE WHEN SUM(ZFY) IS NULL THEN 0 ELSE SUM(ZFY) END AS ZFY,    
	 CASE WHEN SUM(YPZFY) IS NULL THEN 0 ELSE SUM(YPZFY) END AS YPZFY,    
	 CASE WHEN SUM(WJSZFY) IS NULL THEN 0 ELSE SUM(WJSZFY) END AS WJSZFY,    
	 CASE WHEN SUM(YJK) IS NULL THEN 0 ELSE SUM(YJK) END AS YJK,    
	 CASE WHEN SUM(WDZYJK) IS NULL THEN 0 ELSE SUM(WDZYJK) END AS WDZYJK,    
	 CASE WHEN SUM(YJK-WJSZFY) IS NULL THEN 0 ELSE SUM(YJK-WJSZFY) END AS YE    
	 FROM #FEE0     
	 GROUP BY INPATIENT_ID    
	) B ON A.INPATIENT_ID=B.INPATIENT_ID
	LEFT JOIN JC_DISEASE C ON A.IN_DIAGNOSIS=C.CODING AND ISNULL(A.YBJKLX,0)=C.YBJKLX
	LEFT JOIN ZY_YB_SHXX D ON A.INPATIENT_ID=D.INPATIENT_ID --AND D.DELETE_BIT=0
	LEFT JOIN ZY_YB_JSB_RJJL E ON A.INPATIENT_ID=E.INPATIENT_ID AND E.DELETE_BIT=0
	WHERE A.INPATIENT_ID=@BINID AND A.BABY_ID=@BABYID    
    
END    
    
--查询费用(含个人)    
IF @ISMY>=1    
BEGIN    
    
	CREATE TABLE #FEE1    
	(    
	 INPATIENT_ID UNIQUEIDENTIFIER,    
	 ZFY          DECIMAL(18,2),    
	 YPZFY        DECIMAL(18,2),    
	 WJSZFY       DECIMAL(18,2),    
	 GRZFY        DECIMAL(18,2),    
	 GRWJSZFY     DECIMAL(18,2),    
	 YJK          DECIMAL(18,2),    
	 WDZYJK       DECIMAL(18,2)    
	)    
	    
	INSERT INTO #FEE1    
	SELECT INPATIENT_ID,ACVALUE,    
	 CASE  WHEN STATITEM_CODE IN ('01','02','03') THEN ACVALUE ELSE 0 END,    
	 CASE DISCHARGE_BIT WHEN 0 THEN ACVALUE ELSE 0 END,0,0,0,0    
	FROM ZY_FEE_SPECI    
	WHERE CHARGE_BIT=1  AND DELETE_BIT=0    
		  AND INPATIENT_ID=@BINID    
	UNION ALL    
	SELECT INPATIENT_ID,0,0,0,ACVALUE,    
	 CASE DISCHARGE_BIT WHEN 0 THEN ACVALUE ELSE 0 END,0,0    
	FROM ZY_FEE_SPECI    
	WHERE CHARGE_BIT=1  AND DELETE_BIT=0    
		  AND INPATIENT_ID=@BINID AND BABY_ID=@BABYID    
	UNION ALL    
	SELECT INPATIENT_ID,0,0,0,0,0,    
	 CASE ARRIVE_BIT WHEN 1 THEN NVALUES ELSE 0 END,    
	 CASE ARRIVE_BIT WHEN 0 THEN NVALUES ELSE 0 END    
	FROM ZY_DEPOSITS    
	WHERE CANCEL_BIT<>1 AND DISCHARGE_BIT<>1    
		  AND INPATIENT_ID=@BINID    
	    
	SELECT A.DEPT_ID,A.BED_ID,A.ROOM_NO,A.BED_NO,A.INPATIENT_ID,A.BABY_ID,    
	 A.INPATIENT_NO,A.NAME,A.TIMES,A.BIRTHDAY,A.RYZD IN_DIAGNOSIS, --modify by zouchihua   
	 --DBO.FUN_GETDATE(A.IN_DATE) IN_DATE,A.DISCHARGETYPE,A.FLAG,   
	 --Modify By Tany 2010-09-29 入院和出院时间还是给长时间格式   
	 A.IN_DATE,A.OUT_DATE,A.DISCHARGETYPE,A.FLAG,  
	 A.SEX_NAME,A.JSFS_NAME,A.TENDLEVEL,A.HLJB_NAME,A.ORDER_BW,A.ORDER_BZ,A.ORDER_YS,A.ORDER_YS_SPEC,    
	 A.ZZDOC_NAME,A.ZYDOC_NAME,A.NURS_NAME,    
	 A.IN_DEPT_NAME,A.CUR_DEPT_NAME,    
	 A.AGE,A.RYTS,    
	 CASE WHEN B.ZFY IS NULL THEN 0 ELSE B.ZFY END ZFY,    
	 CASE WHEN B.YPZFY IS NULL THEN 0 ELSE B.YPZFY END YPZFY,    
	 CASE WHEN B.WJSZFY IS NULL THEN 0 ELSE B.WJSZFY END WJSZFY,    
	 CASE WHEN B.YJK IS NULL THEN 0 ELSE B.YJK END YJK,    
	 CASE WHEN B.WDZYJK IS NULL THEN 0 ELSE B.WDZYJK END WDZYJK,    
	 CASE WHEN B.YE IS NULL THEN 0 ELSE B.YE END YE,    
	 CASE WHEN B.GRZFY IS NULL THEN 0 ELSE B.GRZFY END GRZFY,    
	 CASE WHEN B.GRWJSZFY IS NULL THEN 0 ELSE B.GRWJSZFY END GRWJSZFY,    
	 @ISMY AS ISMY,A.YBYE,CASE A.BABY_ID WHEN 0 THEN A.SICKDESCRIPTION ELSE '' END SICKDESCRIPTION,    
	 A.YBLX,A.YBLX_NAME,A.BRLX,A.BRLX_NAME,A.DBJE  ,INSUREACCOUNT,A.XZLX_NAME,A.DYLX_NAME,
	 ISNULL(D.FYXZ,0) FYXZ,E.YBJS_DATE,E.ZFY YBZFY,E.TCZF,E.ZHZF,E.XJZF,E.QTZF,D.RYSH_BZ,D.CYSH_BZ,A.YJJ_LIMIT,
	 case when  (select COUNT(1) from ZY_ORDERRECORD where INPATIENT_ID=A.INPATIENT_ID and BABY_ID=A.BABY_ID and (ORDER_CONTEXT like '%陪护%' OR ORDER_CONTEXT like '%陪人%' )
	      AND  MNGTYPE=0 AND STATUS_FLAG=2    AND DELETE_BIT=0)=0 then '' else '陪护' end as order_ph,   --add by zouchihua 2013-8-1 增加陪人陪护
	 A.INPATIENT_BANO --Add By Tany 2015-04-23 增加病案号
	FROM  VI_ZY_VINPATIENT_ALL A    
	LEFT JOIN    
	(SELECT INPATIENT_ID,CASE WHEN SUM(ZFY) IS NULL THEN 0 ELSE SUM(ZFY) END AS ZFY,    
	 CASE WHEN SUM(YPZFY) IS NULL THEN 0 ELSE SUM(YPZFY) END AS YPZFY,    
	 CASE WHEN SUM(WJSZFY) IS NULL THEN 0 ELSE SUM(WJSZFY) END AS WJSZFY,    
	 CASE WHEN SUM(YJK) IS NULL THEN 0 ELSE SUM(YJK) END AS YJK,    
	 CASE WHEN SUM(WDZYJK) IS NULL THEN 0 ELSE SUM(WDZYJK) END AS WDZYJK,    
	 CASE WHEN SUM(YJK-WJSZFY) IS NULL THEN 0 ELSE SUM(YJK-WJSZFY) END AS YE,    
	 CASE WHEN SUM(GRZFY) IS NULL THEN 0 ELSE SUM(GRZFY) END AS GRZFY,    
	 CASE WHEN SUM(GRWJSZFY) IS NULL THEN 0 ELSE SUM(GRWJSZFY) END AS GRWJSZFY    
	FROM #FEE1    
	GROUP BY INPATIENT_ID    
	) B ON A.INPATIENT_ID=B.INPATIENT_ID  
	LEFT JOIN JC_DISEASE C ON A.IN_DIAGNOSIS=C.CODING AND ISNULL(A.YBJKLX,0)=C.YBJKLX
	LEFT JOIN ZY_YB_SHXX D ON A.INPATIENT_ID=D.INPATIENT_ID --AND D.DELETE_BIT=0  
	LEFT JOIN ZY_YB_JSB_RJJL E ON A.INPATIENT_ID=E.INPATIENT_ID AND E.DELETE_BIT=0
	WHERE A.INPATIENT_ID=@BINID AND A.BABY_ID=@BABYID    
    
END    
    
    
    


GO


