/****** Object:  StoredProcedure [dbo].[SP_ZYHS_ORDERS_SELECT]    Script Date: 03/24/2015 09:26:49 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SP_ZYHS_ORDERS_SELECT]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SP_ZYHS_ORDERS_SELECT]
GO

/****** Object:  StoredProcedure [dbo].[SP_ZYHS_ORDERS_SELECT]    Script Date: 03/24/2015 09:26:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create PROCEDURE [dbo].[SP_ZYHS_ORDERS_SELECT]
 (
  @BINID UNIQUEIDENTIFIER, 
  @BABYID BIGINT, 
  @SELTYPE INT, 
  @SELKIND INT, 
  @DOC BIGINT, 
  @EXECDATE DATETIME, 
  @WARDID VARCHAR(4),
  @DEPTID BIGINT --0=全部 Modify By tany 增加科室，如果是特殊治疗科室，只能看见自己的
 ) 
AS
/*--------------------------------------------------------------------------
作者：TANY
说明：住院护士站-查询医嘱
日期：2006-12-09
参数：
  @BINID BIGINT, 
  @BABYID INT, 
  @SELTYPE 医嘱类型 0=长嘱、长期帐单 1=临嘱、临时帐单
  @SELKIND 类型 0=有效 1=所有 2=所有未发送的医嘱
  @DOC BIGINT, 
  @EXECDATE DATETIME, 
  @WARDID 
修改：
  2007-01-31 临时医嘱增加费用查询,DBO.FUN_ZY_GETORDERFEE(ORDER_ID) 费用，显示医嘱产生的费用
  2007-08-27 屏蔽上面功能，速度太慢
  2010-09-02 发送时间用EXECDATE来显示
  2011-01-21 DEL_PRINT P 增加是否在医嘱打印中显示
--------------------------------------------------------------------------*/
SET NOCOUNT ON

DECLARE @SELTYPE2 INT --判断两种类型
declare @ISSHowSS int --add by zouchihua 是否显示手术室病人医嘱
set @ISSHowSS =CAST( ISNULL(( select top 1 CONFIG  from jc_config where id=7148),0) as int)
declare @zcyxsmc varchar
set @zcyxsmc=(select top 1 isnull(config,0) from JC_CONFIG where ID=6070)
--如果是临时医嘱，还要加上类型=5的交病人临嘱
IF @SELTYPE=1
   SET @SELTYPE2=5
ELSE
   SET @SELTYPE2=@SELTYPE

--有效
IF @SELKIND=0
BEGIN
    --有效临嘱（临嘱单独出来主要是草药）
    IF @SELTYPE=1

       SELECT *--,DBO.FUN_ZY_GETORDERFEE(ORDER_ID) 费用 
       FROM 
       (SELECT A.STATUS_FLAG,A.ORDER_ID,A.GROUP_ID,A.NUM,
        case when  ISNUMERIC (LEFT(A.UNIT,1))>0 then '['+A.UNIT +']' else  A.UNIT end UNIT,
       A.DWLX,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,A.DOSAGE,
	       A.NTYPE,A.EXEC_DEPT,CONVERT(CHAR,DATEPART(DD,A.ORDER_BDATE)) DAY1,CONVERT(CHAR,DATEPART(MI,A.ORDER_BDATE)) SECOND1,CONVERT(CHAR,DATEPART(DD,A.ORDER_EDATE)) DAY2 ,CONVERT(CHAR,DATEPART(MI,A.ORDER_EDATE)) SECOND2,
           AUDITING_USER,AUDITING_USER1,ORDER_EUSER,ORDER_EUSER1,CASE WHEN NTYPE<=3 AND NTYPE<>0 THEN A.ITEM_CODE ELSE CONVERT(CHAR,A.HOITEM_ID) END ITEM_CODE,XMLY,HOITEM_ID,
	       CONVERT(CHAR,DATEPART(MM,A.ORDER_BDATE)) 开日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_BDATE)) 开时间,
	       LTRIM(RTRIM(A.ORDER_CONTEXT))+CASE WHEN ISNULL(ORDER_SPEC,'')='' THEN '' ELSE '('+LTRIM(RTRIM(ORDER_SPEC))+')' END 医嘱内容,E1.NAME 开嘱医生,E2.NAME 开嘱转抄,E3.NAME 开嘱核对,
	       CONVERT(CHAR,DATEPART(MM,A.ORDER_EDATE)) 停日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_EDATE)) 停时间,
	       E4.NAME 停嘱医生,E5.NAME 停嘱转抄,E6.NAME 停嘱核对,
	       B.EXECDATE 发送时间,E7.NAME 发送护士,D1.NAME 执行科室,A.SERIAL_NO,
	       PS_FLAG,PS_ORDERID,PS_USER,WZX_FLAG,ORDER_BDATE,B.REALEXECDATE 执行时间,rtrim(E8.NAME)+' '+isnull(dbo.fun_getEmpName(ISNULL(REALEXEUSERDb,-1)),'') 执行人,DEL_PRINT P --Add by Tany 2011-01-21
	       ,isnull(isprintypgg,0) isprintypgg,ORDER_SPEC,REALEXEUSERDb ,REALEXEUSER,A.ts,A.zsl,A.zsldw --add by zouchihua 2011-11-30
	FROM ZY_ORDERRECORD A
	LEFT JOIN
	(SELECT DISTINCT X.ORDER_ID,X.EXEUSER,X.EXECDATE,X.REALEXECDATE,X.REALEXEUSER,X.BOOK_DATE,X.REALEXEUSERDb
         FROM (SELECT * FROM ZY_ORDEREXEC WHERE INPATIENT_ID = @BINID AND BABY_ID = @BABYID) X
--		,(SELECT ORDER_ID,MAX(EXECDATE)  EXECDATE FROM ZY_ORDEREXEC WHERE INPATIENT_ID = @BINID AND BABY_ID = @BABYID GROUP BY ORDER_ID) Y
--         WHERE X.ORDER_ID=Y.ORDER_ID AND X.EXECDATE=Y.EXECDATE
	) B
    ON A.ORDER_ID=B.ORDER_ID AND A.LASTEXECDATE=B.EXECDATE
	LEFT JOIN JC_EMPLOYEE_PROPERTY E1 ON A.ORDER_DOC=E1.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E2 ON A.AUDITING_USER=E2.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E3 ON A.AUDITING_USER1=E3.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E4 ON A.ORDER_EDOC=E4.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E5 ON A.ORDER_EUSER=E5.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E6 ON A.ORDER_EUSER1=E6.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E7 ON B.EXEUSER=E7.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E8 ON B.REALEXEUSER=E8.EMPLOYEE_ID
	LEFT JOIN JC_DEPT_PROPERTY D1 ON A.EXEC_DEPT=D1.DEPT_ID
--	LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1
	WHERE (A.MNGTYPE=@SELTYPE OR A.MNGTYPE=@SELTYPE2)
              AND ( (@ISSHowSS=0 and  A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT)) or  @ISSHowSS=1 or @DEPTID in(SELECT DEPTID FROM SS_DEPT)   )--Modify by zouchihua  解决特殊治疗到手术室
              AND (A.INPATIENT_ID = @BINID) AND (A.BABY_ID = @BABYID)
              AND (A.DELETE_BIT = 0)
              AND ( (A.STATUS_FLAG > 1 AND A.STATUS_FLAG < 5)) -- OR (A.STATUS_FLAG = 5 AND DATE(A.ORDER_EDATE)=CURRENT DATE) )
              AND A.NTYPE<>3 AND (@DEPTID=0 OR A.DEPT_ID=@DEPTID)
        UNION ALL
        SELECT A.STATUS_FLAG,DBO.FUN_GETEMPTYGUID(),A.GROUP_ID,A.DOSAGE,'付',-1,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,A.DOSAGE,
		A.NTYPE,A.EXEC_DEPT,CONVERT(CHAR,DATEPART(DD,A.ORDER_BDATE)) DAY1,CONVERT(CHAR,DATEPART(MI,A.ORDER_BDATE)) SECOND1,CONVERT(CHAR,DATEPART(DD,A.ORDER_EDATE)) DAY2 ,CONVERT(CHAR,DATEPART(MI,A.ORDER_EDATE)) SECOND2,
		AUDITING_USER,AUDITING_USER1,ORDER_EUSER,ORDER_EUSER1, 'ZY',-1,1,
		CONVERT(CHAR,DATEPART(MM,A.ORDER_BDATE)) 开日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_BDATE)) 开时间,
		'中草药处方'+
			case when @zcyxsmc='0' then '' else  (case when rtrim(isnull(A.MEMO,''))!=''   then '【'+isnull(A.MEMO,'')+'】' else isnull((select top 1 '【'+MBMC+'】' from  jc_cfmb where MBXH=A.PS_ORDERID),'') end  )   end
			 医嘱内容,
		E1.NAME 开嘱医生,E2.NAME 开嘱转抄,E3.NAME 开嘱核对,
		CONVERT(CHAR,DATEPART(MM,A.ORDER_EDATE)) 停日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_EDATE)) 停时间,
		E4.NAME 停嘱医生,E5.NAME 停嘱转抄,E6.NAME 停嘱核对,
		B.EXECDATE 发送时间,E7.NAME 发送护士,D1.NAME 执行科室,0,
		0,DBO.FUN_GETEMPTYGUID(),0,WZX_FLAG,ORDER_BDATE,B.REALEXECDATE 执行时间,rtrim(E8.NAME)+' '+isnull(dbo.fun_getEmpName(ISNULL(REALEXEUSERDb,-1)),'') 执行人,CAST(DEL_PRINT AS SMALLINT) P --Add by Tany 2011-01-21
		 ,0 isprintypgg ,'' ORDER_SPEC, REALEXEUSERDb,REALEXEUSER ,A.ts,null zsl,null zsldw--add by zouchihua 2011-11-30
        FROM (SELECT * FROM ZY_ORDERRECORD A 
	      WHERE (A.MNGTYPE=@SELTYPE OR A.MNGTYPE=@SELTYPE2)
			AND (  (@ISSHowSS=0 and  A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT)) or @ISSHowSS=1 or @DEPTID in(SELECT DEPTID FROM SS_DEPT)   )--Modify by zouchihua  解决特殊治疗到手术室
			AND (A.INPATIENT_ID = @BINID) AND (A.BABY_ID = @BABYID)
			AND (A.DELETE_BIT = 0)
			AND ( (A.STATUS_FLAG > 1 AND A.STATUS_FLAG < 5))-- OR (A.STATUS_FLAG = 5 AND DATE(A.ORDER_EDATE)=CURRENT DATE) )
			AND A.NTYPE=3 AND (@DEPTID=0 OR A.DEPT_ID=@DEPTID)) A
        LEFT JOIN
	(SELECT DISTINCT X.ORDER_ID,X.EXEUSER,X.EXECDATE,X.REALEXECDATE,X.REALEXEUSER,X.BOOK_DATE,X.REALEXEUSERDb
         FROM (SELECT * FROM ZY_ORDEREXEC WHERE INPATIENT_ID = @BINID AND BABY_ID = @BABYID) X
--		,(SELECT ORDER_ID,MAX(EXECDATE)  EXECDATE FROM ZY_ORDEREXEC WHERE INPATIENT_ID = @BINID AND BABY_ID = @BABYID GROUP BY ORDER_ID) Y
--         WHERE X.ORDER_ID=Y.ORDER_ID AND X.EXECDATE=Y.EXECDATE
	) B
    ON A.ORDER_ID=B.ORDER_ID AND A.LASTEXECDATE=B.EXECDATE
	LEFT JOIN JC_EMPLOYEE_PROPERTY E1 ON A.ORDER_DOC=E1.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E2 ON A.AUDITING_USER=E2.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E3 ON A.AUDITING_USER1=E3.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E4 ON A.ORDER_EDOC=E4.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E5 ON A.ORDER_EUSER=E5.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E6 ON A.ORDER_EUSER1=E6.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E7 ON B.EXEUSER=E7.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E8 ON B.REALEXEUSER=E8.EMPLOYEE_ID
	LEFT JOIN JC_DEPT_PROPERTY D1 ON A.EXEC_DEPT=D1.DEPT_ID
        GROUP BY A.STATUS_FLAG,A.GROUP_ID,A.DOSAGE,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,A.DOSAGE,
		A.NTYPE,A.EXEC_DEPT,A.ORDER_BDATE,A.ORDER_EDATE,
		AUDITING_USER,AUDITING_USER1,ORDER_EUSER,ORDER_EUSER,
		A.ORDER_DOC,A.AUDITING_USER,AUDITING_USER1,
		A.ORDER_EDATE,A.ORDER_EDATE,
		ORDER_EDOC,ORDER_EUSER,ORDER_EUSER1,
		B.EXECDATE,B.EXEUSER,A.EXEC_DEPT,WZX_FLAG,B.REALEXECDATE,B.BOOK_DATE,
		E1.NAME,E2.NAME,E3.NAME,E4.NAME,E5.NAME,E6.NAME,E7.NAME,E8.NAME,D1.NAME ,REALEXEUSERDb,REALEXEUSER,DEL_PRINT
		,A.ts--,A.zsl,A.zsldw
		,A.MEMO,A.PS_ORDERID
        ) TMP 
        ORDER BY ORDER_BDATE,GROUP_ID,SERIAL_NO
 
    --有效长嘱和长期、临时帐单
    ELSE  
       
	SELECT A.STATUS_FLAG,A.ORDER_ID,A.GROUP_ID,A.NUM,
	case when  ISNUMERIC (LEFT(A.UNIT,1))>0 then '['+A.UNIT +']' else  A.UNIT end UNIT,
	A.DWLX,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,A.DOSAGE,
		A.NTYPE,A.EXEC_DEPT,CONVERT(CHAR,DATEPART(DD,A.ORDER_BDATE)) DAY1,CONVERT(CHAR,DATEPART(MI,A.ORDER_BDATE)) SECOND1,CONVERT(CHAR,DATEPART(DD,A.ORDER_EDATE)) DAY2 ,CONVERT(CHAR,DATEPART(MI,A.ORDER_EDATE)) SECOND2,
		AUDITING_USER,AUDITING_USER1,ORDER_EUSER,ORDER_EUSER1,CASE WHEN NTYPE<=3 AND NTYPE<>0 THEN A.ITEM_CODE ELSE CONVERT(CHAR,A.HOITEM_ID) END ITEM_CODE,A.XMLY,A.HOITEM_ID,
		CONVERT(CHAR,DATEPART(MM,A.ORDER_BDATE)) 开日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_BDATE)) 开时间,
		LTRIM(RTRIM(A.ORDER_CONTEXT))+CASE WHEN ISNULL(ORDER_SPEC,'')='' THEN '' ELSE '('+LTRIM(RTRIM(ORDER_SPEC))+')' END 医嘱内容,E1.NAME 开嘱医生,E2.NAME 开嘱转抄,E3.NAME 开嘱核对,
		CASE WHEN A.STATUS_FLAG<4 THEN '' ELSE CONVERT(CHAR,DATEPART(MM,A.ORDER_EDATE)) END 停日期,CASE WHEN A.STATUS_FLAG<4 THEN '' ELSE CONVERT(CHAR,DATEPART(HH,A.ORDER_EDATE)) END 停时间,
		CASE WHEN A.STATUS_FLAG<4 THEN '' ELSE E4.NAME END 停嘱医生,E5.NAME 停嘱转抄,E6.NAME 停嘱核对,
		B.EXECDATE 发送时间,E7.NAME 发送护士,D1.NAME 执行科室,A.SERIAL_NO,
		PS_FLAG,PS_ORDERID,PS_USER,WZX_FLAG,ORDER_BDATE,B.REALEXECDATE 执行时间,rtrim(E8.NAME)+' '+isnull(isnull(dbo.fun_getEmpName(ISNULL(REALEXEUSERDb,-1)),''),'') 执行人,DEL_PRINT P --Add by Tany 2011-01-21--,CASE WHEN @SELTYPE=3 THEN DBO.FUN_ZY_GETORDERFEE(A.ORDER_ID) ELSE 0 END 费用
		 ,isnull(isprintypgg,0) isprintypgg,ORDER_SPEC ,REALEXEUSERDb ,REALEXEUSER,A.ts,A.zsl,A.zsldw--add by zouchihua 2011-11-30
	FROM (SELECT * FROM ZY_ORDERRECORD A
	WHERE (A.MNGTYPE=@SELTYPE OR A.MNGTYPE=@SELTYPE2)
		AND (  (@ISSHowSS=0 and A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT)) or @ISSHowSS=1 or @DEPTID in(SELECT DEPTID FROM SS_DEPT)   )--Modify by zouchihua  解决特殊治疗到手术室
		AND (A.INPATIENT_ID = @BINID) AND (A.BABY_ID = @BABYID)
		AND (A.DELETE_BIT = 0)
		AND ( (A.STATUS_FLAG > 1 AND A.STATUS_FLAG < 5) ) AND (@DEPTID=0 OR A.DEPT_ID=@DEPTID)) A
	LEFT JOIN --MODIFY BY TANY 2004-12-11 所有的B条件全部更改
	(SELECT DISTINCT X.ORDER_ID,X.EXEUSER,X.EXECDATE,X.REALEXECDATE,X.REALEXEUSER,X.BOOK_DATE,X.REALEXEUSERDb
         FROM (SELECT * FROM ZY_ORDEREXEC WHERE INPATIENT_ID = @BINID AND BABY_ID = @BABYID) X
--		,(SELECT ORDER_ID,MAX(EXECDATE)  EXECDATE FROM ZY_ORDEREXEC WHERE INPATIENT_ID = @BINID AND BABY_ID = @BABYID GROUP BY ORDER_ID) Y
--         WHERE X.ORDER_ID=Y.ORDER_ID AND X.EXECDATE=Y.EXECDATE
	) B
    ON A.ORDER_ID=B.ORDER_ID AND A.LASTEXECDATE=B.EXECDATE
	LEFT JOIN JC_EMPLOYEE_PROPERTY E1 ON A.ORDER_DOC=E1.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E2 ON A.AUDITING_USER=E2.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E3 ON A.AUDITING_USER1=E3.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E4 ON A.ORDER_EDOC=E4.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E5 ON A.ORDER_EUSER=E5.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E6 ON A.ORDER_EUSER1=E6.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E7 ON B.EXEUSER=E7.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E8 ON B.REALEXEUSER=E8.EMPLOYEE_ID
	LEFT JOIN JC_DEPT_PROPERTY D1 ON A.EXEC_DEPT=D1.DEPT_ID
--	LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1
	ORDER BY A.ORDER_BDATE,A.GROUP_ID,A.SERIAL_NO
                
END
--所有
ELSE IF @SELKIND=1
BEGIN
    --所有临嘱（临嘱单独出来主要是草药）
    IF @SELTYPE=1 

	--医嘱查询 所有临嘱                            	
	SELECT *--,DBO.FUN_ZY_GETORDERFEE(ORDER_ID) 费用 
        FROM 
        (	
	SELECT A.STATUS_FLAG,A.ORDER_ID,A.GROUP_ID,A.NUM,
	case when  ISNUMERIC (LEFT(A.UNIT,1))>0 then '['+A.UNIT +']' else  A.UNIT end UNIT,
	A.DWLX,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,A.DOSAGE,
		A.NTYPE,A.EXEC_DEPT,CONVERT(CHAR,DATEPART(DD,A.ORDER_BDATE)) DAY1,CONVERT(CHAR,DATEPART(MI,A.ORDER_BDATE)) SECOND1,CONVERT(CHAR,DATEPART(DD,A.ORDER_EDATE)) DAY2 ,CONVERT(CHAR,DATEPART(MI,A.ORDER_EDATE)) SECOND2,
		AUDITING_USER,AUDITING_USER1,ORDER_EUSER,ORDER_EUSER1,CASE WHEN NTYPE<=3 AND NTYPE<>0 THEN A.ITEM_CODE ELSE CONVERT(CHAR,A.HOITEM_ID) END ITEM_CODE,XMLY,HOITEM_ID,
		CONVERT(CHAR,DATEPART(MM,A.ORDER_BDATE)) 开日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_BDATE)) 开时间,
		LTRIM(RTRIM(A.ORDER_CONTEXT))+CASE WHEN ISNULL(ORDER_SPEC,'')='' THEN '' ELSE '('+LTRIM(RTRIM(ORDER_SPEC))+')' END 医嘱内容,E1.NAME 开嘱医生,E2.NAME 开嘱转抄,E3.NAME 开嘱核对,
		CONVERT(CHAR,DATEPART(MM,A.ORDER_EDATE)) 停日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_EDATE)) 停时间,
		E4.NAME 停嘱医生,E5.NAME 停嘱转抄,E6.NAME 停嘱核对,
		B.EXECDATE 发送时间,E7.NAME 发送护士,D1.NAME 执行科室,A.SERIAL_NO,
		PS_FLAG,PS_ORDERID,PS_USER,WZX_FLAG,ORDER_BDATE,B.REALEXECDATE 执行时间,rtrim(E8.NAME)+' '+isnull(dbo.fun_getEmpName(ISNULL(REALEXEUSERDb,-1)),'') 执行人,DEL_PRINT P --Add by Tany 2011-01-21
		 ,isnull(isprintypgg,0) isprintypgg,a.DEPT_ID ,ORDER_SPEC,REALEXEUSERDb,REALEXEUSER,A.ts,A.zsl,A.zsldw--add by zouchihua 2011-11-30
	       ,0 费用--add by jchl 2015-03-24
	FROM ZY_ORDERRECORD A --LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') C ON A.ORDER_USAGE=C.USG
	LEFT JOIN
	(SELECT DISTINCT X.ORDER_ID,X.EXEUSER,X.EXECDATE,X.REALEXECDATE,X.REALEXEUSER,X.BOOK_DATE,X.REALEXEUSERDb
         FROM (SELECT * FROM ZY_ORDEREXEC WHERE INPATIENT_ID = @BINID AND BABY_ID = @BABYID) X
--		,(SELECT ORDER_ID,MAX(EXECDATE)  EXECDATE FROM ZY_ORDEREXEC WHERE INPATIENT_ID = @BINID AND BABY_ID = @BABYID GROUP BY ORDER_ID) Y
--         WHERE X.ORDER_ID=Y.ORDER_ID AND X.EXECDATE=Y.EXECDATE
	) B
    ON A.ORDER_ID=B.ORDER_ID AND A.LASTEXECDATE=B.EXECDATE
	LEFT JOIN JC_EMPLOYEE_PROPERTY E1 ON A.ORDER_DOC=E1.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E2 ON A.AUDITING_USER=E2.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E3 ON A.AUDITING_USER1=E3.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E4 ON A.ORDER_EDOC=E4.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E5 ON A.ORDER_EUSER=E5.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E6 ON A.ORDER_EUSER1=E6.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E7 ON B.EXEUSER=E7.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E8 ON B.REALEXEUSER=E8.EMPLOYEE_ID
	LEFT JOIN JC_DEPT_PROPERTY D1 ON A.EXEC_DEPT=D1.DEPT_ID
--	LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1
	WHERE (A.MNGTYPE=@SELTYPE OR A.MNGTYPE=@SELTYPE2)
		AND ( (@ISSHowSS=0 and A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT)) or @ISSHowSS=1 or @DEPTID in(SELECT DEPTID FROM SS_DEPT)   )--Modify by zouchihua  解决特殊治疗到手术室
		AND (A.INPATIENT_ID = @BINID) AND (A.BABY_ID = @BABYID)
		AND (A.DELETE_BIT = 0)
		AND (A.STATUS_FLAG > 1 AND A.STATUS_FLAG<=5)
		AND A.NTYPE<>3 AND (@DEPTID=0 OR A.DEPT_ID=@DEPTID)
	UNION ALL
	SELECT A.STATUS_FLAG,DBO.FUN_GETEMPTYGUID(),A.GROUP_ID,A.DOSAGE,'付',-1,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,A.DOSAGE,
		A.NTYPE,A.EXEC_DEPT,CONVERT(CHAR,DATEPART(DD,A.ORDER_BDATE)) DAY1,CONVERT(CHAR,DATEPART(MI,A.ORDER_BDATE)) SECOND1,CONVERT(CHAR,DATEPART(DD,A.ORDER_EDATE)) DAY2 ,CONVERT(CHAR,DATEPART(MI,A.ORDER_EDATE)) SECOND2,
		AUDITING_USER,AUDITING_USER1,ORDER_EUSER,ORDER_EUSER1, 'ZY',-1,1,
		CONVERT(CHAR,DATEPART(MM,A.ORDER_BDATE)) 开日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_BDATE)) 开时间,
		'中草药处方'+
			case when @zcyxsmc='0' then '' else  (case when rtrim(isnull(A.MEMO,''))!=''   then '【'+isnull(A.MEMO,'')+'】' else isnull((select top 1 '【'+MBMC+'】' from  jc_cfmb where MBXH=A.PS_ORDERID),'') end  )   end
			 医嘱内容,
		E1.NAME 开嘱医生,E2.NAME 开嘱转抄,E3.NAME 开嘱核对,
		CONVERT(CHAR,DATEPART(MM,A.ORDER_EDATE)) 停日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_EDATE)) 停时间,
		E4.NAME 停嘱医生,E5.NAME 停嘱转抄,E6.NAME 停嘱核对,
		B.EXECDATE 发送时间,E7.NAME 发送护士,D1.NAME 执行科室,0,
		0,DBO.FUN_GETEMPTYGUID(),0,WZX_FLAG,ORDER_BDATE,B.REALEXECDATE 执行时间,rtrim(E8.NAME)+' '+isnull(dbo.fun_getEmpName(ISNULL(REALEXEUSERDb,-1)),'') 执行人,CAST(DEL_PRINT AS SMALLINT) P --Add by Tany 2011-01-21
		 ,0 isprintypgg ,a.DEPT_ID ,'' ORDER_SPEC,REALEXEUSERDb,REALEXEUSER,A.ts,null zsl,null zsldw--add by zouchihua 2011-11-30
	       ,0 as 费用--add by jchl 2015-03-24
	FROM (SELECT * FROM ZY_ORDERRECORD A

	      WHERE (A.MNGTYPE=@SELTYPE OR A.MNGTYPE=@SELTYPE2)
		AND ( (@ISSHowSS=0 and A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT)) or @ISSHowSS=1 or @DEPTID in(SELECT DEPTID FROM SS_DEPT)   )--Modify by zouchihua  解决特殊治疗到手术室
		AND (A.INPATIENT_ID = @BINID) AND (A.BABY_ID = @BABYID)
		AND (A.DELETE_BIT = 0)
		AND (A.STATUS_FLAG > 1 AND A.STATUS_FLAG<=5)
		AND A.NTYPE=3 AND (@DEPTID=0 OR A.DEPT_ID=@DEPTID)) A
	--FETCH FIRST 1 ROWS ONLY) A 
	--LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') C ON A.ORDER_USAGE=C.USG
	LEFT JOIN
	(SELECT DISTINCT X.ORDER_ID,X.EXEUSER,X.EXECDATE,X.REALEXECDATE,X.REALEXEUSER,X.BOOK_DATE,X.REALEXEUSERDb
         FROM (SELECT * FROM ZY_ORDEREXEC WHERE INPATIENT_ID = @BINID AND BABY_ID = @BABYID) X
--		,(SELECT ORDER_ID,MAX(EXECDATE)  EXECDATE FROM ZY_ORDEREXEC WHERE INPATIENT_ID = @BINID AND BABY_ID = @BABYID GROUP BY ORDER_ID) Y
--         WHERE X.ORDER_ID=Y.ORDER_ID AND X.EXECDATE=Y.EXECDATE
	) B
    ON A.ORDER_ID=B.ORDER_ID AND A.LASTEXECDATE=B.EXECDATE
	LEFT JOIN JC_EMPLOYEE_PROPERTY E1 ON A.ORDER_DOC=E1.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E2 ON A.AUDITING_USER=E2.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E3 ON A.AUDITING_USER1=E3.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E4 ON A.ORDER_EDOC=E4.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E5 ON A.ORDER_EUSER=E5.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E6 ON A.ORDER_EUSER1=E6.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E7 ON B.EXEUSER=E7.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E8 ON B.REALEXEUSER=E8.EMPLOYEE_ID
	LEFT JOIN JC_DEPT_PROPERTY D1 ON A.EXEC_DEPT=D1.DEPT_ID
	GROUP BY A.STATUS_FLAG,A.GROUP_ID,A.DOSAGE,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,A.DOSAGE,
		A.NTYPE,A.EXEC_DEPT,A.ORDER_BDATE,A.ORDER_EDATE,
		A.ORDER_DOC,A.AUDITING_USER,AUDITING_USER1,ORDER_EUSER,ORDER_EUSER1,
		A.ORDER_EDATE,A.ORDER_EDATE,
		ORDER_EDOC,ORDER_EUSER,ORDER_EUSER1,
		B.EXECDATE,B.EXEUSER,A.EXEC_DEPT,WZX_FLAG,B.REALEXECDATE,B.BOOK_DATE,
		E1.NAME,E2.NAME,E3.NAME,E4.NAME,E5.NAME,E6.NAME,E7.NAME,E8.NAME,D1.NAME,A.DEPT_ID,REALEXEUSERDb,REALEXEUSER,DEL_PRINT,A.ts--,A.zsl,A.zsldw
		,A.MEMO,A.PS_ORDERID
        ) TMP 
        ORDER BY ORDER_BDATE,GROUP_ID,SERIAL_NO
                
    --所有长嘱和长期、临时帐单
    ELSE

	--医嘱查询 所有长嘱、帐单                            	
	SELECT A.STATUS_FLAG,A.ORDER_ID,A.GROUP_ID,A.NUM,
	case when  ISNUMERIC (LEFT(A.UNIT,1))>0 then '['+A.UNIT +']' else  A.UNIT end UNIT,
	A.DWLX,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,A.DOSAGE,
		A.NTYPE,A.EXEC_DEPT,CONVERT(CHAR,DATEPART(DD,A.ORDER_BDATE)) DAY1,CONVERT(CHAR,DATEPART(MI,A.ORDER_BDATE)) SECOND1,CONVERT(CHAR,DATEPART(DD,A.ORDER_EDATE)) DAY2 ,CONVERT(CHAR,DATEPART(MI,A.ORDER_EDATE)) SECOND2,
		AUDITING_USER,AUDITING_USER1,ORDER_EUSER,ORDER_EUSER1,CASE WHEN NTYPE<=3 AND NTYPE<>0 THEN A.ITEM_CODE ELSE CONVERT(CHAR,A.HOITEM_ID) END ITEM_CODE,A.XMLY,A.HOITEM_ID,
		CONVERT(CHAR,DATEPART(MM,A.ORDER_BDATE)) 开日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_BDATE)) 开时间,
		LTRIM(RTRIM(A.ORDER_CONTEXT))+CASE WHEN ISNULL(ORDER_SPEC,'')='' THEN '' ELSE '('+LTRIM(RTRIM(ORDER_SPEC))+')' END 医嘱内容,E1.NAME 开嘱医生,E2.NAME 开嘱转抄,E3.NAME 开嘱核对,
		CASE WHEN A.STATUS_FLAG<4 THEN '' ELSE CONVERT(CHAR,DATEPART(MM,A.ORDER_EDATE)) END 停日期,CASE WHEN A.STATUS_FLAG<4 THEN '' ELSE CONVERT(CHAR,DATEPART(HH,A.ORDER_EDATE)) END 停时间,
		CASE WHEN A.STATUS_FLAG<4 THEN '' ELSE E4.NAME END 停嘱医生,E5.NAME 停嘱转抄,E6.NAME 停嘱核对,
		B.EXECDATE 发送时间,E7.NAME 发送护士,D1.NAME 执行科室,A.SERIAL_NO,
		PS_FLAG,PS_ORDERID,PS_USER,WZX_FLAG,A.ORDER_BDATE,B.REALEXECDATE 执行时间,rtrim(E8.NAME)+' '+isnull(dbo.fun_getEmpName(ISNULL(REALEXEUSERDb,-1)),'') 执行人,DEL_PRINT P --Add by Tany 2011-01-21--,CASE WHEN @SELTYPE=3 THEN DBO.FUN_ZY_GETORDERFEE(A.ORDER_ID) ELSE 0 END 费用
		 ,isnull(isprintypgg,0) isprintypgg,ORDER_SPEC,REALEXEUSERDb,REALEXEUSER --add by zouchihua 2011-11-30
	       , CASE WHEN @SELTYPE=3 THEN cast(coalesce(dbo.FUN_BASE_HOIPRICE(HOITEM_ID)*a.num,0) as decimal(18,2)) ELSE 0 END as 费用--add by jchl 2015-03-24
	FROM ZY_ORDERRECORD A --LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') C ON A.ORDER_USAGE=C.USG
	LEFT JOIN
	(SELECT DISTINCT X.ORDER_ID,X.EXEUSER,X.EXECDATE,X.REALEXECDATE,X.REALEXEUSER,X.BOOK_DATE,X.REALEXEUSERDb
         FROM (SELECT * FROM ZY_ORDEREXEC WHERE INPATIENT_ID = @BINID AND BABY_ID = @BABYID) X
--		,(SELECT ORDER_ID,MAX(EXECDATE)  EXECDATE FROM ZY_ORDEREXEC WHERE INPATIENT_ID = @BINID AND BABY_ID = @BABYID GROUP BY ORDER_ID) Y
--         WHERE X.ORDER_ID=Y.ORDER_ID AND X.EXECDATE=Y.EXECDATE
	) B
    ON A.ORDER_ID=B.ORDER_ID AND A.LASTEXECDATE=B.EXECDATE
	LEFT JOIN JC_EMPLOYEE_PROPERTY E1 ON A.ORDER_DOC=E1.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E2 ON A.AUDITING_USER=E2.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E3 ON A.AUDITING_USER1=E3.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E4 ON A.ORDER_EDOC=E4.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E5 ON A.ORDER_EUSER=E5.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E6 ON A.ORDER_EUSER1=E6.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E7 ON B.EXEUSER=E7.EMPLOYEE_ID
	LEFT JOIN JC_EMPLOYEE_PROPERTY E8 ON B.REALEXEUSER=E8.EMPLOYEE_ID
	LEFT JOIN JC_DEPT_PROPERTY D1 ON A.EXEC_DEPT=D1.DEPT_ID
--	LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1
	WHERE (A.MNGTYPE=@SELTYPE OR A.MNGTYPE=@SELTYPE2)
		AND ( (@ISSHowSS=0 and A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT)) or @ISSHowSS=1 or @DEPTID in(SELECT DEPTID FROM SS_DEPT)   )--Modify by zouchihua  解决特殊治疗到手术室
		AND (A.INPATIENT_ID = @BINID) AND (A.BABY_ID = @BABYID)
		AND (A.DELETE_BIT = 0)
		AND (A.STATUS_FLAG > 1 AND A.STATUS_FLAG<=5) AND (@DEPTID=0 OR A.DEPT_ID=@DEPTID)
	ORDER BY A.ORDER_BDATE,A.GROUP_ID,A.SERIAL_NO
                
END
--所有未发送医嘱
ELSE
BEGIN
    
	--所有未发送医嘱
	--MODIFY BY TANY 2005-01-10
	SELECT A.STATUS_FLAG,A.ORDER_ID,A.GROUP_ID,A.NUM,
	case when  ISNUMERIC (LEFT(A.UNIT,1))>0 then '['+A.UNIT +']' else  A.UNIT end UNIT,
	A.DWLX,A.ORDER_USAGE,A.FREQUENCY,A.DROPSPER,A.DOSAGE,
		A.NTYPE,A.EXEC_DEPT,CONVERT(CHAR,DATEPART(DD,A.ORDER_BDATE)) DAY1,CONVERT(CHAR,DATEPART(MI,A.ORDER_BDATE)) SECOND1,CONVERT(CHAR,DATEPART(DD,A.ORDER_EDATE)) DAY2 ,CONVERT(CHAR,DATEPART(MI,A.ORDER_EDATE)) SECOND2,
		AUDITING_USER,AUDITING_USER1,ORDER_EUSER,ORDER_EUSER1,CASE WHEN NTYPE<=3 AND NTYPE<>0 THEN A.ITEM_CODE ELSE CONVERT(CHAR,A.HOITEM_ID) END ITEM_CODE,A.XMLY,A.HOITEM_ID,C.INPATIENT_ID,C.BABY_ID,C.ISMY,
		CONVERT(CHAR,DATEPART(MM,A.ORDER_BDATE)) 开日期,CONVERT(CHAR,DATEPART(HH,A.ORDER_BDATE)) 开时间,C.BED_NO 床号,C.INPATIENT_NO 住院号,C.NAME 姓名,
		CASE A.MNGTYPE WHEN 0 THEN '长期医嘱' WHEN 1 THEN '临时医嘱' WHEN 2 THEN '长期账单' WHEN 3 THEN '临时账单' WHEN 5 THEN '临时医嘱' END AS 类型,
		LTRIM(RTRIM(A.ORDER_CONTEXT))+CASE WHEN ISNULL(ORDER_SPEC,'')='' THEN '' ELSE '('+LTRIM(RTRIM(ORDER_SPEC))+')' END 医嘱内容,DBO.FUN_ZY_SEEKEMPLOYEENAME(A.ORDER_DOC) 开嘱医生,DBO.FUN_ZY_SEEKEMPLOYEENAME(A.AUDITING_USER) 开嘱转抄,DBO.FUN_ZY_SEEKEMPLOYEENAME(AUDITING_USER1) 开嘱核对,
		TERMINAL_TIMES 末次, FIRST_TIMES 首次,A.MNGTYPE,
		CASE WHEN A.STATUS_FLAG<4 THEN '' ELSE CONVERT(CHAR,DATEPART(MM,A.ORDER_EDATE)) END 停日期,CASE WHEN A.STATUS_FLAG<4 THEN '' ELSE CONVERT(CHAR,DATEPART(HH,A.ORDER_EDATE)) END 停时间,
		CASE WHEN A.STATUS_FLAG<4 THEN '' ELSE DBO.FUN_ZY_SEEKEMPLOYEENAME(ORDER_EDOC) END 停嘱医生,DBO.FUN_ZY_SEEKEMPLOYEENAME(ORDER_EUSER) 停嘱转抄,DBO.FUN_ZY_SEEKEMPLOYEENAME(ORDER_EUSER1) 停嘱核对,
		B.EXECDATE 发送时间,DBO.FUN_ZY_SEEKEMPLOYEENAME(B.EXEUSER) 发送护士,DBO.FUN_ZY_SEEKDEPTNAME(A.EXEC_DEPT) 执行科室,A.SERIAL_NO,
		PS_FLAG,PS_ORDERID,PS_USER,WZX_FLAG,A.ORDER_BDATE,B.REALEXECDATE 执行时间,DBO.FUN_ZY_SEEKEMPLOYEENAME(REALEXEUSER) 执行人,0 费用
	FROM ZY_ORDERRECORD A
	INNER JOIN ( SELECT * FROM VI_ZY_VINPATIENT_BED WHERE WARD_ID=@WARDID AND INPATIENT_ID = @BINID AND BABY_ID = @BABYID) C
	ON (A.INPATIENT_ID = C.INPATIENT_ID ) AND (A.BABY_ID = C.BABY_ID)
	--LEFT JOIN (SELECT NAME USG,IS_PRINT ISP FROM JC_USAGEDICTION WHERE NAME <> '') C ON A.ORDER_USAGE=C.USG
	LEFT JOIN
	(SELECT DISTINCT X.ORDER_ID,X.EXEUSER,X.EXECDATE,X.REALEXECDATE,X.REALEXEUSER,X.BOOK_DATE,X.REALEXEUSERDb
         FROM (SELECT * FROM ZY_ORDEREXEC WHERE INPATIENT_ID = @BINID AND BABY_ID = @BABYID) X
--		,(SELECT ORDER_ID,MAX(EXECDATE)  EXECDATE FROM ZY_ORDEREXEC WHERE INPATIENT_ID = @BINID AND BABY_ID = @BABYID GROUP BY ORDER_ID) Y
--         WHERE X.ORDER_ID=Y.ORDER_ID AND X.EXECDATE=Y.EXECDATE
	) B
    ON A.ORDER_ID=B.ORDER_ID AND A.LASTEXECDATE=B.EXECDATE
--	LEFT JOIN VI_YP_YPCD YP ON A.HOITEM_ID=YP.CJID AND A.XMLY=1
	WHERE (A.DELETE_BIT = 0)
		AND (A.STATUS_FLAG > 1)  AND (A.STATUS_FLAG < 5)
		AND ( (B.EXECDATE IS NULL)  OR ( B.EXECDATE IS NOT NULL AND CONVERT(DATETIME,DBO.FUN_GETDATE(B.EXECDATE)) < CONVERT(DATETIME,DBO.FUN_GETDATE(@EXECDATE) )) )
		AND CONVERT(DATETIME,DBO.FUN_GETDATE(A.ORDER_BDATE))<= CONVERT(DATETIME,DBO.FUN_GETDATE(@EXECDATE) )
		AND ( (@ISSHowSS=0 and A.DEPT_ID NOT IN (SELECT DEPTID FROM SS_DEPT)) or @ISSHowSS=1 or @DEPTID in(SELECT DEPTID FROM SS_DEPT)   )--Modify by zouchihua  解决特殊治疗到手术室 
		AND (@DEPTID=0 OR A.DEPT_ID=@DEPTID)
	ORDER BY C.BED_NO,C.INPATIENT_NO,C.BABY_ID,A.NTYPE,A.GROUP_ID,A.ORDER_BDATE,A.SERIAL_NO
        
END

GO


