IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SP_ZYYS_DELETE_ORDER]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SP_ZYYS_DELETE_ORDER]
GO
CREATE PROCEDURE [dbo].[SP_ZYYS_DELETE_ORDER]
(
	@SIGN INT, 
	@ORDERID UNIQUEIDENTIFIER, 
	@GROUPNUM INT, 
	@INPATIENTID UNIQUEIDENTIFIER
) 
AS
/*
Modify By Tany 2014-09-12 增加删除医嘱打印表记录
*/
BEGIN
	DECLARE @MNGTYPE INT
	DECLARE @PAGENO INT
	DECLARE @ROWNO INT
	DECLARE @PRT_STATUS INT
	
	--删除一条
	IF @SIGN=0
	BEGIN
		UPDATE ZY_ORDERRECORD SET DELETE_BIT=1 
		WHERE INPATIENT_ID=@INPATIENTID AND ORDER_ID=@ORDERID AND STATUS_FLAG IN (0,1,9)--9 是补录医嘱
		
		SELECT @MNGTYPE=MNGTYPE FROM ZY_ORDERRECORD WHERE INPATIENT_ID=@INPATIENTID AND ORDER_ID=@ORDERID
	END
	
	--删除一组
	IF @SIGN=1
	BEGIN
		UPDATE ZY_ORDERRECORD SET DELETE_BIT=1
		WHERE INPATIENT_ID=@INPATIENTID AND GROUP_ID=@GROUPNUM AND STATUS_FLAG IN (0,1,9)
		
		SELECT @MNGTYPE=MNGTYPE FROM ZY_ORDERRECORD WHERE INPATIENT_ID=@INPATIENTID AND GROUP_ID=@GROUPNUM
	END
	
	IF @MNGTYPE=0
	BEGIN
		--IF @SIGN=0
		--	SELECT @PAGENO=PAGENO,@ROWNO=ROWNO,@PRT_STATUS=PRT_STATUS FROM ZY_LOGORDERPRT WHERE INPATIENT_ID=@INPATIENTID AND ORDER_ID=@ORDERID
		--ELSE
		--不管是一条医嘱还是一组医嘱，都按一组医嘱来删除打印记录
		SELECT @PAGENO=MIN(PAGENO),@ROWNO=MIN(ROWNO),@PRT_STATUS=MIN(PRT_STATUS) FROM ZY_LOGORDERPRT WHERE INPATIENT_ID=@INPATIENTID AND GROUP_ID=@GROUPNUM
		
		SET @PAGENO=ISNULL(@PAGENO,0)
		SET @ROWNO=ISNULL(@ROWNO,0)
		SET @PRT_STATUS=ISNULL(@PRT_STATUS,0)
		
		IF @PRT_STATUS<=0 and @ROWNO>0 --行号必须大于0，否则证明没找到记录，不需要删除 Modify By Tany 2014-09-25
			delete from zy_logorderprt where inpatient_id=@INPATIENTID and ((PAGENO>=@PAGENO and ROWNO>=@ROWNO) OR PAGENO>@PAGENO)
	END
	ELSE
	BEGIN
		--IF @SIGN=0
		--	SELECT @PAGENO=PAGENO,@ROWNO=ROWNO,@PRT_STATUS=PRT_STATUS FROM ZY_TMPORDERPRT WHERE INPATIENT_ID=@INPATIENTID AND ORDER_ID=@ORDERID
		--ELSE
		--不管是一条医嘱还是一组医嘱，都按一组医嘱来删除打印记录
		SELECT @PAGENO=MIN(PAGENO),@ROWNO=MIN(ROWNO),@PRT_STATUS=MIN(PRT_STATUS) FROM ZY_TMPORDERPRT WHERE INPATIENT_ID=@INPATIENTID AND GROUP_ID=@GROUPNUM
		
		SET @PAGENO=ISNULL(@PAGENO,0)
		SET @ROWNO=ISNULL(@ROWNO,0)
		SET @PRT_STATUS=ISNULL(@PRT_STATUS,0)
		
		IF @PRT_STATUS<=0 and @ROWNO>0 --行号必须大于0，否则证明没找到记录，不需要删除 Modify By Tany 2014-09-25
			delete from zy_tmporderprt where inpatient_id=@INPATIENTID and ((PAGENO>=@PAGENO and ROWNO>=@ROWNO) OR PAGENO>@PAGENO)
	END
END


