IF EXISTS( SELECT 1 FROM dbo.SYSOBJECTS WHERE name ='sp_yf_select_TLMX_YFY_ALL' AND type='P' )
	drop procedure sp_yf_select_TLMX_YFY_ALL
go	

CREATE PROCEDURE sp_yf_select_TLMX_YFY_ALL (  
@GROUPID UNIQUEIDENTIFIER,
@TMPNAME varchar(50),
@STEP INT
)    
as  
	DECLARE @tablename varchar(32)
	DECLARE @stmt varchar(8000)
	set @tablename = '##T__' + LTRIM(RTRIM(@TMPNAME))  --定义全局临时表名
	
	if @STEP = 1 
	BEGIN
		EXEC('IF EXISTS(SELECT name FROM tempdb..sysobjects WHERE  name = ''' +@tablename+ ''')
	    		DROP TABLE ' + @tablename )
		set @stmt='CREATE TABLE ' + @tablename + '(GROUPID UNIQUEIDENTIFIER)'								
		exec (@stmt)			
		RETURN
	END
	
	IF @STEP = 2
	BEGIN
		set @stmt='INSERT INTO ' + @tablename + '(GROUPID) VALUES (''' + convert(varchar,@GROUPID) + ''')'	      	
		exec(@stmt)
		RETURN
	END
  
	IF @STEP = 3	
	BEGIN  
		DECLARE @SS VARCHAR(8000)  
		DECLARE @NCOUNT INT  
		
		CREATE TABLE #T_GROUPID(GROUPID UNIQUEIDENTIFIER)
		set @stmt = 'INSERT INTO #T_GROUPID SELECT * FROM ' + @tablename
		exec(@stmt)
		
		SELECT 0 序号,CAST(1 AS SMALLINT) 选择,'' 类型,S_YPJX 剂型,S_YPPM+ISNULL(YPSPMBZ,'') 品名,S_YPSPM 商品名,S_YPGG 规格,S_SCCJ 厂家,CAST(COST_PRICE AS FLOAT) 单价,  
			'' 库存数,cast(a.num as float) 数量,a.unit 单位,'' 缺药,'' 转发,cast(sdvalue as float) 金额,shh 货号,a.xmid as cjid,  
			DBO.FUN_ZY_GETBEDNO(BED_ID) 床号,C.NAME 姓名,INPATIENT_NO 住院号,SEX_NAME  性别,''  年龄,A.DEPT_BR AS DEPT_ID,'''' APPLY_ID,'''' APPLY_DATE,CHARGE_BIT,'''' WARD_ID,  
			A.ID ZY_ID,UNITRATE ,0 YPSL,0 ZXDW,0 DWBL,0 批发价,0 批发金额,   
			(CASE WHEN DWLX <>1 THEN  CAST(E.NUM AS FLOAT)    ELSE CAST(E.NUM/B.HLXS AS DECIMAL(10,4))  END) AS  MCYL,  
			(CASE WHEN DWLX <>1 THEN E.UNIT ELSE DBO.FUN_YP_YPDW(BZDW) END ) AS MCDW,  
			CAST(CAST(E.NUM AS FLOAT) AS VARCHAR(50))+ISNULL(E.UNIT,'') AS 用量,ORDER_USAGE AS 用法,  ISNULL(FREQUENCY,'')  频次,  
			CONVERT(varchar(100), in_date, 21) as  ryrq, '' lsj,  '' 货位号,'' lyflcode,  
			LEFT('00',2-LEN(MONTH(PRESC_DATE)))+CAST(MONTH(PRESC_DATE) AS VARCHAR(10))+ LEFT('00',2-LEN(DAY(PRESC_DATE)))+CAST(DAY(PRESC_DATE) AS VARCHAR(10)) AS PRESC_DATE,
			'' AS DEPT_LY,'' AS YPDW,  (CASE WHEN MNGTYPE IN(1,5) THEN '' ELSE EXECTIME END)  GYSJ,PRESC_DATE 处方日期,  MNGTYPE,--修改MNGTYPE   
			A.KCID,B.YPYWM 英文名,A.CZ_ID,A.DOSAGE 剂数,E.NUM 剂量,A.CHARGE_DATE 收费日期,A.CHARGE_USER 收费员ID,C.ZY_DOC 管床医生ID,E.HOITEM_ID 医嘱序号,    
			A.PRESCRIPTION_ID 处方ID,E.ORDER_CONTEXT 医嘱内容,E.EXEC_DEPT 执行科室ID,E.DEPT_BR 病人科室ID,E.DEPT_ID 开单科室ID,    
			E.ORDER_DOC 开单医生ID ,(SELECT ID FROM YP_YPDW WHERE DWMC=E.UNIT ) JLZXDW,'' YPDW ,C.INPATIENT_ID 住院ID,A.BABY_ID 婴儿ID, '' 嘱托 ,0 组标志,E.UNIT 剂量单位    
  
		FROM ZY_FEE_SPECI A(NOLOCK) INNER JOIN VI_YP_YPCD B(NOLOCK) ON A.XMID=B.CJID AND A.XMLY=1  
			INNER JOIN VI_ZY_VINPATIENT_INFO C(NOLOCK) ON  A.INPATIENT_ID=C.INPATIENT_ID AND A.BABY_ID=C.BABY_ID  
			--INNER JOIN ZY_ORDEREXEC D(NOLOCK) ON A.ORDEREXEC_ID=D.ID   
			INNER JOIN ZY_ORDERRECORD E(NOLOCK) ON A.ORDER_ID=E.ORDER_ID  
			LEFT JOIN JC_FREQUENCY F ON E.FREQUENCY=F.NAME  
		WHERE A.GROUP_ID IN (SELECT GROUPID FROM #T_GROUPID) ORDER BY A.DEPT_BR,A.INPATIENT_ID,BED_ID  
END  
  
