IF  EXISTS (SELECT * FROM SYS.TRIGGERS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TR_ZY_BEDDICTION_INSERTFOREVENTLOG]'))
DROP TRIGGER [DBO].[TR_ZY_BEDDICTION_INSERTFOREVENTLOG]
GO
CREATE TRIGGER TR_ZY_BEDDICTION_INSERTFOREVENTLOG
	ON ZY_BEDDICTION 
	AFTER INSERT
AS   
SET NOCOUNT ON

insert into EVENTLOG(EVENT,CATEGORY,BIZID)
select 'n2oCwwh.HIS','ZY_BEDDICTION',bed_id from inserted where dept_id in (select deptid from vi_zy_newhishsz)
and ISINUSE=0