ALTER PROCEDURE [DBO].[SP_ZYHS_SELKSSR]  
 (  
 @BDATE DATETIME,   
 @EDATE DATETIME,   
 @DEPTID BIGINT  
 )   
AS  
/*--------------------------------------------------------------------------  
作者：TANY  
说明：护士站-统计科室收入(记帐就算,统计的是开单科室为本科室的所有科室的费用)  
日期：2007-08-29  
参数：  
 @BDATE 开始日期,  
 @EDATE 结束日期,  
 @DEPTID 科室ID  
修改：  
 2011-07-25 BY SHILIN
--------------------------------------------------------------------------*/  
SET NOCOUNT ON  
  
DECLARE @SQL VARCHAR(8000)  --保存SQL语句  
DECLARE @SQLSUM VARCHAR(8000)  
DECLARE @SQLSUM1 VARCHAR(8000)  
DECLARE @XMMC VARCHAR(50)--项目名称  
  
SET @SQL=''  
SET @SQLSUM=''  
SET @SQLSUM1=''  
SET @XMMC=''  
  
--定义游标变量  
DECLARE @NAME VARCHAR(100)  
DECLARE @FEE_WARDID VARCHAR(10)  
DECLARE @FEE_DEPTBR INT  
DECLARE @FEE_INPATIENTID UNIQUEIDENTIFIER  
DECLARE @FEE_NAME VARCHAR(100)  
DECLARE @FEE_ACVALUE DECIMAL(18,2)  
  
--建立临时表  
SET @SQL='CREATE TABLE ##TMP(WARD_ID VARCHAR(10),DEPT_ID INT,INPATIENT_ID UNIQUEIDENTIFIER'  
 
--建立数据临时表  
DECLARE CS_STATITEM CURSOR FOR SELECT ITEM_NAME FROM JC_STAT_ITEM ORDER BY CODE  
  
OPEN CS_STATITEM  
  
FETCH CS_STATITEM INTO @NAME  
  
WHILE @@FETCH_STATUS=0  
BEGIN   
  SET @SQL=@SQL+',['+@NAME+'] DECIMAL(18,2) DEFAULT 0'  
  SET @SQLSUM=@SQLSUM+','+'SUM(['+@NAME+']) AS ['+@NAME+']'  
  SET @SQLSUM1=@SQLSUM1+'+'+'SUM(['+@NAME+'])'  
  
  FETCH CS_STATITEM INTO @NAME  
END  
  
CLOSE CS_STATITEM    
DEALLOCATE CS_STATITEM   
  
SET @SQL=@SQL+')'  
EXEC(@SQL)  
  
SET @BDATE=CONVERT(DATETIME,DBO.FUN_GETDATE(@BDATE))  
SET @EDATE=CONVERT(DATETIME,DBO.FUN_GETDATE(DATEADD(DD,1,@EDATE)))  
  
DECLARE CS_FEE CURSOR FOR  
  SELECT B.WARD_ID,A.DEPT_BR,A.INPATIENT_ID,C.ITEM_NAME,A.ACVALUE  
  FROM (SELECT * FROM ZY_FEE_SPECI WHERE CHARGE_BIT=1 AND DELETE_BIT=0   
        AND CHARGE_DATE >= @BDATE   
        AND CHARGE_DATE < @EDATE  
        AND DEPT_ID=@DEPTID) A  
  INNER JOIN JC_WARDRDEPT B  
  ON A.DEPT_BR=B.DEPT_ID  
  INNER JOIN JC_STAT_ITEM C   
  ON A.STATITEM_CODE=C.CODE  
  
OPEN CS_FEE  
  
FETCH CS_FEE INTO @FEE_WARDID,@FEE_DEPTBR,@FEE_INPATIENTID,@FEE_NAME,@FEE_ACVALUE  
  
WHILE @@FETCH_STATUS=0  
BEGIN  
  SET @XMMC=@FEE_NAME  
  IF @XMMC<>''  
  BEGIN  
    SET @SQL='INSERT INTO ##TMP(WARD_ID,DEPT_ID,INPATIENT_ID,'+ @XMMC +') VALUES('''+ @FEE_WARDID +''','+ CONVERT(VARCHAR,@FEE_DEPTBR) +','''+ CONVERT(VARCHAR(50),@FEE_INPATIENTID) +''','+ CONVERT(VARCHAR,@FEE_ACVALUE) +')'  
    EXEC(@SQL)  
  END  
    
  FETCH CS_FEE INTO @FEE_WARDID,@FEE_DEPTBR,@FEE_INPATIENTID,@FEE_NAME,@FEE_ACVALUE  
END  
  
CLOSE CS_FEE    
DEALLOCATE CS_FEE   
  
--最终数据  
SET @SQL='SELECT CASE WHEN GROUPING(B.INPATIENT_NO) = 1 THEN ''合  计'' ELSE C.WARD_NAME END AS 病区,'+
     'B.CUR_DEPT_NAME AS 科室,ISNULL(CAST(B.INPATIENT_ID AS VARCHAR(50)),'''') AS 编号,ISNULL(B.INPATIENT_NO,'''') AS 住院号,'+
     'ISNULL(B.NAME,'''') AS 姓名,0'+ @SQLSUM1 + ' AS 合计' + @SQLSUM + 
     ' FROM ##TMP A INNER JOIN VI_ZY_VINPATIENT_ALL B ON A.INPATIENT_ID=B.INPATIENT_ID'+  
     ' INNER JOIN JC_WARD C ON A.WARD_ID=C.WARD_ID'+  
     ' GROUP BY C.WARD_NAME,B.CUR_DEPT_NAME,B.INPATIENT_NO,B.NAME,B.INPATIENT_ID'+
     ' WITH ROLLUP HAVING B.INPATIENT_ID IS NOT NULL OR (B.CUR_DEPT_NAME IS NOT NULL AND B.INPATIENT_NO IS NULL)'
EXEC(@SQL)  
  
DROP TABLE ##TMP  

  