IF  EXISTS (SELECT * FROM SYS.TRIGGERS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TR_YY_BRXX_UPDATEFOREVENTLOG]'))
DROP TRIGGER [DBO].[TR_YY_BRXX_UPDATEFOREVENTLOG]
GO
--Add By Tany 2015-11-17 修改病人信息
CREATE TRIGGER [dbo].[TR_YY_BRXX_UPDATEFOREVENTLOG]
	ON [dbo].[YY_BRXX] 
	AFTER UPDATE
AS   
SET NOCOUNT ON

if update(jtdh)
begin
	insert into EVENTLOG(EVENT,CATEGORY,BIZID) 
	select 'n2oBrKdj.HIS','YY_BRXX',brxxid 
	from inserted
	where djly in (0,1)
end

GO