IF  EXISTS (SELECT * FROM SYS.TRIGGERS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TR_MZ_YYGHLB_INSERTFOREVENTLOG]'))
DROP TRIGGER [DBO].[TR_MZ_YYGHLB_INSERTFOREVENTLOG]
GO
--Add By Tany 2015-09-29 新增预约信息
CREATE TRIGGER [dbo].[TR_MZ_YYGHLB_INSERTFOREVENTLOG]
	ON [dbo].[MZ_YYGHLB] 
	AFTER INSERT
AS   
SET NOCOUNT ON

	insert into EVENTLOG(EVENT,CATEGORY,BIZID) 
	select 'GetYyMsgInfo','MZ_YYGHLB',yyid 
	from inserted

GO


