IF  EXISTS (SELECT * FROM SYS.TRIGGERS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TR_YY_BRXX_INSERTFOREVENTLOG]'))
DROP TRIGGER [DBO].[TR_YY_BRXX_INSERTFOREVENTLOG]
GO
----Add By Tany 2015-08-31 新增病人信息
--CREATE TRIGGER [dbo].[TR_YY_BRXX_INSERTFOREVENTLOG]
--	ON [dbo].[YY_BRXX] 
--	AFTER INSERT,UPDATE
--AS   
--SET NOCOUNT ON

--	insert into EVENTLOG(EVENT,CATEGORY,BIZID) 
--	select 'n2oBrKdj.HIS','YY_BRXX',brxxid 
--	from inserted
--	where djly in (0,1)

--GO


