IF  EXISTS (SELECT * FROM SYS.TRIGGERS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TR_YF_FY_DELETEFOREVENTLOG]'))
DROP TRIGGER [DBO].[TR_YF_FY_DELETEFOREVENTLOG]
GO
--Add By Tany 2014-05-08 状态变更插入事件表
CREATE TRIGGER TR_YF_FY_DELETEFOREVENTLOG
	ON YF_FY 
	AFTER DELETE
AS   
SET NOCOUNT ON

DECLARE @JZCFBZ INT
DECLARE @TFBZ INT

SELECT @JZCFBZ=JZCFBZ,@TFBZ=TFBZ
FROM deleted

IF(@JZCFBZ=0)
BEGIN
	
	insert into EVENTLOG(EVENT,CATEGORY,BIZID) 
	select 'MZQXFYZT','YF_FY',CFXH from deleted

END