IF  EXISTS (SELECT * FROM SYS.TRIGGERS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TR_ZY_BEDDICTION_UPDATEFOREVENTLOG]'))
DROP TRIGGER [DBO].[TR_ZY_BEDDICTION_UPDATEFOREVENTLOG]
GO
--Add By Tany 2014-10-29 状态变更插入事件表
CREATE TRIGGER TR_ZY_BEDDICTION_UPDATEFOREVENTLOG
	ON ZY_BEDDICTION 
	AFTER UPDATE
AS   
SET NOCOUNT ON

IF(UPDATE(room_no) or update(hoitem_id))
BEGIN
	insert into EVENTLOG(EVENT,CATEGORY,BIZID)
	select 'n2oCwwh.HIS','ZY_BEDDICTION',bed_id from inserted where dept_id in (select deptid from vi_zy_newhishsz)
		and ISINUSE=0
	return
END
