IF  EXISTS (SELECT * FROM SYS.TRIGGERS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TR_ZY_JY_PRINT_INSERTFOREVENTLOG]'))
DROP TRIGGER [DBO].[TR_ZY_JY_PRINT_INSERTFOREVENTLOG]
GO
--Add By Tany 2014-04-16 状态变更插入事件表
CREATE TRIGGER TR_ZY_JY_PRINT_INSERTFOREVENTLOG
	ON ZY_JY_PRINT 
	AFTER INSERT
AS   
SET NOCOUNT ON

--因为检验做了直接接口，所以这里的事件只给EMR使用 Modify By Tany 2014-08-13
insert into EVENTLOG(EVENT,CATEGORY,BIZID) 
select 'NewExamOrder.EMR','ZY_JY_PRINT',id from inserted
