IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SP_ZYHS_SELWCLXM]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SP_ZYHS_SELWCLXM]
GO
create PROCEDURE [dbo].[SP_ZYHS_SELWCLXM]
 (
  @INPATIENT_ID UNIQUEIDENTIFIER, 
  @BABY_ID BIGINT
 ) 
AS
/*--------------------------------------------------------------------------
作者：TANY
说明：住院护士站-未处理项目查询
日期：2006-12-07
参数：
  @INPATIENT_ID 病人ID
  @BABY_ID 婴儿ID 
修改：
2015-02-02 增加显示费用所属的医嘱相关信息
--------------------------------------------------------------------------*/
SET NOCOUNT ON
declare @wfy int
set @wfy=ISNULL((select config from JC_CONFIG where ID=7130),'1')
declare @hdyz int --核对医嘱
set @hdyz=ISNULL((select config from JC_CONFIG where ID=7176),'1')

SELECT * FROM 
(SELECT CASE MNGTYPE
	WHEN 0 THEN '长期医嘱'
	WHEN 1 THEN '临时医嘱'
	WHEN 5 THEN '临时医嘱'
	WHEN 2 THEN '长期账单'
	WHEN 3 THEN '临时账单' END "类型",
        ORDER_CONTEXT "内容",'' "数量",'' "单位",'' "金额",DBO.FUN_ZY_SEEKDEPTNAME(EXEC_DEPT) "执行科室",
        DBO.FUN_ZY_SEEKDEPTNAME(DEPT_ID) "开单科室",DBO.FUN_ZY_SEEKEMPLOYEENAME(ORDER_DOC) "录入人",DBO.FUN_GETDATE(ORDER_BDATE) "录入时间",ORDER_ID ID,ORDER_BDATE "医嘱开始时间",'' "医嘱内容"
 FROM ZY_ORDERRECORD A
 WHERE A.STATUS_FLAG<5 AND A.DELETE_BIT=0 AND A.INPATIENT_ID=@INPATIENT_ID AND A.BABY_ID=@BABY_ID
 
 UNION ALL
 SELECT '药品',B.ITEM_NAME + ' ' + CASE WHEN B.TLFS=1 THEN '【缺药】' ELSE '' END,
	CONVERT(CHAR,B.NUM),B.UNIT,CONVERT(CHAR,B.ACVALUE),DBO.FUN_ZY_SEEKDEPTNAME(B.EXECDEPT_ID),DBO.FUN_ZY_SEEKDEPTNAME(B.DEPT_ID),
	DBO.FUN_ZY_SEEKEMPLOYEENAME(B.BOOK_USER),DBO.FUN_GETDATE(B.BOOK_DATE),B.ID,null,null
 FROM ZY_FEE_SPECI B 
 WHERE B.STATITEM_CODE IN ('01','02','03') AND B.CHARGE_BIT=0 AND B.DELETE_BIT=0 AND B.INPATIENT_ID=@INPATIENT_ID  AND B.BABY_ID=@BABY_ID
  
  UNION ALL--记账没有发药的医嘱未处理项目 add by zouchihua 2012-6-13
  SELECT '药品',B.ITEM_NAME + ' ' + '【未发药】' ,
	CONVERT(CHAR,B.NUM),B.UNIT,CONVERT(CHAR,B.ACVALUE),DBO.FUN_ZY_SEEKDEPTNAME(B.EXECDEPT_ID),DBO.FUN_ZY_SEEKDEPTNAME(B.DEPT_ID),
	DBO.FUN_ZY_SEEKEMPLOYEENAME(B.BOOK_USER),DBO.FUN_GETDATE(B.BOOK_DATE),B.ID,null,null
 FROM ZY_FEE_SPECI B 
 WHERE (@wfy='0' and B.STATITEM_CODE IN ('01','02','03') AND B.FY_BIT=0 and CHARGE_BIT=1 AND B.DELETE_BIT=0 AND B.INPATIENT_ID=@INPATIENT_ID  AND B.BABY_ID=@BABY_ID)
  
 UNION ALL
 SELECT '费用',B.ITEM_NAME,
	CONVERT(CHAR,B.NUM),B.UNIT,CONVERT(CHAR,B.ACVALUE),DBO.FUN_ZY_SEEKDEPTNAME(B.EXECDEPT_ID),DBO.FUN_ZY_SEEKDEPTNAME(B.DEPT_ID),
	DBO.FUN_ZY_SEEKEMPLOYEENAME(B.BOOK_USER),DBO.FUN_GETDATE(B.BOOK_DATE),B.ID,c.ORDER_BDATE,c.ORDER_CONTEXT
 FROM ZY_FEE_SPECI B left join ZY_ORDERRECORD c on B.ORDER_ID=c.ORDER_ID
 WHERE B.STATITEM_CODE NOT IN ('01','02','03') AND B.CHARGE_BIT=0 AND B.DELETE_BIT=0 AND B.INPATIENT_ID=@INPATIENT_ID  AND B.BABY_ID=@BABY_ID

 union all 
 select '未核对医嘱',b.ORDER_CONTEXT  ITEM_NAME,CONVERT(CHAR,B.NUM),b.UNIT,null,null,DBO.FUN_ZY_SEEKDEPTNAME(B.DEPT_ID),
 DBO.FUN_ZY_SEEKEMPLOYEENAME(B.ORDER_DOC),DBO.FUN_GETDATE(B.BOOK_DATE),null,null,null
 from ZY_ORDERRECORD b
 where DELETE_BIT=0 and MNGTYPE in(0,1,5) and ( @hdyz=0 and 
 (isnull(AUDITING_USER1,0)<=0  or  ((status_flag>=3 and  isnull(ORDER_EUSER1,0)<=0 and MNGTYPE=0 )) )
 ) and B.INPATIENT_ID=@INPATIENT_ID  AND B.BABY_ID=@BABY_ID
 and b.DEPT_ID not in(select DEPTID from SS_DEPT  )   
  
) TMP
	




GO


