IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SP_ZYYS_ORDERS_SELCARD]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SP_ZYYS_ORDERS_SELCARD]
GO
create PROCEDURE [dbo].[SP_ZYYS_ORDERS_SELCARD]
(
	@DEPTID BIGINT, 
	@WARD_DEPT BIGINT,
	@JGBM BIGINT
) 
AS
------------------------------------------------------------------------
-- SQL 存储过程
------------------------------------------------------------------------
BEGIN
	if(SELECT LTRIM(RTRIM(CONFIG)) FROM JC_CONFIG WHERE ID=6203)=0
		begin
 --如果是药剂科室  
 --6025药剂特殊治疗科室开医嘱时是否可以开项目0=是1=不是 Add by Tany2010-07-25  
 IF EXISTS(SELECT 1 FROM YP_YJKS WHERE DEPTID=@DEPTID)   
  AND (SELECT LTRIM(RTRIM(CONFIG)) FROM JC_CONFIG WHERE ID=6025)=1  
    BEGIN  
  SELECT DISTINCT 医嘱内容, 内容, 单位, 单价, 规格, S_DW,拼音码,五笔码,数字码,  
   DEFAULT_DEPT,DBO.FUN_JC_DEPTNAME(DEFAULT_DEPT) DEPTNAME, DWHL, ORDER_ID,  
   SHH NATION_CODE,TYPE,PSYP, 用法 , 0 ISCOMPLEX ,  
   基数,CASE WHEN KCL<=0 THEN '缺' ELSE '' END 缺,DWBL,BZSL,SYXL,LEN(拼音码) 排序,   
   XZJB,KCL,KCDW,XMLY,JGBM,'' 自付比,CASE WHEN XMLY=1 THEN GGID ELSE ORDER_ID END 项目代码,  
   YPJX,TLFL,S_YPJX 剂型 -- XZJB 限制级别  
  FROM  
  (  
   SELECT A.CJID ORDER_ID,SHH,A.PSYP,S_YPPM "医嘱内容",S_SCCJ "内容",  
    S_YPGG+(CASE WHEN ISNULL(LTRIM(RTRIM(YPSPMBZ)),'')<>'' THEN '('+LTRIM(RTRIM(YPSPMBZ))+')' ELSE '' END) "规格",  
    B.HLXS DWHL,E.DWMC "单位",LSJ "单价",S_YPDW S_DW,D.PYM "拼音码",D.WBM "五笔码",  
    D.SZM "数字码",--'[' + RTRIM(CAST(100*ZFBL AS SMALLINT)) + '%]' + S_SCCJS_YPPM + YPSPMBZ  
    C.KCL,C.DEPTID DEFAULT_DEPT,B.HLDW,S_SCCJ,  
    CASE B.STATITEM_CODE WHEN '01' THEN 1 ELSE CASE B.STATITEM_CODE WHEN '02'THEN 2 ELSE 3 END END TYPE,  
    C.DWBL,B.BZSL,B.SYXL,B.CFJB XZJB,F.DWMC KCDW,1 XMLY,@JGBM JGBM,A.GGID,A.YPJX,A.TLFL,S_YPJX,SYFF as 用法,--KCDW 库存单位 ,   
    (case when (select top 1 ISNULL(GJJBYW,0) from YP_YPGGD where GGID=A.GGID)=1 then '基' else '' end ) "基数"    
   FROM   
   (  
    SELECT CJID,SHH,GGID,S_YPSPM,S_YPPM,YPSPMBZ,S_YPGG,LSJ,S_YPDW,PSYP,S_SCCJ,ZFBL,YPJX,S_YPJX,TLFL FROM DBO.VI_YP_YPCD  
    
   ) A LEFT JOIN   
   (  
    SELECT GGID,HLXS,HLDW,BZSL,SYXL,STATITEM_CODE,CFJB,isnull(dbo.FUN_GETUsageNAMEById(SYFF),'') as SYFF  FROM YP_YPGGD  --syff add by jchl  
   ) B ON A.GGID=B.GGID    
   INNER JOIN  
   (  
       (  
            SELECT CJID,KCL,DEPTID,DWBL,ZXDW FROM YF_KCMX WHERE BDELETE=0 AND DEPTID=@DEPTID  
       )  
       UNION ALL  
          (  
     SELECT CJID,KCL,DEPTID,DWBL,ZXDW FROM YF_KCMX WHERE DEPTID=@WARD_DEPT AND BDELETE=0  
    )  
   ) C ON A.CJID=C.CJID  
   LEFT JOIN YP_YPBM D ON B.GGID=D.GGID  
   LEFT JOIN YP_YPDW E ON B.HLDW=E.ID  
   LEFT JOIN YP_YPDW F ON C.ZXDW=F.ID  
   LEFT JOIN YP_YPJX G ON A.YPJX=G.ID  
  ) KK WHERE KCL>0 --Modify By tany 2011-07-06  
  ORDER BY 排序 ASC,KCL DESC  
  RETURN  
 END  
  
 SELECT DISTINCT 医嘱内容, 内容, 单位, 单价, 规格, S_DW,拼音码,五笔码,数字码,  
  DEFAULT_DEPT,DBO.FUN_JC_DEPTNAME(DEFAULT_DEPT) DEPTNAME, DWHL, ORDER_ID,  
  SHH NATION_CODE,TYPE,PSYP, 用法 , 0 ISCOMPLEX ,  
  基数,CASE WHEN KCL<=0 THEN '缺' ELSE '' END 缺,DWBL,BZSL,SYXL,LEN(拼音码) 排序,   
  XZJB,KCL,KCDW,XMLY,JGBM,'' 自付比,CASE WHEN XMLY=1 THEN GGID ELSE ORDER_ID END 项目代码,  
  YPJX,TLFL,S_YPJX 剂型 -- XZJB 限制级别  
    FROM  
 (  
  SELECT A.CJID ORDER_ID,SHH,A.PSYP,S_YPPM "医嘱内容",S_SCCJ "内容",  
   S_YPGG+(CASE WHEN ISNULL(LTRIM(RTRIM(YPSPMBZ)),'')<>'' THEN '('+LTRIM(RTRIM(YPSPMBZ))+')' ELSE '' END) "规格",  
   B.HLXS DWHL,E.DWMC "单位",LSJ "单价",S_YPDW S_DW,D.PYM "拼音码",D.WBM "五笔码",  
   D.SZM "数字码",--'[' + RTRIM(CAST(100*ZFBL AS SMALLINT)) + '%]' + S_SCCJS_YPPM + YPSPMBZ  
            C.KCL,C.DEPTID DEFAULT_DEPT,B.HLDW,S_SCCJ,  
   CASE B.STATITEM_CODE WHEN '01' THEN 1 ELSE CASE B.STATITEM_CODE WHEN '02'THEN 2 ELSE 3 END END TYPE,  
   C.DWBL,B.BZSL,B.SYXL,B.CFJB XZJB,F.DWMC KCDW,1 XMLY,@JGBM JGBM,A.GGID,A.YPJX,A.TLFL,S_YPJX,SYFF as 用法,--KCDW 库存单位 ,   
   (case when (select top 1 ISNULL(GJJBYW,0) from YP_YPGGD where GGID=A.GGID)=1 then '基' else '' end ) "基数"    
        FROM   
  (  
   SELECT CJID,SHH,GGID,S_YPSPM,S_YPPM,YPSPMBZ,S_YPGG,LSJ,S_YPDW,PSYP,S_SCCJ,ZFBL,YPJX,S_YPJX,TLFL FROM DBO.VI_YP_YPCD  
  ) A LEFT JOIN   
  (  
    SELECT GGID,HLXS,HLDW,BZSL,SYXL,STATITEM_CODE,CFJB,isnull(dbo.FUN_GETUsageNAMEById(SYFF),'') as SYFF  FROM YP_YPGGD  --syff add by jchl  
  ) B ON A.GGID=B.GGID    
  INNER JOIN  
  (  
      (  
           SELECT CJID,KCL,DEPTID,DWBL,ZXDW FROM YF_KCMX WHERE BDELETE=0 AND DEPTID IN  
             (  
     SELECT DRUGSTORE_ID FROM JC_DEPT_DRUGSTORE WHERE DEPT_ID=@DEPTID AND FLAG<2 and DELETE_BIT=0  
       ) AND CJID NOT IN   
    (  
     SELECT CJID FROM YF_KCMX WHERE DEPTID=@WARD_DEPT AND BDELETE=0  
       )  
      )  
      UNION ALL  
         (  
    SELECT CJID,KCL,DEPTID,DWBL,ZXDW FROM YF_KCMX WHERE DEPTID IN (@WARD_DEPT,@DEPTID) AND BDELETE=0 --Modify By Tany 2010-07-25 增加本病区科室和开单科室  
   )  
  ) C ON A.CJID=C.CJID  
  LEFT JOIN YP_YPBM D ON B.GGID=D.GGID  
  LEFT JOIN YP_YPDW E ON B.HLDW=E.ID  
  LEFT JOIN YP_YPDW F ON C.ZXDW=F.ID  
  LEFT JOIN YP_YPJX G ON A.YPJX=G.ID  
 ) KK WHERE KCL>0 --Modify By tany 2011-07-06  
 UNION ALL  
 (  
 SELECT DISTINCT ORDER_NAME 医嘱内容,  isnull(BZ,'')+' '+SCCJ 内容, ORDER_UNIT 单位, DJ 单价 ,GG 规格,  
  ORDER_UNIT S_DW, 拼音码,WB_CODE 五笔码,D_CODE 数字码,  
  DEFAULT_DEPT,DBO.FUN_JC_DEPTNAME(DEFAULT_DEPT) DEPTNAME,  
  1 DWHL,ORDER_ID,HOICODE NATION_CODE,ORDER_TYPE TYPE,0 AS PSYP,DEFAULT_USAGE 用法 ,  
  ISCOMPLEX,'' 基数,'' 缺,1 AS DWBL,1 AS BZSL,0 AS SYXL,LEN(拼音码) 排序,4 XZJB,NULL KCL,  
  '' KCDW,2 XMLY,@JGBM JGBM,'' 自付比,ITEMID 项目代码,-1 YPJX,'' TLFL,'' 剂型  
 FROM(  
   SELECT A.ORDER_NAME ,A.ORDER_UNIT , CAST(C.PRICE AS DECIMAL(18,2)) DJ,LOWER(A.PY_CODE) 拼音码  ,  
    A.WB_CODE ,A.D_CODE ,   --d_code取医嘱项目表的 Modify By Tany 2015-02-02
    CASE WHEN A.DEFAULT_DEPT IS NULL OR A.DEFAULT_DEPT=-1 OR A.DEFAULT_DEPT=0 THEN @DEPTID ELSE A.DEFAULT_DEPT END DEFAULT_DEPT,   
    CAST(CAST(A.ORDER_ID AS INT) AS CHARACTER(10)) AS ORDER_ID,A.ORDER_TYPE,  
    A.HOICODE,A.BZ BZ,A.DEFAULT_USAGE ,B.TC_FLAG ISCOMPLEX,ITEMID,C.GG,C.SCCJ  
        FROM   
   (  
    SELECT ORDER_NAME, ORDER_UNIT, A.ORDER_ID, ORDER_TYPE,PY_CODE,  
     WB_CODE,HOICODE,BZ,DEFAULT_USAGE,CASE WHEN B.EXEC_DEPT>0 THEN B.EXEC_DEPT ELSE DEFAULT_DEPT END DEFAULT_DEPT,A.D_CODE 
             FROM JC_HOITEMDICTION A   
    LEFT JOIN --Modify By Tany 2010-01-25 如果多个执行科室，首先取本机构编码的执行科室  
    (SELECT ORDER_ID,EXEC_DEPT   
     FROM JC_HOI_DEPT B INNER JOIN JC_DEPT_PROPERTY C ON B.EXEC_DEPT=C.DEPT_ID  
     WHERE C.JGBM=@JGBM and dbo.fun_getFirstLevelDeptId(B.EXEC_DEPT)=dbo.fun_getFirstLevelDeptId(@DEPTID)) B --这里加上一个函数来验证他们的一级科室是不是同一个，来判断不同的院区 Modify By Tany 2015-06-04
    ON A.ORDER_ID=B.ORDER_ID  
    WHERE DELETE_BIT = 0 --AND ORDER_TYPE<8  
         ) A  
         LEFT OUTER JOIN JC_HOI_HDI B ON A.ORDER_ID = B.HOITEM_ID  
         LEFT OUTER JOIN  
      (  
    SELECT 0 ROWNO,B.STD_CODE AS ITEMCODE,B.ITEM_NAME AS ITEMNAME,'' AS STANDARD,B.ITEM_UNIT AS UNIT,1 AS DWBL,B.RETAIL_PRICE AS PRICE,LOWER(B.PY_CODE) 拼音码,  
     B.ITEM_CODE AS D_CODE,B.WB_CODE, B.ZXDD_ID AS EXECDEPTID,CASE WHEN D.NAME IS NULL THEN '' ELSE D.NAME END  AS EXECDEPT,'' AS PROD_AREA,  
     B.ITEM_ID AS ITEMID,-1 AS UNIT_ID,B.RETAIL_PRICE AS ITEMPFJ,B.RETAIL_PRICE AS ITEMYHJ, STATITEM_CODE AS BIGITEMCODE ,-1 AS TCID,C.CFLX_CODE AS  PRESCTYPE,B.JGBM,
     B.GG,B.SCCJ
    FROM JC_HSITEMDICTION AS B  
    INNER JOIN JC_STAT_ITEM AS C ON B.STATITEM_CODE=C.CODE  
    LEFT JOIN JC_DEPT_PROPERTY D ON B.ZXDD_ID=D.DEPT_ID WHERE B.DELETE_BIT=0  
    UNION ALL  
    SELECT 0 ROWNO,'' AS ITEMCODE,B.ITEM_NAME AS ITEMNAME,'' AS STANDARD,B.ITEM_UNIT AS UNIT,1 AS DWBL,TCPRICE AS PRICE,LOWER(B.PY_CODE) 拼音码,B.CODE AS D_CODE,  
           B.WB_CODE,B.EXEC_DEPT AS EXECDEPTID,CASE WHEN D.NAME IS NULL THEN '' ELSE D.NAME END  AS EXECDEPT,'' AS PROD_AREA,B.ITEM_ID AS ITEMID,-1 AS UNIT_ID,  
           TCPRICE AS ITEMPFJ,TCPRICE AS ITEMYHJ, '' AS BIGITEMCODE,B.ITEM_ID AS TCID,'-1' AS PRESCTYPE,B.JGBM,'',''  
    FROM(  
     SELECT A.*,PRICE AS TCPRICE FROM JC_TC AS A  
            ) AS B  
    LEFT JOIN JC_DEPT_PROPERTY D ON B.EXEC_DEPT=D.DEPT_ID  
    WHERE B.DELETE_BIT=0  
   ) C ON C.ITEMID=B.HDITEM_ID AND C.TCID=B.TCID AND C.JGBM=@JGBM  
   WHERE ORDER_TYPE=7 OR ITEMID IS NOT NULL --收费项目被删除的不再显示  
     ) AS AA  
 ) ORDER BY 排序 ASC,KCL DESC  
		end
	else
		begin
	--如果是药剂科室
	--6025药剂特殊治疗科室开医嘱时是否可以开项目0=是1=不是 Add by Tany2010-07-25
	IF EXISTS(SELECT 1 FROM YP_YJKS WHERE DEPTID=@DEPTID) 
		AND (SELECT LTRIM(RTRIM(CONFIG)) FROM JC_CONFIG WHERE ID=6025)=1
    BEGIN
		SELECT DISTINCT 医嘱内容, 内容, 单位, 单价, 规格, S_DW,拼音码,五笔码,数字码,
			DEFAULT_DEPT,DBO.FUN_JC_DEPTNAME(DEFAULT_DEPT) DEPTNAME, DWHL, ORDER_ID,
			SHH NATION_CODE,TYPE,PSYP, 用法 , 0 ISCOMPLEX ,
			基数,CASE WHEN KCL<=0 THEN '缺' ELSE '' END 缺,DWBL,BZSL,SYXL,LEN(拼音码) 排序, 
			XZJB,KCL,KCDW,XMLY,JGBM,'' 自付比,CASE WHEN XMLY=1 THEN GGID ELSE ORDER_ID END 项目代码,
			YPJX,TLFL,S_YPJX 剂型 -- XZJB 限制级别
		FROM
		(
			SELECT A.CJID ORDER_ID,SHH,A.PSYP,S_YPPM "医嘱内容",S_SCCJ "内容",
				S_YPGG+(CASE WHEN ISNULL(LTRIM(RTRIM(YPSPMBZ)),'')<>'' THEN '('+LTRIM(RTRIM(YPSPMBZ))+')' ELSE '' END) "规格",
				B.HLXS DWHL,E.DWMC "单位",LSJ "单价",S_YPDW S_DW,D.PYM "拼音码",D.WBM "五笔码",
				D.SZM "数字码",--'[' + RTRIM(CAST(100*ZFBL AS SMALLINT)) + '%]' + S_SCCJS_YPPM + YPSPMBZ
				C.KCL,C.DEPTID DEFAULT_DEPT,B.HLDW,S_SCCJ,
				CASE B.STATITEM_CODE WHEN '01' THEN 1 ELSE CASE B.STATITEM_CODE WHEN '02'THEN 2 ELSE 3 END END TYPE,
				C.DWBL,B.BZSL,B.SYXL,B.CFJB XZJB,F.DWMC KCDW,1 XMLY,@JGBM JGBM,A.GGID,A.YPJX,A.TLFL,S_YPJX,SYFF as 用法,--KCDW 库存单位
				(case when (select top 1 ISNULL(GJJBYW,0) from YP_YPGGD where GGID=A.GGID)=1 then '基' else '' end ) "基数" 	
			FROM 
			(
				SELECT CJID,SHH,GGID,S_YPSPM,S_YPPM,YPSPMBZ,S_YPGG,LSJ,S_YPDW,PSYP,S_SCCJ,ZFBL,YPJX,S_YPJX,TLFL FROM DBO.VI_YP_YPCD
			) A LEFT JOIN 
			(
				SELECT GGID,HLXS,HLDW,BZSL,SYXL,STATITEM_CODE,CFJB,isnull(dbo.FUN_GETUsageNAMEById(SYFF),'') as SYFF  FROM YP_YPGGD  --syff add by jchl  
			) B ON A.GGID=B.GGID  
			INNER JOIN
			(
    			(
	         		SELECT CJID,KCL,DEPTID,DWBL,ZXDW FROM YF_KCMX WHERE BDELETE=0 AND DEPTID=@DEPTID
    			)
   				UNION ALL
       			(
					SELECT CJID,KCL,DEPTID,DWBL,ZXDW FROM YF_KCMX WHERE DEPTID=@WARD_DEPT AND BDELETE=0
				)
			) C ON A.CJID=C.CJID
			LEFT JOIN YP_YPBM D ON B.GGID=D.GGID
			LEFT JOIN YP_YPDW E ON B.HLDW=E.ID
			LEFT JOIN YP_YPDW F ON C.ZXDW=F.ID
			LEFT JOIN YP_YPJX G ON A.YPJX=G.ID
		) KK WHERE KCL>0 --Modify By tany 2011-07-06
		ORDER BY 排序 ASC,KCL DESC
		RETURN
	END

	SELECT DISTINCT 医嘱内容, 内容, 单位, 单价, 规格, S_DW,拼音码,五笔码,数字码,
		DEFAULT_DEPT,DBO.FUN_JC_DEPTNAME(DEFAULT_DEPT) DEPTNAME, DWHL, ORDER_ID,
		SHH NATION_CODE,TYPE,PSYP, 用法 , 0 ISCOMPLEX ,
		基数,CASE WHEN KCL<=0 THEN '缺' ELSE '' END 缺,DWBL,BZSL,SYXL,LEN(拼音码) 排序, 
		XZJB,KCL,KCDW,XMLY,JGBM,'' 自付比,CASE WHEN XMLY=1 THEN GGID ELSE ORDER_ID END 项目代码,
		YPJX,TLFL,S_YPJX 剂型 -- XZJB 限制级别
    FROM
	(
		SELECT A.CJID ORDER_ID,SHH,A.PSYP,S_YPPM "医嘱内容",S_SCCJ "内容",
			S_YPGG+(CASE WHEN ISNULL(LTRIM(RTRIM(YPSPMBZ)),'')<>'' THEN '('+LTRIM(RTRIM(YPSPMBZ))+')' ELSE '' END) "规格",
			B.HLXS DWHL,E.DWMC "单位",LSJ "单价",S_YPDW S_DW,D.PYM "拼音码",D.WBM "五笔码",
			D.SZM "数字码",--'[' + RTRIM(CAST(100*ZFBL AS SMALLINT)) + '%]' + S_SCCJS_YPPM + YPSPMBZ
            C.KCL,C.DEPTID DEFAULT_DEPT,B.HLDW,S_SCCJ,
			CASE B.STATITEM_CODE WHEN '01' THEN 1 ELSE CASE B.STATITEM_CODE WHEN '02'THEN 2 ELSE 3 END END TYPE,
			C.DWBL,B.BZSL,B.SYXL,B.CFJB XZJB,F.DWMC KCDW,1 XMLY,@JGBM JGBM,A.GGID,A.YPJX,A.TLFL,S_YPJX,SYFF as 用法,--KCDW 库存单位
			(case when (select top 1 ISNULL(GJJBYW,0) from YP_YPGGD where GGID=A.GGID)=1 then '基' else '' end ) "基数" 	
        FROM 
		(
			SELECT CJID,SHH,GGID,S_YPSPM,S_YPPM,YPSPMBZ,S_YPGG,LSJ,S_YPDW,PSYP,S_SCCJ,ZFBL,YPJX,S_YPJX,TLFL FROM DBO.VI_YP_YPCD
		) A LEFT JOIN 
		(
				SELECT GGID,HLXS,HLDW,BZSL,SYXL,STATITEM_CODE,CFJB,isnull(dbo.FUN_GETUsageNAMEById(SYFF),'') as SYFF  FROM YP_YPGGD  --syff add by jchl 
		) B ON A.GGID=B.GGID  
		INNER JOIN
		(
    		(
	         	SELECT CJID,KCL,DEPTID,DWBL,ZXDW FROM YF_KCMX WHERE BDELETE=0 AND DEPTID IN
            	(
					SELECT DRUGSTORE_ID FROM JC_DEPT_DRUGSTORE WHERE DEPT_ID=@DEPTID AND FLAG<2 and DELETE_BIT=0
    			) AND CJID NOT IN 
				(
					SELECT CJID FROM YF_KCMX WHERE DEPTID=@WARD_DEPT AND BDELETE=0
		   		)
    		)
   			UNION ALL
       		(
				SELECT CJID,KCL,DEPTID,DWBL,ZXDW FROM YF_KCMX WHERE DEPTID IN (@WARD_DEPT,@DEPTID) AND BDELETE=0 --Modify By Tany 2010-07-25 增加本病区科室和开单科室
			)
		) C ON A.CJID=C.CJID
		LEFT JOIN YP_YPBM D ON B.GGID=D.GGID
		LEFT JOIN YP_YPDW E ON B.HLDW=E.ID
		LEFT JOIN YP_YPDW F ON C.ZXDW=F.ID
		LEFT JOIN YP_YPJX G ON A.YPJX=G.ID
	) KK WHERE KCL>0 --Modify By tany 2011-07-06
	UNION ALL
	(
	SELECT DISTINCT ORDER_NAME 医嘱内容,  isnull(BZ,'')+' '+SCCJ 内容, ORDER_UNIT 单位, DJ 单价 ,GG 规格,
		ORDER_UNIT S_DW, 拼音码,WB_CODE 五笔码,D_CODE 数字码,
		DEFAULT_DEPT,DBO.FUN_JC_DEPTNAME(DEFAULT_DEPT) DEPTNAME,
		1 DWHL,ORDER_ID,HOICODE NATION_CODE,ORDER_TYPE TYPE,0 AS PSYP,DEFAULT_USAGE 用法 ,
		ISCOMPLEX,'' 基数,'' 缺,1 AS DWBL,1 AS BZSL,0 AS SYXL,LEN(拼音码) 排序,4 XZJB,NULL KCL,
		'' KCDW,2 XMLY,@JGBM JGBM,'' 自付比,ITEMID 项目代码,-1 YPJX,'' TLFL,'' 剂型
	FROM(
			SELECT A.ORDER_NAME ,A.ORDER_UNIT , CAST(C.PRICE AS DECIMAL(18,2)) DJ,LOWER(A.PY_CODE) 拼音码  ,
				A.WB_CODE ,A.D_CODE , --d_code取医嘱项目表的 Modify By Tany 2015-02-02
				CASE WHEN A.DEFAULT_DEPT IS NULL OR A.DEFAULT_DEPT=-1 OR A.DEFAULT_DEPT=0 THEN @DEPTID ELSE A.DEFAULT_DEPT END DEFAULT_DEPT, 
				CAST(CAST(A.ORDER_ID AS INT) AS CHARACTER(10)) AS ORDER_ID,A.ORDER_TYPE,
				A.HOICODE,A.BZ BZ,A.DEFAULT_USAGE ,B.TC_FLAG ISCOMPLEX,ITEMID,C.GG,C.SCCJ
      		FROM 
			(
				SELECT ORDER_NAME, ORDER_UNIT, A.ORDER_ID, ORDER_TYPE,PY_CODE,
					WB_CODE,HOICODE,BZ,DEFAULT_USAGE,CASE WHEN B.EXEC_DEPT>0 THEN B.EXEC_DEPT ELSE DEFAULT_DEPT END DEFAULT_DEPT,A.D_CODE
	            FROM JC_HOITEMDICTION A 
				LEFT JOIN --Modify By Tany 2010-01-25 如果多个执行科室，首先取本机构编码的执行科室
				(SELECT ORDER_ID,EXEC_DEPT 
				 FROM JC_HOI_DEPT B INNER JOIN JC_DEPT_PROPERTY C ON B.EXEC_DEPT=C.DEPT_ID
				 WHERE C.JGBM=@JGBM and dbo.fun_getFirstLevelDeptId(B.EXEC_DEPT)=dbo.fun_getFirstLevelDeptId(@DEPTID)) B --这里加上一个函数来验证他们的一级科室是不是同一个，来判断不同的院区 Modify By Tany 2015-06-04
				ON A.ORDER_ID=B.ORDER_ID
				WHERE DELETE_BIT = 0 --AND ORDER_TYPE<8
				--Modify By jchl 武汉中心医院开医嘱权限控制
				and 
				(exists (select 1 from jc_yzqx_ks t1 
								inner join jc_yzqx t2 on t1.qxid=t2.id and t2.jlzt=0 
								inner join jc_yzqxmx t3 on t1.qxid=t3.qxid and t3.order_type in ('4','5','6','7','8','9')
								where t1.deptid=@DEPTID and t3.order_id=A.ORDER_ID)
				--Modify By Tany 2015-07-02 没有匹配的不显示
				--or not exists((select 1 from JC_YZQXMX t3 where A.ORDER_ID=t3.ORDER_ID))
				or ORDER_TYPE=7
				)
	        ) A
	        LEFT OUTER JOIN JC_HOI_HDI B ON A.ORDER_ID = B.HOITEM_ID
	        LEFT OUTER JOIN
	   		(
				SELECT 0 ROWNO,B.STD_CODE AS ITEMCODE,B.ITEM_NAME AS ITEMNAME,'' AS STANDARD,B.ITEM_UNIT AS UNIT,1 AS DWBL,B.RETAIL_PRICE AS PRICE,LOWER(B.PY_CODE) 拼音码,
					B.ITEM_CODE AS D_CODE,B.WB_CODE, B.ZXDD_ID AS EXECDEPTID,CASE WHEN D.NAME IS NULL THEN '' ELSE D.NAME END  AS EXECDEPT,'' AS PROD_AREA,
					B.ITEM_ID AS ITEMID,-1 AS UNIT_ID,B.RETAIL_PRICE AS ITEMPFJ,B.RETAIL_PRICE AS ITEMYHJ, STATITEM_CODE AS BIGITEMCODE ,-1 AS TCID,C.CFLX_CODE AS  PRESCTYPE,B.JGBM,
					B.GG,B.SCCJ
				FROM JC_HSITEMDICTION AS B
				INNER JOIN JC_STAT_ITEM AS C ON B.STATITEM_CODE=C.CODE
				LEFT JOIN JC_DEPT_PROPERTY D ON B.ZXDD_ID=D.DEPT_ID WHERE B.DELETE_BIT=0
				UNION ALL
				SELECT 0 ROWNO,'' AS ITEMCODE,B.ITEM_NAME AS ITEMNAME,'' AS STANDARD,B.ITEM_UNIT AS UNIT,1 AS DWBL,TCPRICE AS PRICE,LOWER(B.PY_CODE) 拼音码,B.CODE AS D_CODE,
				       B.WB_CODE,B.EXEC_DEPT AS EXECDEPTID,CASE WHEN D.NAME IS NULL THEN '' ELSE D.NAME END  AS EXECDEPT,'' AS PROD_AREA,B.ITEM_ID AS ITEMID,-1 AS UNIT_ID,
				       TCPRICE AS ITEMPFJ,TCPRICE AS ITEMYHJ, '' AS BIGITEMCODE,B.ITEM_ID AS TCID,'-1' AS PRESCTYPE,B.JGBM,'',''
				FROM(
					SELECT A.*,PRICE AS TCPRICE FROM JC_TC AS A
		    		    ) AS B
				LEFT JOIN JC_DEPT_PROPERTY D ON B.EXEC_DEPT=D.DEPT_ID
				WHERE B.DELETE_BIT=0
			) C ON C.ITEMID=B.HDITEM_ID AND C.TCID=B.TCID AND C.JGBM=@JGBM
			WHERE ORDER_TYPE=7 OR ITEMID IS NOT NULL --收费项目被删除的不再显示
	    ) AS AA
	) ORDER BY 排序 ASC,KCL DESC
		end
END

GO


