IF  EXISTS (SELECT * FROM SYS.TRIGGERS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TR_YF_FY_INSERTFOREVENTLOG]'))
DROP TRIGGER [DBO].[TR_YF_FY_INSERTFOREVENTLOG]
GO
--Add By Tany 2014-05-08 状态变更插入事件表
CREATE TRIGGER TR_YF_FY_INSERTFOREVENTLOG
	ON YF_FY 
	AFTER INSERT
AS   
SET NOCOUNT ON

DECLARE @JZCFBZ INT
DECLARE @TFBZ INT

SELECT @JZCFBZ=JZCFBZ,@TFBZ=TFBZ
FROM INSERTED

if(@JZCFBZ=0 and @TFBZ=0)
begin

	insert into EVENTLOG(EVENT,CATEGORY,BIZID) 
	select 'MZFYZT','YF_FY',CFXH from inserted
	return
end

if(@JZCFBZ=0 and @TFBZ=1)
begin

	insert into EVENTLOG(EVENT,CATEGORY,BIZID) 
	select 'MZFYZTTY','YF_FY',CFXH from inserted
	return
end