IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[JC_HSITEMDICTION]'))
DROP VIEW [dbo].[JC_HSITEMDICTION]
GO
CREATE VIEW [dbo].[JC_HSITEMDICTION]
AS
SELECT     dbo.JC_HSITEM.ITEM_ID, dbo.JC_HSITEM.P_ITEM_ID, dbo.JC_HSITEM.P_ITEM_CODE, dbo.JC_HSITEM.ITEM_CODE, 
  dbo.JC_HSITEM.ITEM_DESCRIBE, dbo.JC_HSITEM.NSITEM_ID, dbo.JC_HSITEM.ITEM_NAME, dbo.JC_HSITEM.ITEM_UNIT, 
  dbo.JC_HSITEMPRICE.PRICE AS COST_PRICE, dbo.JC_HSITEMPRICE.PRICE AS RETAIL_PRICE, dbo.JC_HSITEM.PRICE_ID, 
  dbo.JC_HSITEM.PY_CODE, dbo.JC_HSITEM.WB_CODE, dbo.JC_HSITEM.DELETE_BIT, dbo.JC_HSITEM.EFFECT_BDATE, 
  dbo.JC_HSITEM.EFFECT_EDATE, dbo.JC_HSITEM.ISCOMPLEX, dbo.JC_HSITEM.INVOICE_ID, dbo.JC_HSITEM.ZXDD_ID, dbo.JC_HSITEM.MXID, 
  dbo.JC_HSITEM.STATITEM_CODE, dbo.JC_HSITEM.ZY_USE, dbo.JC_HSITEM.MZ_USE, dbo.JC_HSITEM.YJ_USE, dbo.JC_HSITEM.CYZXM, 
  dbo.JC_HSITEM.CFLX, dbo.JC_HSITEM.BOOKING, dbo.JC_HSITEM.ORDER_NAME, dbo.JC_HSITEM.ORDER_PYM, dbo.JC_HSITEM.ORDER_WBM, 
  dbo.JC_HSITEM.SAMPLE, dbo.JC_HSITEM.EXEC_DEPT_RATE, dbo.JC_HSITEM.ORDER_DEPT_RATE, dbo.JC_HSITEM.STD_CODE, 
  dbo.JC_HSITEM.last_operator, dbo.JC_HSITEMPRICE.JGBM, dbo.JC_HSITEMPRICE.JGMC, dbo.JC_HSITEMPRICE.MIN_PRICE, 
  dbo.JC_HSITEMPRICE.MAX_PRICE,dbo.JC_HSITEM.GG,dbo.JC_HSITEM.SCCJ
FROM   dbo.JC_HSITEM INNER JOIN   dbo.JC_HSITEMPRICE 
ON dbo.JC_HSITEM.ITEM_ID = dbo.JC_HSITEMPRICE.HSITEMID


GO


