//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5477
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.5477 版自动生成。
// 
#pragma warning disable 1591

namespace Ts_HisVsLis_interface.WebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="lisServiceSoap", Namespace="http://tempuri.org/23")]
    public partial class lisService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LisServiceInputOperationCompleted;
        
        private System.Threading.SendOrPostCallback Event_logOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertMzOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public lisService() {
            this.Url = global::Ts_HisVsLis_interface.Properties.Settings.Default.Ts_HisVsLis_interface_WebReference_lisService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LisServiceInputCompletedEventHandler LisServiceInputCompleted;
        
        /// <remarks/>
        public event Event_logCompletedEventHandler Event_logCompleted;
        
        /// <remarks/>
        public event InsertMzCompletedEventHandler InsertMzCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/23/LisServiceInput", RequestNamespace="http://tempuri.org/23", ResponseNamespace="http://tempuri.org/23", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LisServiceInput(string xml_content) {
            object[] results = this.Invoke("LisServiceInput", new object[] {
                        xml_content});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LisServiceInputAsync(string xml_content) {
            this.LisServiceInputAsync(xml_content, null);
        }
        
        /// <remarks/>
        public void LisServiceInputAsync(string xml_content, object userState) {
            if ((this.LisServiceInputOperationCompleted == null)) {
                this.LisServiceInputOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLisServiceInputOperationCompleted);
            }
            this.InvokeAsync("LisServiceInput", new object[] {
                        xml_content}, this.LisServiceInputOperationCompleted, userState);
        }
        
        private void OnLisServiceInputOperationCompleted(object arg) {
            if ((this.LisServiceInputCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LisServiceInputCompleted(this, new LisServiceInputCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/23/Event_log", RequestNamespace="http://tempuri.org/23", ResponseNamespace="http://tempuri.org/23", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Event_log(string id) {
            object[] results = this.Invoke("Event_log", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Event_logAsync(string id) {
            this.Event_logAsync(id, null);
        }
        
        /// <remarks/>
        public void Event_logAsync(string id, object userState) {
            if ((this.Event_logOperationCompleted == null)) {
                this.Event_logOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEvent_logOperationCompleted);
            }
            this.InvokeAsync("Event_log", new object[] {
                        id}, this.Event_logOperationCompleted, userState);
        }
        
        private void OnEvent_logOperationCompleted(object arg) {
            if ((this.Event_logCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Event_logCompleted(this, new Event_logCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/23/InsertMz", RequestNamespace="http://tempuri.org/23", ResponseNamespace="http://tempuri.org/23", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertMz(MZOrderInfos infos) {
            object[] results = this.Invoke("InsertMz", new object[] {
                        infos});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertMzAsync(MZOrderInfos infos) {
            this.InsertMzAsync(infos, null);
        }
        
        /// <remarks/>
        public void InsertMzAsync(MZOrderInfos infos, object userState) {
            if ((this.InsertMzOperationCompleted == null)) {
                this.InsertMzOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertMzOperationCompleted);
            }
            this.InvokeAsync("InsertMz", new object[] {
                        infos}, this.InsertMzOperationCompleted, userState);
        }
        
        private void OnInsertMzOperationCompleted(object arg) {
            if ((this.InsertMzCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertMzCompleted(this, new InsertMzCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wuhanzhongxinyiyuan.org")]
    public partial class MZOrderInfos {
        
        private MZOrderInfo[] orderInfoField;
        
        /// <remarks/>
        public MZOrderInfo[] OrderInfo {
            get {
                return this.orderInfoField;
            }
            set {
                this.orderInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wuhanzhongxinyiyuan.org")]
    public partial class MZOrderInfo {
        
        private string slField;
        
        private string birthdayField;
        
        private string billNoField;
        
        private string fpNoField;
        
        private string chargeDTField;
        
        private string genderField;
        
        private string nameField;
        
        private string orderDeptField;
        
        private string orderDeptIdField;
        
        private string orderDocIdField;
        
        private string orderDocNameField;
        
        private string orderSystemField;
        
        private string patientIdField;
        
        private string testItemIdField;
        
        private string testItemNameField;
        
        private string tfbzField;
        
        /// <remarks/>
        public string SL {
            get {
                return this.slField;
            }
            set {
                this.slField = value;
            }
        }
        
        /// <remarks/>
        public string birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
            }
        }
        
        /// <remarks/>
        public string billNo {
            get {
                return this.billNoField;
            }
            set {
                this.billNoField = value;
            }
        }
        
        /// <remarks/>
        public string fpNo {
            get {
                return this.fpNoField;
            }
            set {
                this.fpNoField = value;
            }
        }
        
        /// <remarks/>
        public string chargeDT {
            get {
                return this.chargeDTField;
            }
            set {
                this.chargeDTField = value;
            }
        }
        
        /// <remarks/>
        public string gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string orderDept {
            get {
                return this.orderDeptField;
            }
            set {
                this.orderDeptField = value;
            }
        }
        
        /// <remarks/>
        public string orderDeptId {
            get {
                return this.orderDeptIdField;
            }
            set {
                this.orderDeptIdField = value;
            }
        }
        
        /// <remarks/>
        public string orderDocId {
            get {
                return this.orderDocIdField;
            }
            set {
                this.orderDocIdField = value;
            }
        }
        
        /// <remarks/>
        public string orderDocName {
            get {
                return this.orderDocNameField;
            }
            set {
                this.orderDocNameField = value;
            }
        }
        
        /// <remarks/>
        public string orderSystem {
            get {
                return this.orderSystemField;
            }
            set {
                this.orderSystemField = value;
            }
        }
        
        /// <remarks/>
        public string patientId {
            get {
                return this.patientIdField;
            }
            set {
                this.patientIdField = value;
            }
        }
        
        /// <remarks/>
        public string testItemId {
            get {
                return this.testItemIdField;
            }
            set {
                this.testItemIdField = value;
            }
        }
        
        /// <remarks/>
        public string testItemName {
            get {
                return this.testItemNameField;
            }
            set {
                this.testItemNameField = value;
            }
        }
        
        /// <remarks/>
        public string tfbz {
            get {
                return this.tfbzField;
            }
            set {
                this.tfbzField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void LisServiceInputCompletedEventHandler(object sender, LisServiceInputCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LisServiceInputCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LisServiceInputCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void Event_logCompletedEventHandler(object sender, Event_logCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Event_logCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Event_logCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void InsertMzCompletedEventHandler(object sender, InsertMzCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertMzCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertMzCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591