IF  EXISTS (SELECT * FROM SYS.TRIGGERS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TR_MZ_YYGHLB_UPDATEFOREVENTLOG]'))
DROP TRIGGER [DBO].[TR_MZ_YYGHLB_UPDATEFOREVENTLOG]
GO
--Add By Tany 2015-09-29 更新预约信息
CREATE TRIGGER [dbo].[TR_MZ_YYGHLB_UPDATEFOREVENTLOG]
	ON [dbo].[MZ_YYGHLB] 
	AFTER UPDATE
AS   
SET NOCOUNT ON

if(UPDATE(ghxxid))
begin

	insert into EVENTLOG(EVENT,CATEGORY,BIZID) 
	select 'GetGhMsgInfo','MZ_YYGHLB',ghxxid 
	from inserted
	where ghxxid is not null

end
GO