IF  EXISTS (SELECT * FROM SYS.TRIGGERS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TR_JC_DEPT_PROPERTY_INSERTFOREVENTLOG]'))
DROP TRIGGER [DBO].[TR_JC_DEPT_PROPERTY_INSERTFOREVENTLOG]
GO
--Add By Tany 2015-03-04 状态变更插入事件表
--CREATE TRIGGER [dbo].[TR_JC_DEPT_PROPERTY_INSERTFOREVENTLOG]
--	ON [dbo].[JC_DEPT_PROPERTY] 
--	AFTER INSERT,UPDATE
--AS   
--SET NOCOUNT ON

--insert into EVENTLOG(EVENT,CATEGORY,BIZID) 
--select 'JC_DEPT_ZNYK','JC_DEPT_PROPERTY',DEPT_ID from inserted