--webservice»’÷æ±Ì Add By Tany 2015-10-09
CREATE TABLE [dbo].[WS_LOG](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[BIZID] [varchar](100) NULL,
	[NOTE] [varchar](2000) NULL,
	[DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_WS_LOG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE NONCLUSTERED INDEX IX_WS_LOG_BIZID ON dbo.WS_LOG
	(
	BIZID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX IX_WS_LOG_DATE ON dbo.WS_LOG
	(
	DATE
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

